### ISSUE TITLE
add in option to generate biaxial plots

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#10]
useful for assessing accuracy of segmentation, can do log/log plots of marker intensity per cell to get a sense of overlap of distinct markers and co-expression of related markers

**Comment by alex-l-kong** [comment]
These much older issues caught my eye tonight. Is this is a task that we can mark as a good first issue, or has the project changed enough to necessitate something much different here?

**Comment by ngreenwald** [comment]
Agreed, this would be a good first issue
