### ISSUE TITLE
Make 99.9 normalization optional on function cell_som_clustering.train_cell_som

### ISSUE THREAD

**Issue by JLrumberger** [angelolab/ark-analysis#1000]
**Is your feature request related to a problem? Please describe.**
I want to use the [templates/generic_cell_clustering.ipynb](https://github.com/angelolab/ark-analysis/blob/main/templates/generic_cell_clustering.ipynb) on data from the cell classification model. @ngreenwald mentioned that I should run the SOM clustering without 99.9 percentile normalization on this data, but the function `train_cell_som` and the downstream class `CellSOMCluster` do not allow me to turn off normalization.

**Describe the solution you'd like**
Add a flag to [cluster_helpers.CellSOMCluster](https://github.com/angelolab/ark-analysis/blob/main/src/ark/phenotyping/cluster_helpers.py) to the init called `normalize` with default `True` and add control flow to the init to make `self.train_data = self.normalize_data(self.train_data)` optional.

Add a flag to [cell_som_clustering.train_cell_som](https://github.com/angelolab/ark-analysis/blob/main/src/ark/phenotyping/cell_som_clustering.py) called `normalize` with default `True` and provide this argument to `cluster_helpers.CellSOMCluster`.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by srivarra** [comment]
congrats on issue / pr number 1000! Lorenz! 🥳
