### ISSUE TITLE
Issue setting up the repo on Windows

### ISSUE THREAD

**Issue by jlqm2** [angelolab/ark-analysis#1004]
I'm trying to set up the repo on Windows and I keep getting the following error when I run "bash start_docker.sh": 

C:\Users\jlqm2\ark-analysis>bash start_docker.sh
start_jupyter.sh: line 8: syntax error: unexpected end of file

**Comment by srivarra** [comment]
The bash scripts need to be converted with the `dos2unix` tool installed using `wsl`. 
Once you have `wsl` and `dos2unix` you will need to run the following command `wsl dos2unix` for `start_docker.sh` `update_notebooks.sh` and `start_jupyter.sh` respectively. Then will be able to run `start_docker.sh` successfully.

We have some documentation here which goes over installing wsl / docker, converting the bash scripts.
- [Windows setup documentation](
https://github.com/angelolab/ark-analysis/blob/main/docs/_rtd/windows_setup.md)

**Comment by julienmortier** [comment]
I had the same issue as Jlqm2 and it was fixed by running "wsl dos2unix start_jupyter.sh" as srivarra suggested. However, this is not mentioned in the documentation for Windows configuration and is also not mentioned in the youtube video (https://www.youtube.com/watch?v=EXMGdi_Izdw&t=1s).

**Comment by srivarra** [comment]
@julienmortier Thanks for pointing that out, the docs will be updated in #1012.
