### ISSUE TITLE
Issue with segmentation mask stitching

### ISSUE THREAD

**Issue by camisowers** [angelolab/ark-analysis#1009]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
Our segmentations masks apparently have a fun 3d shape, so (512, 512) images are actually stored as (1, 512, 512) arrays. This complicates things for stitching and throws an error in the [Stitch Segmentation Output Images](https://github.com/angelolab/ark-analysis/blob/main/templates/Image_Stitching.ipynb) section of Image_Stitching.ipynb. 

**Expected behavior**
Should be able to stitch the segmentation masks by just squeezing it into a 2d array first.

**To Reproduce**
Attempt to stitch segmentation masks.

**Comment by ngreenwald** [comment]
I think this has caused problems in a few other places. I think it would be easiest to modify the segmentation pipeline to save 2D tiffs rather than modifying the loading functions.

**Comment by camisowers** [comment]
Yeah I thought about just modifying `create_deepcell_output()`, but wasn't sure if changing it would cause more issues down the pipeline. Sounds good though!

**Comment by ngreenwald** [comment]
It might, but if it does, we should find those issues and fix them, since it's only the place in the whole repo where we have 3D tiffs for no reason.
