### ISSUE TITLE
Missing docker import: alpineer

### ISSUE THREAD

**Issue by dtebaykin** [angelolab/ark-analysis#1013]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
Missing docker import: alpineer for Candace's new script in ark-analysis (ark-analysis has been updated to the latest github version)

**Expected behavior**
Would like to run the script

**To Reproduce**
Please either copy/paste or screenshot all of the code you ran which produced the error. In addition, copy the full error message. 
![Screenshot 2023-06-13 at 4 48 22 PM](https://github.com/angelolab/ark-analysis/assets/8460227/6f097a72-5e10-4737-9068-c56d00a3b474)

**Comment by srivarra** [comment]
The current Docker Image is using Python 3.8, and we recently adjusted the minimum Python to 3.9 for all the relevant repos. There will be a new release ready by the end of the week which should fix this issue.
