### ISSUE TITLE
Pixie cell clustering should ignore cells that don't contain any pixel clusters in it

### ISSUE THREAD

**Issue by cliu72** [angelolab/ark-analysis#1046]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
Cells that do not have any pixel clusters in them are still being included in the cell clustering. These cells should be removed prior to clustering.

**Expected behavior**
In `cluster_count_size_norm`, check for cells where all pixel cluster counts are 0 and remove those before cell clustering.

**Comment by alex-l-kong** [comment]
Any reason we need to keep these blank cell in the `cluster_count` (un-normalized) table as well?
