### ISSUE TITLE
Mass Plotting needs a few adjustments

### ISSUE THREAD

**Issue by srivarra** [angelolab/ark-analysis#1064]
**Is your feature request related to a problem? Please describe.**

There are a few minor issues in the mass plotting notebook.

1. The mass plotting functionality needs the `dpi` and the `figsize` parameter for `cohort_cluster_plot` and `color_segmentation_by_stat` functions.

2. There is also an issue where the user provided colormap file is mis-coloring the cluster names provided (i.e. the ordering / mapping is incorrect)

3. In addition, the interpolation should be set to `"none"` for `plot_utils.color_segmentation_by_stat`.

4. Incorrect colors are not reported to the user in `plot_utils.cohort_cluster_plot`.

5. Add option to save the plot w or w/o colorbar as a `png` or a `pdf`.

**Describe the solution you'd like**

Add the two parameters, look into the mis-coloring issue for color maps, set the interpolation to `"none"`, and report incorrect colors.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by ngreenwald** [comment]
Another adjustment: when we import into illustrator, having an SVG of the colorbar is helpful for manipulating. Could you add the option to specify the extension (either .png or .pdf) of the cluster plots images?

**Comment by ngreenwald** [comment]
If the supplied colormap has different elements than the cell table, the error message isn't very informative. We should probably add a verify_in_list or equivalent before constructing the colormap:

<img width="1407" alt="image" src="https://github.com/angelolab/ark-analysis/assets/13770365/c4412c14-460a-4da1-a409-80c432dca94d">
