### ISSUE TITLE
New License

### ISSUE THREAD

**Issue by srivarra** [angelolab/ark-analysis#1077]
**Is your feature request related to a problem? Please describe.**

It's a good idea to adjust our license to something more open and less hostile to for-profit organizations. Our current license doesn't allow for this.

**Describe the solution you'd like**

The MIT license is a permissive license, and is a very popular license for open source development.

**MIT**

- Can:
  - Commercial Use
  - Modify (Modify the software and create derivatives)
  - Distribute (distribute original or derivative works)
  - Sublicense (grant / extend a license to the software)
  - Private Use (use / modify software freely without distributing it)
- Cannot:
  - Hold Liable (the developers are not viable for any damages caused by the software)
- Must:
  - Include Copyright
  - Include License (include the license in modified software)

We will need to adjust the badge to reflect the new license.

We will need to state the DeepCell License as well in the README.

**Describe alternatives you've considered**
N/A

**References**

- [The Legal Side of Open Source
](https://opensource.guide/legal/)
- [A Dev's guide to open source software licensing](https://github.com/readme/guides/open-source-licensing)
- [TLDR Legal](https://www.tldrlegal.com/)

**Comment by srivarra** [comment]
@ngreenwald thoughts on MIT?

**Comment by ngreenwald** [comment]
Looks great! I don't think it needs to be in the README, but somewhere in the segmentation notebook itself, I would add the following:

"This notebook uses the Mesmer algorithm, which has a [more restrictive license](https://github.com/vanvalenlab/deepcell-tf/blob/master/LICENSE) than the rest of the codebase"

I think we're good to change this across all the repos in our github.
