### ISSUE TITLE
Incorrect cell cluster mapping in mantis

### ISSUE THREAD

**Issue by camisowers** [angelolab/ark-analysis#1082]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
Currently, the `cell_cluster_mask.csv` that is generated and loaded into mantis does not contain the correct integer IDs for each cell cluster. 

**Expected behavior**
When we updated the way we generate cell_masks to allow for colored masks, the integer IDs for the clusters changed.
If before they were [1,4,10] they are now [1,2,3]. The currently saved `cell_meta_cluster_mapping.csv` does not reflect this change.

**To Reproduce**
Run cell clustering and create new metaclusters.

**Comment by janinemelsen** [comment]
I was wondering whether this is now fixed in the newest release? I downloaded the latest version but am still experiencing the issue of incorrect cluster mapping in Mantis.

**Comment by camisowers** [comment]
Hi @janinemelsen, the fix has just been merged into main! I was not included in the latest release, but if you're running ark from a local environment just pull the repository and update your environment!
