### ISSUE TITLE
Error in `create_mantis_dir` in cell clustering notebook if running `generate_and_save_cell_cluster_masks` multiple times

### ISSUE THREAD

**Issue by cliu72** [angelolab/ark-analysis#1099]
**Describe the bug**
This is a pretty niche problem, but hopefully this fix is straight forward. When I run the "4.4: Generate cell phenotype maps" section of the cell clustering notebook more than once, I get this error: `KeyError: "['cluster_id'] not in index"`. The use case for this is if a user wants to look at ['fov1','fov2'] first and runs the rest of the notebook with `subset_cell_fovs = ['fov1','fov2']`, then decides they want to look at other fovs, so changes `subset_cell_fovs` and tries to run the rest of the notebook again.

I think this error is because in `generate_and_save_cell_cluster_masks`, a `cluster_id` column is added to the mapping csv. However, if this function is run multiple times, because the `cluster_id` column already exists, the columns are not merged properly: 
![image](https://github.com/angelolab/ark-analysis/assets/11382352/e8e7af30-ec23-4026-aba3-13f0ef27f1b6)

**Expected behavior**
Should be allowed to change `subset_cell_fovs` and re-run the rest of the notebook without issue.

**To Reproduce**
Run the example dataset in notebook 3 all the way through. Go back to the start of section 4.4, change `subset_cell_fovs` to something else (ex. ['fov3','fov4']) and run the rest of the notebook. After doing this, I got this error in the last cell:
![image](https://github.com/angelolab/ark-analysis/assets/11382352/c3631ed5-10cf-40f4-9c28-e95b355a0f74)

**Comment by camisowers** [comment]
The `cluster_id` should be the same values for both columns, so I think it would be really easy to just not re-generate the column if it already exists.

**Comment by alex-l-kong** [comment]
@camisowers agreed. I can add a fix for that.
