### ISSUE TITLE
Error downloading example dataset

### ISSUE THREAD

**Issue by cliu72** [angelolab/ark-analysis#1116]
**Describe the bug**
I'm getting this error when I try to run `example_dataset.get_example_dataset`. I tried this line in notebooks 1, 2, and 3 - I get the same error. I tried on both Linux and Windows.

`ValueError: BuilderConfig BuilderConfig(name='segment_image_data', version=0.0.5, data_dir=None, data_files=None, description='This configuration contains data used by notebook 1 - Segment Image Data.') doesn't have a 'trust_remote_code' key.`

**Expected behavior**
Successfully download example dataset in notebooks 1, 2, and 3.

**To Reproduce**
Run notebook 1, 2, or 3 as is (delete any existing example datasets).
![image](https://github.com/angelolab/ark-analysis/assets/11382352/347cb7a4-951a-446c-8d6d-6fe576833b00)

**Comment by srivarra** [comment]
@cliu72 What version of the package `datasets` are you using?

**Comment by cliu72** [comment]
Ah yes, that was the problem, thanks Sri. The version I was using was 2.14.6. In my old environment, I had just run `pip install .` to update ark. I created a completely new environment and ran `pip install .` to build ark from scratch and the datasets version was 2.17.1. So I guess re-installing ark in the same environment doesn't update `datasets`, but it does update when you create a new environment.
