### ISSUE TITLE
ValueError: Lists pixel som weights columns and pixel data columns ordered differently

### ISSUE THREAD

**Issue by janinemelsen** [angelolab/ark-analysis#1120]
After updating to the latest version from github, the ordering of the columns in the pixel som weights file differs from the ordering of the normalised data columns.

error: ' ValueError: Lists pixel som weights columns and pixel data columns ordered differently: values CD324 and Actin do not match at index 0'

Output of print(pixel_pysom.norm_data.columns.values) indeed differs from print(pixel_pysom.columns).

For now I solved it by providing a channel list in which the order is the same as in the normalised data.

**Comment by cliu72** [comment]
Hi @janinemelsen! This should have been fixed in this pull request: https://github.com/angelolab/ark-analysis/pull/1114. Please pull the latest version (and make sure to install the newest version after pulling). Let us know if you still have issues!
