### ISSUE TITLE
generate neighborhood mask results in string error

### ISSUE THREAD

**Issue by janinemelsen** [angelolab/ark-analysis#1129]
Creating the neighborhood cluster mask using the example dataset as described in the  the example_neighborhood_analysis_script led to the following error:

`data_utils.generate_and_save_neighborhood_cluster_masks(
    subset_neighborhood_fovs,
    overlay_out_dir,
    all_data_cluster_labeled,
    segmentation_dir,
    name_suffix='_neighborhood_mask'
)`

<img width="1014" alt="image" src="https://github.com/angelolab/ark-analysis/assets/50010499/eb9ff1ff-60e3-4058-be73-683aa2230b34">

**Comment by camisowers** [comment]
Hi! It's an issue with the argument order. We'll get a PR in to fix this, but for now you can replace the code in the notebook with the below and it should work!

```
data_utils.generate_and_save_neighborhood_cluster_masks(
    fovs=subset_neighborhood_fovs,
    save_dir=overlay_out_dir,
    neighborhood_data=all_data_cluster_labeled,
    seg_dir=segmentation_dir,
    name_suffix='_neighborhood_mask')
```
