### ISSUE TITLE
Appropriate cutoff for random_closenum

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#129]
I'm going to ask Leeat about the rationale for having the comparison for random permutations include >=, rather than strict inequality.

**Comment by ngreenwald** [comment]
Talked to Leeat, she agreed that this should be strictly greater than/less than

**Comment by alex-l-kong** [comment]
Looks like we still have `>=` in `calculate_enrichment_stats` (`p_pos[j, k] = (1 + (np.sum(tmp >= close_num[j, k]))) / bootstrap_num + 1`). Guess I never fixed this in my original `synthetic_datagen` PR, but based on what Leaat said, probably need to change this to `>`.

One question: can't imagine this specific edge case coming up, but if we change `>=` to `>`, do we need to handle `tmp == close_num[j,k]` in `calculate_enrichment_stats`? Or do we just leave those instances out?

**Comment by ngreenwald** [comment]
We can leave those out. We're constructing two one-sided p values here, so
for either p-value the equals case appropriately doesn't get counted
