### ISSUE TITLE
More informative/standardized names in spatial_analysis functions

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#138]
Right now we aren't consistent with how our data structures are named in different versions of spatial analysis. Furthermore, the names themselves are not that informative (e.g. what is fov_data?). Our next step should be to come up with a standardized way of describing different formats of data, and make sure we are consistent throughout our functions with using that naming scheme. 

It should be obvious based on the name of the variable whether it's a pandas array with just the channels, just the phenotype columns, or both, and whether it's across all fovs or just a subset.

**Comment by Jaiveers21** [comment]
channel - all_fov_data -> specific_fov_data and specific_fov_channel_data (just the channel data w all the markers for specific fov)

cluster - all_fov_data -> all_cluster_data (only contains 3 columns: fov, cell label, cell phenotype) -> specific_fov_data (all_cluster_data but for the specific fov)

neighborhood - all_fov_data -> all_fov_neighborhood_data (only contains 4 columns: fov, cell label, cell phenotype ID, cell phenotype) -> specific_fov_data (all_data but for the specific fov)

**Comment by ngreenwald** [comment]
How about this

all_data: matrix with both marker expression data and phenotype labels

all_channel_data: when we subset to just include the channel data

all_phenotype_data: when we subset to just include phenotype data

current_channel_data: when we subset for a certain fov

current_phenotype_data: when we subset to a certain fov. 

Do you think that will make sense for how the functions are written?
