### ISSUE TITLE
Next steps for spatial analysis pipeline

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#139]
Idealized workflow from Erin:

1. produce neighborhood matrix (counts and frequency normalized by total neighborhood size) with recommended distance of 20 um
2. visualize matrix as heatmap which hierarchical clustering and row z-score (to assess general structure and highlight what cell types characterize neighborhood) + visualize neighborhood matrix as UMAP/tSNE
3. Run k-means clustering with k selected based on user input with recommendation of 10 + run either silhouette score or WSS/% variance explained measurement to produce plot with # cluster (x-axis) v metric so user can choose k based on elbow point method 
4. Visualize clusters as a heatmap with cell types (columns) and clusters (rows) along with mean exprs of all markers (columns) and clusters (rows) with column z-scoring (ie. two separate heatmaps, one with mean frequency of cell types in negihborhood and one with mean exprs of all markers) 
5. Produce segmentation images with cell colored by neighborhood cluster 
6. Allow exportation of csv with neighborhood cluster annotated for additional clustering methods and analyses

**Comment by alex-l-kong** [comment]
Just to clarify, this isn't meant to be one all-encompassing issue (as in, not for a single PR), more of like a step-by-step process for future work? I think it's best to split this into several different issues, which I think @ngreenwald has begun already.

**Comment by ngreenwald** [comment]
Right, tackling a portion of this at a time is perfectly fine. Let me know
if any of the specific tasks are not sufficiently clear to get started on.
