### ISSUE TITLE
Add flag to control docker-path checking validate_paths

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#155]
The current implementation of validate_paths means that these functions can't be run outside of the docker image. It would be good to add a flag to validate_paths to turn off the '../data' specific checks, but keep the rest of the functionality, to allow it to be used outside of the docker.

**Comment by ackagel** [comment]
I think the functions themselves can be run outside of the docker, just not the notebooks (I think I removed all the path validation within functions a little while ago and moved them into the notebooks).

**Comment by ackagel** [comment]
nvm I found a few left overs.  I can remove those.  Regardless, I think we can just use `validate_paths` in the notebooks w/ no docker-path flag, since that's `validate_paths` main use case

**Comment by ngreenwald** [comment]
Right, there are a couple places within functions (like data loading) where
instead of checking that the files exist, we switched to using
validate_paths to make sure the files exist. And there were separately a
few functions that just call validate_paths at the top level. Up to you
which option you think makes more sense

**Comment by ngreenwald** [comment]
Looks like these have all been removed now.
