### ISSUE TITLE
Consolidate data loading functions

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#156]
We currently have 4 different functions to load images from various directory structures. There is a fair amount of copied code, it would be good to try and reduce this. 

It looks like load_imgs_from_dir and load_imgs_from_multitiff could be combined together, since the first is just a special case of the second. Lets wait on this until the deepcell upload/download pipeline is a bit more solidified, to make sure we won't be making any other changes.

**Comment by alex-l-kong** [comment]
Is Omer going to be addressing this issue as well with #243?

**Comment by ngreenwald** [comment]
yup!

**Comment by alex-l-kong** [comment]
Great! I think I'll mark this as a duplicate then.

**Comment by ngreenwald** [comment]
Closed via #261
