### ISSUE TITLE
Create additional signal_extraction options

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#157]
Currently, the only signal_extraction option is to sum over all pixels within each cell. To improve upon this, we should start by adding two fairly simple alternative signal extraction functions:

positive_pixels: rather than returning the sum of the image data over pixels, it returns the number of pixels that have non-zero expression of the marker within the cell

center_weighting: Rather than equally weighting each pixel, pixels at the center of the cell are more heavily weighted than pixels at the border. We can aproximate each cell as a circle, then radially multiply pixels by some scaling factor which decreases the further away from the center each pixel gets. To start, lets make this a linear factor.

**Comment by ackagel** [comment]
So, we added/programmed the different extraction functions but it doesn't look like there's actually a way to call/use them.  Reopening this issue and making the functions usable.
