### ISSUE TITLE
Template vs working versions of jupyter notebooks

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#166]
**Is your feature request related to a problem? Please describe.**
The current workflow for using the jupyter notebooks is as follows:
- Start the docker image
- The bash script checks to see if the the template version of the notebook is different from the version in scripts
- If they are different, it copies the new template into the scripts folder

The goal of this was to check and see if the template has been updated in git, and if so, copy it into scripts. However, anytime people modify the version in scripts, it is now different from the version in templates, so even if no change has been made, it still gives the message about an updated version

**Describe the solution you'd like**
Maybe going back to not having people edit the main version, and asking them to make a copy? This way, if they don't follow the instructions, all that will happen is a new template gets copied over, rather than a git issue? I'm not sure.

**Comment by ngreenwald** [comment]
One idea: maybe have an optional flag (like --update-notebooks). If this is supplied to start_docker.sh, it copies the version in templates to the version if scripts. Otherwise, it does nothing.

We can add a line in the documentation about what to do when updating

**Comment by ngreenwald** [comment]
@ackagel I'm leaning towards the following: If there is no scripts directory (aka first time starting) it copies from templates and creates it. Otherwise, it does nothing. If -update_scripts is passed as a flag `bash start_docker.sh -update`, it copies the templates into scripts, and gives a warning if it's overwriting an existing file, without making an 'updated' version of the file. 

We add a section to the documentation spelling this out. How does that sound? Open to other suggestions as well.

**Comment by ackagel** [comment]
Sounds good.  Should be easy enough to implement (time to put my bash hat back on)

**Comment by ackagel** [comment]
I had a fun idea with the update flag.  It might be possible so that when someone calls `bash start_docker.sh --update` (or `-u`), the Dockerfile is copied+cached somewhere, `git pull origin master` is called, and the cached Dockerfile is compared (w/ diff) to the new one.  If there is a difference, the docker can be rebuilt and then started, and if there isn't, start_docker runs as usual (the cached dockerfile is obvs deleted).

This would eliminate the need to tell people to rebuild the docker when there are changes to the dockerfile and also lets us feel more comfortable w/ changing the dockerfile as needed.  Thoughts?

**Comment by ngreenwald** [comment]
I think the first priority is covering the base scenario, with an update
flag that handles the script copying. But if you want to play around with a
more complex update flag logic, go for it! I think now that the code is
mounted, people will only actually need to rebuild the image when we make a
change to the dockerfile that impacts new functionality, which I don't
imagine will be that often. Your call

**Comment by ngreenwald** [comment]
Closed by #181, but @ackagel's syntax is too advanced for github to figure out.
