### ISSUE TITLE
Code cleanup for segmentation

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#185]
Marker_quantification.py:
Is there a better way to distinguish `generate_expression_matrix` and `compute_complete_expression_matrix`? These function names aren't that informative
testing: Many of the test functions here are too long. We should break them up into smaller test functions, named by which aspect of the main function they're testing, so that when errors are raised it's more obvious based on the name of the test that's failing what the problem was. 

Signal_extraction.py:
Testing: import the synthetic_data function with a (much) shorter name to increase code readability. 

I'm not in love with marker_quantification as the module name here. Open to suggestions for a good name to describe the set of functions that take segmentation masks, channel data, and produce the CSV of counts per cell.

**Comment by alex-l-kong** [comment]
For distinguishing `generate_expression_matrix` and `compute_complete_expression_matrix`, what about renaming them to `create_marker_count_matrix` and `generate_segmentation_marker_counts` respectively? The latter is a bit long so we could shorten it to `gen_seg_marker_counts` or something like that.

I personally don't have a huge problem with `marker_quantification` as a name, but what about `marker_count_extraction` as an alternative?

**Comment by ngreenwald** [comment]
Okay, let's leave it as marker_quantification in that case. 

How about generate_cell_data or create_cell_table for the complete_epxression_matrix? We can rename it so that it indicates which data structure it produces, which for now we're going to be calling cell_data or something like that.
