### ISSUE TITLE
Create global settings.py to hold global constants

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#187]
**Is your feature request related to a problem? Please describe.**
With the changing pipeline, the default values for certain common column names is likely changing. These may continue to change in the future. This means we'll have to track down and change these defaults wherever they appear in function calls, test functions, etc

**Describe the solution you'd like**
A settings.py file with global variables that can be imported

**Comment by ngreenwald** [comment]
A nice side effect of this will be having standardized column names to bookend the relevant channel data. Similarly to how this works in [marker extraction](https://github.com/angelolab/ark-analysis/blob/72f3f840d325daf9d3228c4bafc5044d10b33bb7/ark/utils/segmentation_utils.py#L59), this will allow us to exclude or include all marker data without needing an exhaustive list of specific targets on each panel.

**Comment by alex-l-kong** [comment]
This issue was addressed by #232.
