### ISSUE TITLE
Identify syntax errors in sphinx/RTD 

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#197]
**Is your feature request related to a problem? Please describe.**
Currently, the sphinx build on ReadTheDocs will pass as long as there are no errors. However, there might be formatting issues that result in docstrings not getting displayed properly, arguments not being properly highlighted, etc

**Describe the solution you'd like**
Is it possible to add either a github status check or some other way of figuring out if the current build of the docs not only runs without errors, but doesn't introduce any new formatting errors?

**Additional context**
If not, we'll have to either manually review which portions of the docs were changed, or just check in on RTD intermittently to identify new errors.

**Comment by alex-l-kong** [comment]
Seems like if you update the Makefile and/or .readthedocs.yml file, you can force Sphinx and thus ReadTheDocs to treat all warnings as errors: https://github.com/PyAbel/PyAbel/pull/271. I've encountered formatting warnings when running `make html` locally, which will not cause the build to fail unless you specify a flag. So hopefully using this link as a base for addressing this on the next Sphinx PR should solve that issue.
