### ISSUE TITLE
Default heatmap visualization

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#205]
**Is your feature request related to a problem? Please describe.**
The current heatmap visualization function `visualize_z_scores` is not robust and extensible to different datatypes. 

**Describe the solution you'd like**
A generalized heatmap function that is more flexible. It should take in a matrix of data to be visualized, a set of labels for the axes, and a colormap, and produce an annotated heatmap as output.

Additionally, the heatmap should support the following:

- An optional `dpi` parameter for resolution control if the user wants to save the figure
- An optional `center_val` parameter identifying which value to center the colorbar around

**Comment by ngreenwald** [comment]
The seaborn.heatmap function already does most of these things. The main additional feature we want is the ability to cluster the rows and columns with hierarchical clustering, and to display the clustering dendrogram in addition to the heatmap itself

**Comment by alex-l-kong** [comment]
@ngreenwald I think it would be useful to combine #267 and #269 into this issue, any objections?

**Comment by ngreenwald** [comment]
yeah definitely

**Comment by ngreenwald** [comment]
Looks like we may be able to just copy https://seaborn.pydata.org/generated/seaborn.clustermap.html
