### ISSUE TITLE
Include section in documentation on data models/data types

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#210]
It would be useful to have a section in the documentation explaining how we represent the various types of data in the pipeline. For example, an explanation of what a label map is and how that is used to represent segmentations; an explanation of what an xarray is (#209) and how we use that to represent image data; and an explanation of our pandas arrays and how we use that to represent extract information.

**Comment by ngreenwald** [comment]
I added some more examples of what data types we might want in #211

**Comment by alex-l-kong** [comment]
What would be the best way to do this? Tabular format? Full-fledged sections? Or perhaps a hybrid (maybe have a section, perhaps entire page, on `xarray`, and for smaller data types, just use a table if necessary)?

**Comment by ngreenwald** [comment]
Maybe subsections on a single page, but with some structure? For example:

Data Structure: distance_matrix
Used for: Storing distances between pairs of cells
Shape: cells x cells

Description: Longer description here, potentially multiple paragraphs

**Comment by alex-l-kong** [comment]
@ngreenwald I think that's good.
