### ISSUE TITLE
Flowchart for analysis pipeline

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#211]
As we continue to add more pieces to the pipeline, I think it would be useful to have a graphical representation of how data moves through the different scripts. This would be related to a description of individual data types (#210), and we would likely link to it. It would also likely link to the example notebooks. I imagine this going in the main readme section to serve as a starting point for understanding the repo

**Comment by ngreenwald** [comment]
Geneva uses draw.io to make really clean flowcharts. I think this could be a nice way to integrate something like this here. 

Our current workflow is basically the following: 
Data Processing
1.  Organize data into folders of TIFs
2. Identify nuclear channel and membrane channel for deepcell
3. Create 2-channel TIFs to be sent to deepcell
4. Send TIFs to deepcell
5. Get segmentation predictions from deepcell

Segmentation
6. Load all image data in an xarray (what is an xarray? link to explanation)
7. Load all segmentation masks into an xarray (what is a segmentation mask? link to explanation)
8. Extract counts per cell into pandas array (what is this data format? link to explanation)

Analysis
9. Create distance_matrix (what is this? link to explanation)
10. Calculate spatial enrichment (link to docs)

**Comment by alex-l-kong** [comment]
How basic/complex of a flowchart are we talking about? Are we thinking something similar to what we see in the MIBI papers or a bit simpler?

**Comment by ngreenwald** [comment]
Probably a bit simpler, at least for the diagram. Here's something Geneva put together for the data annotation pipeline:
![image](https://user-images.githubusercontent.com/13770365/93655354-afbe7180-f9d7-11ea-8e76-ce2a43ea6505.png)


Draw.io makes it really easy to do stuff like that. The main point that I want the flowchart to communicate is how the data representations change as we go through the pipeline. A visual aid to help people as they're reading about distance_matrices, stacked channel data, FOVs, etc etc.

**Comment by ngreenwald** [comment]
The description is a bit outdated. Once we finalize the readme/notebook structure, can tackle this
