### ISSUE TITLE
Error while installing 

### ISSUE THREAD

**Issue by man154** [angelolab/ark-analysis#223]
I executed this command: 
$ docker build -t ark-analysis .
It ran for sometime and stopped in Step 5/8 : RUN pip install -r /opt/ark-analysis/requirements.txt

ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
...
The command '/bin/sh -c pip install -r /opt/ark-analysis/requirements.txt' returned a non-zero code: 1

FYI I'm running Docker Toolbox (Docker Quickstart Terminal) on Win10.

**Comment by ackagel** [comment]
Hi there!  There may have been a problem while downloading some dependencies.  Could you try running the command again?  If that doesn't work, can you post a screenshot(s) of the error message and/or specify the packages it lists as not having matching hashes?

**Comment by man154** [comment]
It worked after several attempt. However, the link is not working. 
![Capture](https://user-images.githubusercontent.com/55411688/93289186-a7c1c000-f792-11ea-85e3-8a49c367a141.JPG)

**Comment by ackagel** [comment]
when you ran `bash start_docker.sh`, did you keep the window open or close it?  The terminal window should be kept open (not exited out) while using the notebooks.

**Comment by man154** [comment]
The window was open. Also, the "ark-analysis" image was running on Docker as well.

**Comment by ackagel** [comment]
Gotcha.  Ok, after a little more research, it looks like this is an issue with Docker Toolbox.  I'd recommend updating to Docker Desktop for Windows in the future, but there is an immediate workaround that we can try:

 1. Run the command `docker-machine ip default` in the docker terminal.  This should print an ip address that looks something like `xxx.xxx.xxx.xxx`.  Remember this ip address.
 2. When you copy/paste the link from the terminal into the browser, replace the `127.0.0.1` in the url with the ip address output by step 1, `xxx.xxx.xxx.xxx`

**Comment by man154** [comment]
It worked! Thanks a lot.

**Comment by ackagel** [comment]
No problem! Happy to help

**Comment by man154** [comment]
However, there were still some warnings. Any suggestion? 
![error1](https://user-images.githubusercontent.com/55411688/93519323-f7af9c80-f8e2-11ea-80fc-d0b4cd7adee3.JPG)
![error2](https://user-images.githubusercontent.com/55411688/93519341-fb432380-f8e2-11ea-9076-532ca1cd5682.JPG)

**Comment by ngreenwald** [comment]
Yeah these are all fine, it'll still work
