### ISSUE TITLE
FAQ/troubleshooting documentation

### ISSUE THREAD

**Issue by ackagel** [angelolab/ark-analysis#226]
### **Problem description**
There are issues users encounter when downloading, installing, and using this toolkit, which can't be resolved as a bug fix on our end.  These problems can be repeatedly encountered among users or are predictable within certain conditions/environments.

### **Ideal solution**
It would save both users and developers time if we consolidate commonly encountered and/or confusing issues into a FAQ/troubleshooting section within the documentation.  This avoids users having to detail their operating conditions in arbitrarily necessary detail and avoids developers having to divert attention from other tasks in order to iteratively re-diagnose issues they've encountered before.

### **Alternative solution**
It could go directly in the readme I suppose, but this would probably clutter the readme a bit much, especially as we find more common errors.  Regardless, an FAQ/troubleshooting section within the readme containing a link to the FAQ/troubleshooting documentation could be warranted.

### **Additional context**
This isn't a replacement for user/developer interaction!  We should always be happy to help users, regardless of how difficult of an issue they are having.  Not to mention, there will still be cases where users need assistance from developers on problems which lie outside the scope of the FAQ/troubleshooting docs.

Furthermore, a FAQ/troubleshooting section is not an encyclopedia of all encounter-able issues.  Care should be made to reserve it for issues which are either common or predictable within certain systems.

**Comment by alex-l-kong** [comment]
Agreed, I think having a separate FAQ page in our`_rtd` folder (`faq.md`) is a good idea. We can easily add new questions that come up if needed.

**Comment by alex-l-kong** [comment]
Whoops, forgot to link my PR to this, closing.
