### ISSUE TITLE
Question regarding Input to Deepcell

### ISSUE THREAD

**Issue by man154** [angelolab/ark-analysis#231]
How is the input file to Deepcell generated/formatted/sized? Looks like it has a dimension of 1024x2 (I imported the file to Matlab to check the dimension). Shouldn't it be 1048576x2, if the individual channel images were resized?

**Comment by ackagel** [comment]
Currently, the input file to Deepcell is 1024x1024x2, one 1024x1024 nuclear signal image/layer and one 1024x1024 membrane signal image/layer.

However, other standard tif reading/writing software/packages would expect these multilayered tifs to be shaped 2x1024x1024, with number of layers as the first dimension.  Consequently, when single tif reading packages look at these Deepcell input files, only one 1024x2 image is loaded in as if it were the first of 1024 layers.

@ngreenwald correct me if I'm mistaken, but I believe Deepcell will change the input format to the standardized 2x1024x1024 format, at which point or prior to which we'll update this project accordingly.  That process shouldn't be anything to be concerned about; it'll occur under the radar with no appreciable side effects.

Regardless, it sounds like you've gotten the right inputs for Deepcell, so you're all set; they're just not MATLAB compatible tifs.

If you really need to read in the tiff file to MATLAB, as they are right now, you can use the following snippet:
```
%%% function for general multipagetiff reading (I don't think there's another way of doing this 🙄 )
function images = readMultipageTiff(filename)
    % Create Tiff object and read first image
    t = Tiff(filename, 'r');
    images(:,:,1) = t.read();
    if t.lastDirectory()
         return;
    end
    % Read all remaining pages (directories) in the file
    t.nextDirectory();
    while true
        images(:,:,end+1) = t.read();
        if t.lastDirectory()
            break;
        else
            t.nextDirectory();
        end
    end
end

%%% example usage
images = readMultipageTiff(deepcell_input)

% show nuclear channel
imshow(images(1, :, :))

% show membrane channel
imshow(images(2, :, :))
```

Alternatively, if you just want to look at the Deepcell input tifs to verify that everything looks correct, you could do that from the preprocessing notebook by adding a new notebook cell with this code:
```
import matplotlib.pyplot as plt

deepcell_input_xr = data_utils.load_imgs_from_multitiff(deepcell_dir)

# show nuclear channel
plt.imshow(deepcell_input_xr[0, : , :, 0].values)

# show membrane channel
plt.imshow(deepcell_input_xr[0, :, :, 1].values)
```

Again, all of that code is optional.  You're all set to upload to Deepcell.

**Comment by man154** [comment]
Makes sense. Thanks for the Matlab code - the file is supposed to be read like that. I just dragged the file to the workspace which is not the correct way to read this type of tiff files.
