### ISSUE TITLE
Remove all references to Points

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#241]
**Is your feature request related to a problem? Please describe.**
The MIBI terminology for an FOV is a point. However, no one else understands what this means. About halfway through coding the pipeline up I switched to using FOVs instead. However, there are still a fair number of remaining references to Points sprinkled throughout the repo. 

**Describe the solution you'd like**
Control-f for all occurrences of Point anywhere in the repo and change to FOV

**Describe alternatives you've considered**
Anarchy

**Comment by alex-l-kong** [comment]
😂 at the feature request description.
