### ISSUE TITLE
Update deepcell processing pipeline

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#243]
**Is your feature request related to a problem? Please describe.**
Now that we have a way to get segmentations from deepcell without a separate upload step, we can combine the preprocessing and post-processing notebooks together. 

**Describe the solution you'd like**
A single notebook called Segment_Image_Data or something along those lines. It should combine the functionality of the two notebooks together, and add in a call to the new kiosk-client function call. 

Additionally, we should switch the format of the deepcell_input tifs to be channels_first, since deepcell now supports that and it makes it easier to load into image viewers. 

Finally, now that we've settled on the format for the multi-tiff format, we can combine `load_imgs_from_dir` and `load_imgs_from_multitiff` into a single function that handles both a directory of single-channel images and a directory of multi-channel images

**Comment by omerbt** [comment]
Hey Noah, 

> Additionally, we should switch the format of the deepcell_input tifs to be channels_first, since deepcell now supports that and it makes it easier to load into image viewers.

Could you please explain what does the `channels_first` format mean? 

Thanks!

**Comment by ngreenwald** [comment]
Sure thing. When you have images with multiple channels, the shape of your array can either be [channel, row, col] or [row, col, channel]. If channel is first we call this format channels first, and if channel is last we call that format channels last. 

Channels last is more intuitive (I think) when working 4D arrays, where you have [image, row, col, channel]. However, most image viewing software expects [channel, row, col]. Therefore, we'll want to switch [this function](https://github.com/angelolab/ark-analysis/blob/853d0c3870e632c53204b52a941216151ad93316/ark/utils/data_utils.py#L10) to save data with the channels first instead of last. 

The other thing that could use some more explaining:
We currently have one function [load_imgs_from_multitiff](https://github.com/angelolab/ark-analysis/blob/853d0c3870e632c53204b52a941216151ad93316/ark/utils/load_utils.py#L80) that loads multiple images from a directory. It assumes that each image is a multi-tiff image, meaning [rows, cols, channels]. 

We have a second function [load_imgs_from_dir](https://github.com/angelolab/ark-analysis/blob/853d0c3870e632c53204b52a941216151ad93316/ark/utils/load_utils.py#L252) that loads multiple images from a directory. However, it assumes that each image is a single channel 2D image, meaning [rows, cols].

However, the second is just a special case of the first. So what we should do is combine these two functions together into a single function. We should keep the `load_imgs_from_dir` name. 

`load_imgs_from_dir` has more functionality than `load_imgs_from_multitiff`. We should keep all of that functionality except for `variable_sizes`, which isn't needed anymore.
