### ISSUE TITLE
Remove certain functions in test_utils.py from documentation

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#251]
**Describe the solution you'd like**

A lot of our functions in `test_utils.py` do not need to be seen by the user. We can hide these by including an `_` before each such function we want to hide. Alternatively, we could also consider just ignoring `test_utils.py` all together. I can modify `conf.py` to do this if we plan to completely nuke all documentation for `test_utils.py`.

**Additional context**

This issue isn't limited to just `test_utils.py`. If we notice any other function that we wish to hide from our documentation, we should consider similar methods discussed above.

**Comment by ngreenwald** [comment]
I think we can ignore it completely

**Comment by alex-l-kong** [comment]
Got it, now that I think about it, instead of modifying `conf.py`, let's just enforce a rule that each function in `test_utils.py` should have a preceding `_` in their name. Sphinx/RTD ignores those thankfully.
