### ISSUE TITLE
Check for important missed test coverage

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#256]
**Is your feature request related to a problem? Please describe.**
There is undoubtedly a number of lines that are not currently being tested. Some of these are likely not worth spending our time on. However, in order to avoid users discovering bugs by changing things, it would be great to test the ones that are likely to lead to errors. Especially uncovered lines that depend on variable names or variable formats that seem likely to change over time. 

**Describe the solution you'd like**
Take a look through the coveralls output, either online or via the HTML output generated locally, to identify uncovered lines, and add in tests to cover those corner cases. 

**Describe alternatives you've considered**
Bug-report driven coverage increases

**Comment by alex-l-kong** [comment]
After running into several recent bugs with marker verification in `calculate_channel_spatial_enrichment`, I think it would be a good idea to include coverage for each place an exception is raised.
