### ISSUE TITLE
Condense test data generation for spatial_analysis_test and spatial_analysis_utils_test

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#258]
**Describe the solution you'd like**

The process to generate synthetic data for testing purposes in `spatial_analysis_test` and `spatial_analysis_utils_test` should be combined into one function for each separate dataframe/xarray/etc. needed (ex. dist_mats, expression_mats, neighborhood_mats should be in separate functions). We're relying on entirely different test matrices for both functions and it's overcomplicating the testing process. By placing these data-generating functions in `test_utils` and combining shared logic, we should have a much more modular testing process.

**Comment by ngreenwald** [comment]
We can update the tests when we reintroduce the pairwise distance notebook
