### ISSUE TITLE
low contrast image warning

### ISSUE THREAD

**Issue by DMrdjen** [angelolab/ark-analysis#260]
Getting this warning message when loading images into notebook:

/usr/local/lib/python3.6/site-packages/ark/utils/data_utils.py:39: UserWarning: ../data/hippocampus/input_data/deepcell_input/Point102.tif is a low contrast image
  io.imsave(save_path, out, plugin='tifffile')

**Comment by ngreenwald** [comment]
We can add a line to the data_loaders to suppress these warnings
