### ISSUE TITLE
Make error messages for mismatched columns, fovs, and markers for spatial analysis more descriptive

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#264]
**Is your feature request related to a problem? Please describe.**

The exception messages we raise for checking `all_data` column, fov, and marker validity are very vague. For an inexperienced user with a very wide dataframe, it can be confusing to simply be told, for example, that "Fovs were not found in Expression Matrix" without also being told which ones were not found.

**Describe the solution you'd like**

We should print out the exact mismatched values to help guide the user to adjust their csv/dataframe accordingly.

**Additional context**

We hadn't got too many complaints about this so far, but I ran into a lot of problems with this when given a sample dataset from Tyler. There were several column, fov, and marker mismatches and it was hard to pinpoint exactly which ones were missing without print debugging inside `spatial_analysis.py` (which also required restarting the kernel several times in `example_spatial_analysis_script.ipynb`).

While it is true that we're working on enforcing strict standardization guidelines for expression CSV's, I still think this is an issue worth looking into.

**Comment by ngreenwald** [comment]
Agreed, I think #254 will address this
