### ISSUE TITLE
Preprocessing multidimensional tiffs

### ISSUE THREAD

**Issue by maharahim** [angelolab/ark-analysis#270]
Hey, 

I am trying to load multi-channel tiffs for pre-processing. 

When I run the following command: 

if MIBItiff:
    data_xr = load_utils.load_imgs_from_mibitiff(tiff_dir, mibitiff_files=fovs, channels=channels)
else:
    data_xr = load_utils.load_imgs_from_tree(tiff_dir, img_sub_folder="TIFs", fovs=fovs, channels=channels)

I get an indexing error:
IndexError                                Traceback (most recent call last)
<ipython-input-35-0ceedcd7a276> in <module>
      6 
      7 if MIBItiff:
----> 8     data_xr = load_utils.load_imgs_from_mibitiff(tiff_dir, mibitiff_files=fovs, channels=channels)
      9 else:
     10     data_xr = load_utils.load_imgs_from_tree(tiff_dir, img_sub_folder="TIFs", fovs=fovs, channels=channels)

/usr/local/lib/python3.6/site-packages/ark/utils/load_utils.py in load_imgs_from_mibitiff(data_dir, mibitiff_files, channels, delimiter, dtype)
     45                       for mt_file in mibitiff_files]
     46 
---> 47     test_img = io.imread(mibitiff_files[0], plugin='tifffile')
     48 
     49     # check to make sure that float dtype was supplied if image data is float

IndexError: list index out of range

**Comment by alex-l-kong** [comment]
@maharahim can you check the names of your MIBItiff files? The default suffix of the filenames is `-MassCorrected-Filtered.tiff`.

**Comment by maharahim** [comment]
@alex-l-kong Yes, I have the same suffix for my MIBItiff files. I get the same error if I am running the example dataset as well.

**Comment by ngreenwald** [comment]
If you're getting the same error on the example dataset, my suspicion is
that you have a path messed up somewhere. Can you print the `fovs`
variable? It looks like it's empty based on the error message

**Comment by maharahim** [comment]
@ngreenwald Yes, 'fovs' was empty. I had to change the tiff directory - Thanks!

**Comment by ngreenwald** [comment]
For sure, no problem
