### ISSUE TITLE
Which markers are displayed in the overlay tiff?

### ISSUE THREAD

**Issue by maharahim** [angelolab/ark-analysis#272]
In the overlay tiff generated from the postprocessing script, which markers are displayed? I selected three membrane markers and two nuclear markers to be used for segmentation in the pre-processing script. In the overlay tiff, it only looks to be one of the three membrane markers. Does the overlay tiff only display some of the markers used for segmentation, or is it possible that not all markers I selected were used for preprocessing? If the latter, how can I check? Thanks!

**Comment by ngreenwald** [comment]
The preprocessing scripts adds them all together into a single nuclear and
single membrane channel, so what you're seeing in the overlay is the summed
channel being overlaid with the image data

**Comment by alex-l-kong** [comment]
Looks like this one has been resolved, closing.
