### ISSUE TITLE
Running bash start_docker.sh will automatically try to use port 8888

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#276]
**Describe the bug**

When a user tries to run `bash start_docker.sh`, the Jupyter server is automatically assigned port 8888. This is not usually a problem, but if the user already has a Jupyter server open that is using port 8888, you will not be able to open the notebook (technically, you will be taken to a page where you need to validate your token, but that will always fail because you need the token for the existing server using port 8888, and then you will be taken to that server and not the Deepcell notebooks).

This can be a problem if, say, a user has multiple important Jupyter servers open and one of them is using the default port 8888. It would be very inconvenient to tell the user that they have to kill all of the work they've been doing on the server using port 8888 before they can properly start the Docker.

**To Reproduce**

Open a Jupyter server using the default port 8888, then try running `bash start_docker.sh`.

**Expected behavior**

The proper functionality would be to test if port 8888 is being used first, and if so, then assign it to the next available port (so if 8889 is also taken, then 8890, and so forth).

**Comment by ngreenwald** [comment]
I assumed 8888 was the only usable port! Great idea
