### ISSUE TITLE
create_deepcell_output in Segment Image Data notebook generates error on multichannel .tiffs

### ISSUE THREAD

**Issue by awedwards** [angelolab/ark-analysis#278]
The "create_deepcell_output" command in the Segment Image Data notebook produces an error. I have multiple MIBI multi channel .tif files in my deepcell_input folder, but once I get to the upload step, it seems to be looking for files ending in ".tiff.tif" files instead.

**To Reproduce**
1. In the Segment_Image_data.ipynb file, set MIBItiff = True and point the tiffdir variable to a folder with multichannel .tiffs 
2. Run the notebook through all of the preprocessing steps (this will create .tif files in the deepcell_input folder, as expected)
3. Run the line with "create_deepcell_output"

**Expected behavior**

The program should find the .tif files in the deepcell_input folder, zip and upload them.

**Error trace**

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-2b23a959c361> in <module>
----> 1 deepcell_service_utils.create_deepcell_output(deepcell_input_dir, deepcell_output_dir, fovs=fovs)

/usr/local/lib/python3.6/site-packages/ark/utils/deepcell_service_utils.py in create_deepcell_output(deepcell_input_dir, deepcell_output_dir, fovs, suffix, host, job_type)
     52             if not os.path.isfile(filename):
     53                 raise ValueError('Could not find .tif file for %s. '
---> 54                                  'Invalid value for %s' % (fov, filename))
     55             zipObj.write(filename, os.path.basename(filename))
     56 

ValueError: Could not find .tif file for fov6_LichenoidDysplasia-MassCorrected-Filtered.tiff. Invalid value for ../data/HNDysplasia/input_data/deepcell_input/fov6_LichenoidDysplasia-MassCorrected-Filtered.tiff.tif
```

**Comment by ngreenwald** [comment]
Looks like an issue with .tif vs .tiff. 
We just updated this notebook yesterday, I think you're the first to try it out. Can you check if you get the same error if you swap the endings?

**Comment by awedwards** [comment]
if I change the files from .tiff to .tif I get a similar error:

```
ValueError: Could not find .tif file for fov2_SevereDysplasia-MassCorrected-Filtered.tif. Invalid value for ../data/HNDysplasia/input_data/deepcell_input/fov2_SevereDysplasia-MassCorrected-Filtered.tif.tif
```

**Comment by alex-l-kong** [comment]
@ngreenwald @awedwards just got around to looking at this, looks like there's a bug in generating the `fovs` list when `MIBItiff` is set to `True`:

```
if MIBItiff:
    fovs = io_utils.list_files(tiff_dir, substrs=MIBItiff_suffix)
```

This will keep the `.tif` or `.tiff` file extensions at the end of `fov`, but that will cause `create_deepcell_output` to append an extra `.tif` at the end, which is why you were getting `.tiff.tif` or `.tif.tif` file names.

We'll work on a patch for that tomorrow. @awedwards the quick and dirty fix for that is to add a line to remove `.tiff` from each of the `fovs` in the code above:

```
if MIBItiff:
    fovs = io_utils.list_files(tiff_dir, substrs=MIBItiff_suffix)
    fovs = [fov.replace('.tiff', '') for fov in fovs]
```

**Comment by ngreenwald** [comment]
Certain functions expect just the identifier, and other functions expect the identifier plus the extension. 

The following line:
```
    data_xr = load_utils.load_imgs_from_mibitiff(tiff_dir, mibitiff_files=fovs, channels=channels)
```

expects the extension. It's only the final function 
```
deepcell_service_utils.create_deepcell_output(deepcell_input_dir, deepcell_output_dir, fovs=fovs)
```
that expects there not to be an extension. Alex's workaround should be fine. I would suggest naming it something else and only changing the passed variable for the last function call. 

We'll want to think about a better way to standardize when extensions are expected and when they are not.

**Comment by awedwards** [comment]
Word. Yeah I was just changing my files to .tiff.tifs and that worked too. But figured you would want to fix it. Thanks!
