### ISSUE TITLE
Generating fov names with MIBItiff keeps .tiff extension in Segment_Image_Data

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#279]
**Describe the bug**

When `MIBItiff` is set to`True` in `Segment_Image_Data.ipynb`, the `fov` names that are generated from `list_files` does not properly remove the `.tiff` extension afterward. This is a problem because `generate_deepcell_output` assumes that the `fovs` provided are just the names of the `fovs` and not corresponding file names.

**To Reproduce**

Run `Segment_Image_Data.ipynb` with example data such that `MIBItiff = True`.

**Expected behavior**

We should either be removing the `.tiff` extension in `Segment_Image_Data` or in `generate_deepcell_output`, whichever one works better for us.

**Comment by ngreenwald** [comment]
I think more broadly we should come up with a plan for when we keep track of the extension and when we don't, to avoid this problem. 

Also, we should use Adam's function instead:

```
    fovs_no_suffix = io_utils.extract_delimited_names(fovs, '.tif')
```
