### ISSUE TITLE
Save combined nuclear and membrane channels for visualization

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#285]
**Is your feature request related to a problem? Please describe.**
As described in #284, our current visualization fails when multiple markers have been summed together to create the input for deepcell. This is because the `data_xr`, which is used to load the markers in cell 5, doesn't contain the summed channels. Instead, this summation happens within the `generate_deepcell_input` function, and the summed markers are saved directly to disk as .tiff files

**Describe the solution you'd like**
We should store the summed versions of these markers for easy visualization. There are two ways to accomplish this. 
- The first would be to separately load the tiffs which are created by `generate_deepcell_input` into a different data_structure, and use that for visualization. For example, `load_utils.load_imgs_from_dir` should work directly on those .tiff files. 
- The second would be to break `generate_deepcell_input` into two functions. One function would create (and return) the summed xarray. The next function would take that xarray and save it to disk as individual tiffs.

**Comment by alex-l-kong** [comment]
I think it's probably easier to go with the first option. It seems a little overkill to have to split up the functionality of `generate_deepcell_input` into separate compute and save functions considering that the save function would probably be just 2 lines.
