### ISSUE TITLE
Add neighborhood hierarchical clustering, UMAP, and tSNE visualizations

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#293]
**Describe the solution you'd like**

When a user conducts neighborhood analyses using `example_neighborhood_analysis_script.ipynb`, it would be useful to provide a visualization to show a general overview of what the neighborhood clustering produced. To do this, a visualization of a hierarchical clustering of the neighborhood matrix would be helpful, as well as a corresponding UMAP and tSNE visualization as well. This addresses the first TODO in the notebook.

**Comment by ngreenwald** [comment]
This is now resolved
