### ISSUE TITLE
Overlay segmented images with neighborhood clusters

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#295]
**Describe the solution you'd like**

The final visualization in `example_neighborhood_analysis_script.ipynb` (corresponding to the last TODO) should provide the user an image showing which cells were assigned to which neighborhood cluster generated. Before writing the generated DataFrame to .csv, this will serve as the check that everything went according to plan.

**Comment by ngreenwald** [comment]
You might be able to use [this function](https://github.com/angelolab/ark-analysis/blob/19721f3cd9e500b82edb60de4ef83daffeb904ff/ark/utils/plot_utils.py#L143) and [this one](https://github.com/angelolab/ark-analysis/blob/19721f3cd9e500b82edb60de4ef83daffeb904ff/ark/utils/plot_utils.py#L173) as inspiration. I wrote them a while ago, they're not very optimized. Either way, once this PR is ready to go, you can delete them from the repo.

**Comment by omerbt** [comment]
Perhaps I didn't understand the way the data is saved, but `all_data_cluster_labeled` doesn't contain an entry (for example) with 'SampleID' that is 'fov6' and 'cellLabelInImage' == 1107, even though there are more than 1107 cells (according to `label_maps`)

**Comment by ngreenwald** [comment]
`all_data_cluster_labeled` should be identical to `all_data`, the only exception being there is an extra column with the cluster labels. `all_data` is read directly from the example_data directory. It's definitely possible you found a bug. 

However, there are missing labels as a result of post-processing. So just because there are 1107 unique cells in the segmetnation_label, doesn't necessarily mean that cell 1107 **definitely** exists. Did you check that there is a cell with ID 1107 in the segmentation_label?

**Comment by omerbt** [comment]
For example: cells 1107, 1868, 102, 914 (and a few more) exist (in `label_maps`) but not in `all_data_cluster_labeled`

**Comment by ngreenwald** [comment]
Do they exist in `all_data`, or they're missing from both?

**Comment by omerbt** [comment]
They exist there

**Comment by ngreenwald** [comment]
@alex-l-kong can you confirm that specific cell_ids are being dropped in the clustering script, and if so help Omer figure out why?

**Comment by alex-l-kong** [comment]
@ngreenwald yeah I'll work with him on that.

**Comment by alex-l-kong** [comment]
@ngreenwald @omerbt so when I ran the `example_neighborhood_analysis_script`, I confirmed that the values in `all_data` match up with the values in `all_data_cluster_labeled` (after dropping the `cluster_labels` col). So I'm not sure how they are ending up different.

@omerbt it is true that cell label 1107 for fov6 doesn't appear in `all_data_cluster_labeled`, but that should be because it also doesn't appear in `all_data` (verified). For fov6, cell labels 1868, 102, and 914 should exist in both. Are you using our `example_expression_matrix.csv`?

**Comment by omerbt** [comment]
@alex-l-kong I'm using the example csv file. I thought to get the labeled image from `label_maps`, and then change the labels according to `all_data_cluster_labeled`. Cell label 1107 (for fov6) appears in `label_maps`, so I'm not sure what I'm missing here.

**Comment by alex-l-kong** [comment]
@omerbt I don't think you should be changing any of the labels in either `label_maps` or `all_data`/`all_data_cluster_labeled`. One thing to check: are you getting the same number of rows in `all_data_cluster_labeled` as you are getting in `all_data` @ngreenwald please feel free to comment on this.

On a related note, there's actually a major bug in the way we're generating the cluster score visualizations right now: we're not dropping the label column prior to doing that (the desired `k` should actually be 8, not 6, in the resulting visualization). I'll need to open an issue and address that by tomorrow. For the time being, @omerbt, just move the line where you drop the label column to before the call to `compute_cluster_metrics`.

**Comment by ngreenwald** [comment]
Okay I think I understand the confusion. There are some cells in `segmentation_labels.xr` which are **not** in either `all_data` or `all_data_cluster_labeled`. This is fine; this means that during the clustering process, those cells were removed for some reason. 

What we want to make sure is that there aren't any differences in the cells between `all_data` and `all_data_cluster_labeled`. Those should have exactly the same cells. 

What we can do is have an `other` category for coloring the labels. Any label that is given an explicit category can be grouped into this other category, and displayed as grey.
