### ISSUE TITLE
Ark Module Not Found

### ISSUE THREAD

**Issue by suyangliu** [angelolab/ark-analysis#299]
**What are you trying to do?**
I am trying to run the Segment_Image_Data .py script

**What is the problem?**  
The ark Module cannot be  found

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-3e1027588ae4> in <module>
      4 import matplotlib.pyplot as plt
      5 
----> 6 from ark.utils import data_utils, load_utils, io_utils, plot_utils, deepcell_service_utils
      7 from ark.segmentation import marker_quantification

ModuleNotFoundError: No module named 'ark'

**What have you tried so far?**
I made sure I copy the link  that  was  generated  from the  start_docker.sh
I've updated  docker and then tried to restart docker and run start_docker.sh

**Additional context**
Add any other context or screenshots here.
<img width="1176" alt="Screen Shot 2020-10-26 at 11 30 02 PM" src="https://user-images.githubusercontent.com/73518067/97265845-908bde80-17e4-11eb-9ccb-d09927b024d8.png">

**Comment by alex-l-kong** [comment]
Are you running this in Docker? If you're not, make sure to run `bash start_docker.sh` in your Terminal, copy the second URL that pops up into your web browser, and select `Segment_Image_Data.ipynb`.

More details can be found in the `README.md` of our repository.

**Comment by HoxB8** [comment]
Thanks.   I had the docker and Jupyter notebook opened before running the start_docker.sh  and copying the link; perhaps that's why it didn't run in the docker.  When I closed jupyter notebook, ran the script, and opened jupyter notebook by copying  the link, it worked.

**Comment by ngreenwald** [comment]
Great, glad to hear it!
