### ISSUE TITLE
append phenotyping information to single cell output

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#30]
given a csv file with patient IDs and the corresponding point names, we should add functionality so that this information can get appended onto each cell corresponding to that patient

**Comment by alex-l-kong** [comment]
Does `concatenate_csv` in `segmentation_utils` address this issue, or is that a completely unrelated function?

**Comment by ngreenwald** [comment]
This is slightly different. This would also be a good highschool project. 

The goal of this function would be the following. Say you have 10 patients. Each patient has an age, weight, and ethnicity. You want to append that information onto each cell in the final CSV that gets generated. For example, all cells from patient 1 will have the ethnicity of patient 1 in a corresponding column, ethnicity. This would be applied across the entire dataset. 

This function would be called add_covariates or something like that, and would provide an easy way to subset the cells in the dataset based on clinical or biological covariates that are shared across patients.
