### ISSUE TITLE
Better testing of notebooks

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#307]
**Is your feature request related to a problem? Please describe.**
We've had a number of issues pop up with the jupyter notebooks. These basically boil down to the fact that the jupyter notebook is run as-is by Travis. That means that only the specific default parameters for each variable are being tested, and not the different ways that these can potentially be modified. This leads to holes in our test coverage, and hence bugs that are only discovered when users modify these parameters. 

**Describe the solution you'd like**
We want to avoid this happening, by ensuring that the code in the notebooks is being more thoroughly tested. There are two options for this. 

1) Abstract more of the code currently in these cells into a function, and the test the function itself
2) Use a more intelligent testing framework than just running the notebook from start to finish. 

I think we've done a fairly good at number 1, and going further down this route is going to lead to extraneous functions. 

The question then is what are the options for option 2. I did some googling, and found this pretty informative discussion [thread](https://discourse.jupyter.org/t/testing-notebooks/701/18). I think it would be great if you guys could take a look through. What popped out to me as potentially the most promising is [this tool](https://test-book.readthedocs.io/en/latest/), which allows you to interact with and write tests for individual cells, variables, and functions within a notebook. 

We could use this to basically parameterize the cells of the notebook, generating fake input data of different shapes, modifying boolean flags, etc etc. 

@vacuousplanet @alex-l-kong, let me know what you think. Any other suggestions also welcome.

**Comment by alex-l-kong** [comment]
`testbook` looks super good and fairly easy to use, plus it has great `pytest` integration as well. I'll try that one out first, then will consider importing the notebooks directly into `pytest`.

**Comment by alex-l-kong** [comment]
A couple questions:
* How many test cases do we plan on handling? If we plan on handling many, this could be a problem because of `generate_deepcell_input`. Is it possible to increase the timeout limit on Travis?
* How thorough do we want our test cases to be (ex. simply running the notebook with different parameters and telling the user if it passed/failed or scrutinizing the values of each generated output along the way)?

**Comment by ngreenwald** [comment]
`generate_deepcell_input` seems like it would be extremely fast, what's the issue there?

I think we just want to make sure it runs correctly for the different possible values, not check correctness of the output. 

However, I think we can be smart about which cells need to be run. For example, since we don't care what the actual labels look like, we likely don't need to actually rerun the call to deepcell. We can use whatever labels were generated the first time, and only check that different combinations of channels for nuclear and membrane, across MIBI-tiff and tree structure, leads to expected results. for all of the other steps

**Comment by alex-l-kong** [comment]
@ngreenwald I meant `create_deepcell_output`, my bad.

**Comment by ngreenwald** [comment]
I think we should have 1 call to the entire notebook, as is, that runs the whole thing. 

All of the others should only run specific cells, and we can skip `create_deepcell_output` for all of the calls other than the first, entire notebook one
