### ISSUE TITLE
Data type error when trying to generate single cell expression table on int32 images

### ISSUE THREAD

**Issue by awedwards** [angelolab/ark-analysis#309]
**Describe the bug**
I get a data type error when trying to generate single channel expression data table on int32 image data. There doesn't seem to be a way to provide "generate_cell_table" method with an argument that would allow for int32 data to be read.

**To Reproduce**
1. Run Segment_Image_data notebook on 32-bit image data through deepcell. This requires adding a dtype='int32' argument to every instance of "load_utils.load_imgs_from_dir", which is fine
2. Try to run "marker_quantification.generate_cell_table" on segmented data, see error

**Expected behavior**
I expect to be able to generate the cell expression table on int32 data either automatically or by feeding it the data type, as I can with load_imgs_from_dir function

**Screenshots**
```
ValueError                                Traceback (most recent call last)
<ipython-input-14-22459c1b4f7e> in <module>
      8                                              is_mibitiff=MIBItiff,
      9                                              fovs=fovs,
---> 10                                              batch_size=5)

/usr/local/lib/python3.6/site-packages/ark/segmentation/marker_quantification.py in generate_cell_table(segmentation_labels, tiff_dir, img_sub_folder, is_mibitiff, fovs, batch_size)
    293             image_data = load_utils.load_imgs_from_tree(data_dir=tiff_dir,
    294                                                         img_sub_folder=img_sub_folder,
--> 295                                                         fovs=batch_names)
    296 
    297         # as well as the labels corresponding to each of them

/usr/local/lib/python3.6/site-packages/ark/utils/load_utils.py in load_imgs_from_tree(data_dir, img_sub_folder, fovs, channels, dtype, variable_sizes)
    174     # check to make sure that dtype wasn't too small for range of data
    175     if np.min(img_data) < 0:
--> 176         raise ValueError("Integer overflow from loading TIF image, try a larger dtype")
    177 
    178     if variable_sizes:

ValueError: Integer overflow from loading TIF image, try a larger dtype
```

**Comment by ngreenwald** [comment]
Looks like we need to add a dtype argument to `generate_cell_table` function and pass it to the internal call to `load_imgs_from_tree`. I just added you as a collaborator, you can open a PR to address it, or just copy the function into a cell and modify it.

**Comment by awedwards** [comment]
Sure, I'll submit a request and fix it. Thanks

**Comment by awedwards** [comment]
Sorry @ngreenwald , n00b question. I created a new local branch, made changes and committed and tried to run ```git push origin <branch-name>``` and got the following message:

```Permission to angelolab/ark-analysis.git denied to awedwards```

I'm sure I did it wrong...
