### ISSUE TITLE
Neighborhood analysis cluster visualization process doesn't drop label column before clustering

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#316]
**Describe the bug**

We're not dropping the label column prior to generating our silhouette scores for clustering in `example_neighborhood_analysis_script.ipynb`. This made our visualization look a little too good because the label column was a major partitioning factor in deciding which clusters each cell belonged to.

**To Reproduce**

Just run the notebook as is.

**Expected behavior**

The simple fix is to drop the label column beforehand. However, we don't want the user to lose any labeling information from `all_data` either. So my opinion is that we simply pass in `all_data.drop(columns=settings.CELL_LABEL)` as an argument rather than reassigning `all_data`. We could consider making another variable `all_data_sans_label` (or something like that), but I think that's kind of overkill, especially since we already have another `all_data_cluster_labeled` that's just `all_data` with the cluster labels.

**Screenshots**

The actual visualization should look like:

<img width="403" alt="Screen Shot 2020-11-02 at 3 26 50 PM" src="https://user-images.githubusercontent.com/31424707/97930270-d59d9c80-1d1f-11eb-8f00-14238c5a6367.png">

To me, this indicates that the ideal `k` should be 8, but @ngreenwald please check me on this: I'm not 100% sure that's where the elbow is located.

**Comment by ngreenwald** [comment]
I agree, passing in a dropped version of the DataFrame makes the most sense to me. Given how few cells are in the exmple data we're working with, I don't expect great clustering results. I wouldn't worry about picking the right value based on this data.
