### ISSUE TITLE
Define a proper warnings handling system

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#321]
**Is your feature request related to a problem? Please describe.**

Currently, the way we're throwing and handling warnings is a bit confusing. Some functions throw a `warnings.warn` but don't actually display the message that is passed in if a warning is raised.

**Describe the solution you'd like**

There are two ways I think we can handle this:

1. Change all the `warnings.warn` calls into `print` statements. This is a crude but simple solution and makes things less confusing.
2. Write specific `warnings` handlers. Normally, I would be for this one, but a lot of the calls to functions that throw warnings happen inside the notebook, and I don't think it's a good idea to confuse our users by handling the warnings there.

**Comment by ngreenwald** [comment]
I thought the purpose of warning.warn was that it raised a warning with the specified message printed out. Is that not what currently happens?

**Comment by alex-l-kong** [comment]
Double checked, looks like it does. Closing this issue.
