### ISSUE TITLE
Changing the rescaling value for deepcell input

### ISSUE THREAD

**Issue by awedwards** [angelolab/ark-analysis#322]
**What are you trying to do?**
I would like to change the rescaling value for the deepcell input programaticallyu

**What is the problem?**
I vaguely remember being able to change the rescaling value in the pre-processing notebook, but I can't seem to find how to do that.

**What have you tried so far?**
Looked through the code and went back to look at the pre-processing notebook.

**Comment by ngreenwald** [comment]
We currently don't have a programatic way to change the scale. The deepcell.org website has that enabled, not the repo. 

However, it would be pretty straightforward to make a PR adding this in. The scale parameter is already an argument which gets passed to the server [here](https://github.com/vanvalenlab/kiosk-client/blob/663595fd5b33299e6a6b0c20330dbafc7b39970c/kiosk_client/__main__.py#L105). What you'd need to do is add that flag to [deepcell_function](https://github.com/angelolab/ark-analysis/blob/ab22c2686fa9a5dbb1e0ab7ff26ff89ce7302d7b/ark/utils/deepcell_service_utils.py#L12), as well as the associated helper function.

**Comment by awedwards** [comment]
Cool, I can likely add that soon. Thanks

**Comment by awedwards** [comment]
Quick question @ngreenwald it looks like the Travis build is failing because of the test suite. Do I need to make changes to ```deepcell_service_utils_test.py``` as well?

**Comment by ngreenwald** [comment]
Yeah, if you click on the red X, you can see exactly which tests are failing. The test function should be updated to include the new argument.
