### ISSUE TITLE
Create basic SOM implementation

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#325]
**Is your feature request related to a problem? Please describe.**
Addresses part 1 of #287. We currently don't have a way to run SOMs in the repo. 

**Describe the solution you'd like**
As a first step to setting up an executable script for Candace to run, we should first create a default template for the repo. The functionality should be the following:

1. Load all images in a given directory into a numpy array
2. Use images to train a SOM, copying the same hyper-parameters that FlowSOM currently uses. 
3. Run SOM on all pixels in the image. 
4. Produce output file in a convenient form to allow comparison with existing FlowSOM clusters

**Comment by alex-l-kong** [comment]
@ngreenwald from the FlowSOM paper, there are 4 main distinct steps to the FlowSOM algorithm: reading/preprocessing, building/training the SOM, creating an MST, and the actual clustering step. To clarify, this PR is only to address step 2 (assuming the data has already been preprocessed)?

**Comment by ngreenwald** [comment]
You should check with Candace to see if she does any preprocessing in FlowSOM. I think the only preprocessing she does is remove 0 pixels and normalize by columns. If she relies on other FlowSOM stuff, then we should add that here as well. 

We're never going to do steps 3 and 4 of the FlowSOM paper, since those aren't relevant for pixel clustering.
