### ISSUE TITLE
Update virtualenv.md to handle issues with Anaconda installation

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#330]
**Is your feature request related to a problem? Please describe.**

I came across these when helping Inna set up her virtual environment on Mac OS X Catalina about a week ago. There are two specific issues that need to be addressed:

* The graphical installer on recent Mac versions has been broken for some time now. You need to use the command line installer to install the `anaconda3` folder in the right location.
* It looks like the installation of `anaconda3` no longer automatically adds the path to the global `PATH` environment variable. This now needs to be manually done.

I don't have experience with installing Anaconda Windows. If someone can replicate any of these issues, feel free to comment.

**Describe the solution you'd like**

We should update `virtualenv.md` to address this.

**Comment by ngreenwald** [comment]
Is there a reason she's not using the Docker?

**Comment by alex-l-kong** [comment]
She is, but she also wanted to set up `conda` as well for some reason. I guess that unintentionally helped expose the issues mentioned here.
