### ISSUE TITLE
list_files in io_utils needs better substr matching

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#332]
**Describe the bug**

It's finally time to tackle this bug! We have mentioned this in passing before, but it never caused a real issue until Candace's data came in.

The problem with the current matching scheme is that we simply test `if any([substr in file for substr in substrs])`. However, this can match more files than intended, which in ceratin cases, will break our code.

**To Reproduce**

The golden example is if the user includes `'C'` in the desired subset of channels, which is exactly what Candace is doing as a preprocessing step for her FlowSOM pipeline. `list_files` will pull _anything_ with a `C` in it, which includes every `CD` marker. If the user explicitly wanted to drop some `CD` markers, that could at best be an annoyance to clean out the residue.

At worst, it could completely break `load_imgs_from_tree` because in a certain case (if `channels` contains elements without file extensions), it will rightfully expect the list of channels provided to be equal to the desired file listing returned by `list_files`.

**Expected behavior**

In this example, `'C'` should only match `C.tiff` and nothing else. It's probably best to use a method like `os.path.splitext` for this.

**Comment by ngreenwald** [comment]
Maybe we should add a `partial_match` flag that controls whether this happens, or if only exact matches will be returned? This behavior is useful in certain situations, but other times is not.

**Comment by alex-l-kong** [comment]
@ngreenwald that's a good idea, but it's complicated by the fact we don't directly call `list_files` many times in our repo (including our notebooks). We sort of trust that it will work behind the scenes. A `partial_match` flag would require a lot of parameter passing to tell `list_files` what to do in that case.

**Comment by ngreenwald** [comment]
We really just want partial matches for .tif, right? So that it matches .tiff? So we could have the default be false, and set it to true only when it matters within each function?

**Comment by alex-l-kong** [comment]
@ngreenwald just realized that myself. It's a pretty black-and-white process. If the user is using it to match file names, they probably want exact matches, whereas if the user is using it to match file extensions, we're always safe with the generic matching method.

**Comment by ngreenwald** [comment]
Although I think we also might use this to get around the issue of extensions: the non-exact matching means that passing CD45 as the channel will match CD45.tiff. Might require some additional tweaks

**Comment by alex-l-kong** [comment]
Ok, let's see what happens with just a control flag, and if testing reveals more problems, then we'll definitely tweak the function further.
