### ISSUE TITLE
Input file for Spatial Analysis

### ISSUE THREAD

**Issue by HoxB8** [angelolab/ark-analysis#334]
**What are you trying to do?**
I'd like to try the spatial analysis script on the segmented deep cell output data.  

**What is the problem?**
How do I get the expression_matrix.csv file?

**Comment by alex-l-kong** [comment]
@HoxB8 you'll need to run `Segment_Image_Data` first to generate the expression matrices which are written to the path assigned to `single_cell_dir`.

**Comment by HoxB8** [comment]
I ran the Segment_Image_data script and now I see the cell_table_arcsinh_transformed.csv and the cell_table_size_normalized.csv in the single_cell_output folder.  I  don't see an expression matrice file and the example expression matrix in the example dataset looks different from these files.   Thanks for your help.

**Comment by alex-l-kong** [comment]
@HoxB8 both `cell_table_arcsinh_transformed.csv` and `cell_table_size_normalized.csv` are the expression matrices. What looks different between your's and the example one? If the columns are different, it might because you have a different selection of markers than the one used to generate the example one.

**Comment by awedwards** [comment]
hey @HoxB8 are you maybe referring to the columns like ```cell_type``` ? Those are qualitative labels that we don't yet have for our data. I think we'd get them by doing some gating in something like CytoMap to define the cell types by intensity -- they don't come from the deepcell output.

**Comment by HoxB8** [comment]
Thanks for the comments.  Yeah, I noticed  that there  were different parameters  in the columns like Cell_type, FlowSOM_ID, fovs.  But what you said makes sense that they were derived after some other processing.  Thanks.
