### ISSUE TITLE
Error plotting overlay on uint16 data with scale = 0.5

### ISSUE THREAD

**Issue by awedwards** [angelolab/ark-analysis#335]
**Describe the bug**
I get an IndexError when I try to plot the prediction overlay after predicting with certain ```scale``` values. I was successful in plotting this data with scale=1.0 and scale=2.0, but not scale=0.5. Also, this data type is 'uint16' if that might make a difference?

**To Reproduce**
1. Run the Segment_Image_Data notebook, adding dtype='uint16' to all load utility functions
2. Set scale=0.5 in the ```create_deepcell_output``` function
3. Try to plot the overlay with the output

**Expected behavior**
I expect to get an overlay, like I do with scale = 1.0 and scale = 2.0.

**Error trace**
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-9-8eb17ec3d080> in <module>
      2     plot_utils.plot_overlay(segmentation_labels.loc[fov, :, :, "whole_cell"].values,
      3                             data_xr_summed.loc[fov, :, :, :].values,
----> 4                             path=os.path.join(deepcell_output_dir, f'{fov.values}_overlay.tif'))

/usr/local/lib/python3.6/site-packages/ark/utils/plot_utils.py in plot_overlay(predicted_contour, plotting_tif, alternate_contour, path)
     88 
     89         # overlay first contour on all three RGB, to have it show up as white border
---> 90         rescaled[predicted_contour_mask > 0, :] = 255
     91 
     92         # overlay second contour as red outline if present

IndexError: boolean index did not match indexed array along dimension 0; dimension is 1023 but corresponding boolean dimension is 1024
```

**Comment by ngreenwald** [comment]
It looks it's getting rescaled to be of size 1023x1023 instead of 1024x1024. Can you confirm that's the case for those images?

**Comment by awedwards** [comment]
Ah yeah, the combined channel fov images in the deepcell_input folder are 1023x1023.

**Comment by ngreenwald** [comment]
Okay, as a workaround for now you can load them into a 1024x1024 image
`new_img = np.zeros(1024, 1024)`
`new_img[:1023, :1023] = old_img`

We'll need to update which rescale function is being used in the kiosk

**Comment by ngreenwald** [comment]
https://github.com/vanvalenlab/kiosk-redis-consumer/issues/145
