### ISSUE TITLE
Defining Cell Types and Lineage from the Expression Matrices

### ISSUE THREAD

**Issue by HoxB8** [angelolab/ark-analysis#339]
I'd like to try some of the visualization tools that you are developing, such as generating a UMAP plot.  In the example dataset, the input data file "select_cell_data.csv" has parameters 'cell_type' and 'cell_lin'.  Were these parameters determined by running the expression matrices in another script or by manually gating in another program? 

Thank you!

**Comment by ngreenwald** [comment]
Yes, you'll need to perform cell type analysis in a separate program. You could either do manual gating, or use an automated approach like hierarchical clustering or FlowSOM.

We're working on integrating this process into the pipeline, but it'll be another few months before that's ready to try.

**Comment by HoxB8** [comment]
Got it.  Thanks!
