### ISSUE TITLE
Add leading underscores to functions the user doesn't need to see in the documentation

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#343]
**Is your feature request related to a problem? Please describe.**

Our documentation currently contains a lot of helper functions that the user doesn't need to see. For example, the helper functions in `spatial_analysis_utils`: the user doesn't need to see documentation for functions such as `get_pos_cell_labels_channel` because they will never call it directly.

**Describe the solution you'd like**

Only functions that explicitly appear in the notebooks need to appear on ReadTheDocs. Any other function should have a leading underscore; the docstring parser will explicitly ignore those functions when building documentation.

**Comment by ngreenwald** [comment]
I think some pruning could be worthwhile, but I think its better to err on the side of having the functions there for people to look at.

**Comment by ngreenwald** [comment]
Can revisit if this becomes a problem for users
