### ISSUE TITLE
segmentation_utils.visualize_segmentation error

### ISSUE THREAD

**Issue by jkgopa** [angelolab/ark-analysis#354]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
When I run the segmentation_utils.visualize_segmentation cell, I get the error attached at the bottom of this write-up. As for the output files from this cell, most points have all 3 files, one point only produces the DNA_overlay file (Point12), and some points don't have any output files. The deepcell output folder before this step has all the points.

**To Reproduce**

Run the downstream cells using the output files of Deepcell.
[491defc4f7884fa5b876860476d2e78a.zip](https://github.com/angelolab/ark-analysis/files/5598258/491defc4f7884fa5b876860476d2e78a.zip)

**Expected behavior**

All 164 points should have a DNA_overlay, segmentation_borders, and segmentation_labels in the deepcell_visualization folder

**Screenshots**
![image](https://user-images.githubusercontent.com/56644685/100260764-aa613400-2efe-11eb-9977-715f60829d3f.png)

**Comment by ngreenwald** [comment]
You can set `show=False` to generate all of the plots. It won't display the image in the notebook, but you can look at them as TIF files until we get this part fixed

**Comment by jkgopa** [comment]
Ok sounds good, thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alex-l-kong** [comment]
@jkgopa so I'm going to guess that `visualize_segmentation` couldn't process one of the channels in `Point12` correctly, hence why it's the only one that has only one visualization result (whereas the others either have all or none). In the call to `visualize_segmentation`, can you pass in just `Point12` in the `fovs` argument? I'm sure you'll replicate the error by doing this. Try passing in a few other point names for `fovs` that currently have no output files in their respective folders: I'm pretty sure at least some of them will pass.
