### ISSUE TITLE
segmentation_utils.visualize_segmentation-file path does not exist

### ISSUE THREAD

**Issue by HoxB8** [angelolab/ark-analysis#356]
I created deepcell input files from several multi-channel tiffs.  Then I tried to enter multiple deepcell output tiff files into the post-processing script.  I am able to get the .xr file but when I try to run the segmentation_utils.visualize_segmentation, I get an error "File Path Does Not Exist".  I double-checked my file directory structure and made sure I had the deepcell_visualization directory in place and no errors in my viz_dir (which is  os.path.join(base_dir, "deepcell_visualization").   

**What have you tried so far?**
I've tried to update with "git pull" and "bash start_docker.sh --update".  I also made sure my file names are pretty simple like fov1_adjnorm.tiff.  
![Screen Shot 2020-11-29 at 5 03 52 PM](https://user-images.githubusercontent.com/58482675/100559051-e6c9c280-3265-11eb-91fd-5043bb1a6adb.png)

I'd appreciate any help on this.

**Comment by alex-l-kong** [comment]
@HoxB8 can you first test if the file path exists in the notebook by calling `os.path.exists(viz_dir)`?

**Comment by HoxB8** [comment]
Yes, I tried that and it returns True.  Also tried typing in the entire path directly, but still happens.  
![Screen Shot 2020-11-30 at 11 44 47 PM](https://user-images.githubusercontent.com/58482675/100711494-35f71c80-3366-11eb-93a0-d99a16910e6b.png)

**Comment by alex-l-kong** [comment]
@HoxB8 are you on a Windows machine by any chance? In the past, we've had Windows users run into issues with file paths in the past.

**Comment by HoxB8** [comment]
I'm using MacOS 10.15.7 with Python version 3.8.5.  I was thinking it might be something with a Mac as I had weird bugs that didn't seem normal.  Oddly, my colleague was able to run the script without issues, so maybe it's a software version issue.
