### ISSUE TITLE
Batch processing for trained SOM

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#363]
The current process for running the trained SOM is fairly slow (#345). This is in part because we have to perform individual operations for every pixel. I think we could do some linear algebra to create a batch version of this, and run multiple pixels through the trained SOM at once. This should substantial improvements in speed.

**Comment by alex-l-kong** [comment]
I asked the author of MiniSOM if there was an option to process MiniSOM in batches rather than one-by-one and he basically said he would, _only if_ I provided a solid research paper to back up doing it that way. Like speed optimization requires a paper to back it up. Guess we'll have to do some work for him.

**Comment by ngreenwald** [comment]
I believe he was referring to batch processing during training. I was thinking about that as well, could provide a nice speedup. But it would fundamentally change the algorithm, since you'd need to average the updates somehow. 

However, for batch-processing the trained version, there's no theory required, because you aren't actually modifying anything.

**Comment by alex-l-kong** [comment]
@ngreenwald OK, I missed the "trained SOM" part of this issue. Yeah, that would be even easier to do. We would have to modify the `winner` function to be able to assign multiple winning coordinate values at once for the clustering, which shouldn't be a huge deal.

**Comment by ngreenwald** [comment]
Yes, you can either modify winner to have a batch mode, or make a
batch_winner function, whichever is easier.

**Comment by alex-l-kong** [comment]
Closing this issue since we've switched to a full R subprocess call implementation.
