### ISSUE TITLE
Implement cell identification in SOM

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#365]
Following the generation of pixel metaclusters, the id of each cell must be determined based on the combination of pixel metaclusters present. 

This step is still in flux, we should consult with Candace before moving forward.

**Comment by alex-l-kong** [comment]
@ngreenwald any update from Candace regarding this step?

**Comment by ngreenwald** [comment]
Nope, we'll probably have an update Friday. Everyone is working on this review paper right now
