### ISSUE TITLE
fov name mismatch between data_xr_summed and segmentation_labels xrarrays

### ISSUE THREAD

**Issue by awedwards** [angelolab/ark-analysis#370]
I am running the Segment_image_data on some data (mibitiff=False if that's relevant) and ran into an error when trying to plot the overlays and save the expression .csvs. 

It seems that the fov names in the segmentation_labels have had a "_0" appended to them.

```
print(segmentation_labels.fovs) 

<xarray.DataArray 'fovs' (fovs: 5)>
array(['fov1_0', 'fov2_0', 'fov3_0', 'fov4_0', 'fov5_0'], dtype='<U6')
Coordinates:
  * fovs     (fovs) <U6 'fov1_0' 'fov2_0' 'fov3_0' 'fov4_0' 'fov5_0'
```

```
print(data_xr_summed.fovs)

<xarray.DataArray 'fovs' (fovs: 5)>
array(['fov1', 'fov4', 'fov3', 'fov5', 'fov2'], dtype='<U4')
Coordinates:
  * fovs     (fovs) <U4 'fov1' 'fov4' 'fov3' 'fov5' 'fov2'
```

**Comment by awedwards** [comment]
For some reason the deepcell output saved the segmented images as "fovX_0_feature_0" so changing the delimiter in the following line to "_0_feature_0" works as a workaround:

````
segmentation_labels = load_utils.load_imgs_from_dir(data_dir=deepcell_output_dir,
                                                    xr_dim_name='compartments',
                                                    xr_channel_names=['whole_cell'],
                                                    delimiter='_0_feature_0',
                                                    force_ints=True)
```

**Comment by ngreenwald** [comment]
Was it something about the way the files were named originally that caused the problem? Can you reproduce the problem with a different of file names that have the same format?

**Comment by awedwards** [comment]
No idea what happened, but I think this is working as expected now, so probably something wrong on my end. Thanks.
