### ISSUE TITLE
Add improved morphology metrics to default output

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#372]
**Is your feature request related to a problem? Please describe.**
The current cell_data file contains only a subset of the features we've found to be useful. 

**Describe the solution you'd like**
There are two things that need to be accomplished. 
1. The first, relatively easy one, is to change the default properties passed to regionprops so that all of them are included in the final csv. These should include the following:

```
props = ['label', 'area',   'major_axis_length', 'minor_axis_length',
             'perimeter', 'centroid', 'convex_area',
             'equivalent_diameter']
```

In addition, there are some custom values which can be computed from the regionprops values which we also want present in the final csv. This will require a couple lines of code once the regionprops values have been computed. These are the following:

```
cell_data['major_minor_axis_ratio'] = cell_data['major_axis_length'] / cell_data['minor_axis_length']
cell_data['perim_square_over_area'] = np.square(cell_data['perimeter']) / cell_data['area']
cell_data['major_axis_equiv_diam_ratio'] = cell_data['major_axis_length'] / cluster_df_selected['equivalent_diameter']
cell_data['convex_hull_resid'] = (cell_data['convex_area'] - cell_data['area']) / cell_data['convex_area']
cell_data['nc_ratio'] = cell_data['area_nuclear'] / cell_data['area']
```

2. The second thing that needs to be accomplished is adding in additional morphology metrics which are not simple combinations of skimage functions. The way I currently have this set up is that I run a separate skimage.regionprops call, and iterate over each object returned to compute these metrics. However, this for loop isn't super fast. It looks like the newest version of skimage includes an ["extra_properties"](https://scikit-image.org/docs/dev/api/skimage.measure.html?highlight=regionprops#skimage.measure.regionprops) argument to regionprops, which allows user-defined functions to be passed in and evaluated. This doesn't speed up the actual function I wrote, which is still slow, but it does help with the for loop aspect. However, this new version isn't compatible with some of our other packages I think. 

```
concavity_count = []
centroid_dif = []
updated_id = []

for fov in np.unique(cell_data['point']):
    current_label = segmentation_labels_selected.loc[fov, :, :, 'whole_cell'].values

    current_props = regionprops(current_label)

    for prop in current_props:
        # cell centroid shift
        cell_image = prop.image
        convex_image = prop.convex_image
        cell_M = skimage.measure.moments(cell_image)
        cell_centroid = cell_M[1, 0] / cell_M[0, 0], cell_M[0, 1] / cell_M[0, 0]

        convex_M = skimage.measure.moments(convex_image)
        convex_centroid = convex_M[1, 0] / convex_M[0, 0], convex_M[0, 1] / convex_M[0, 0]

        centroid_dist = np.sqrt((cell_centroid[1] - convex_centroid[1]) ** 2 +
                                (cell_centroid[0] - convex_centroid[0]) ** 2)

        centroid_dist /= np.sqrt(prop.area)

        # number of concavities
        diff_img = convex_image ^ cell_image
        if np.sum(diff_img) > 0:
            labeled_diff_img = label(diff_img)
            hull_prop_df = pd.DataFrame(regionprops_table(labeled_diff_img, properties=['area', 'perimeter']))
            hull_prop_df['compactness'] = np.square(hull_prop_df['perimeter']) / hull_prop_df['area']
            small_idx = np.logical_and(hull_prop_df['area'] > 10,
                                       hull_prop_df['compactness'] < 60)
            large_idx = hull_prop_df['area'] > 150
            combined_idx = np.logical_or(small_idx, large_idx)

            concavities = np.sum(combined_idx)
        else:
            concavities = 0

        concavity_count.append(concavities)
        centroid_dif.append(centroid_dist)
        updated_id.append(fov + '_' + str(prop.label))

new_df = pd.DataFrame({'unique_id': updated_id,
                       'concavity_count': concavity_count,
                       'centroid_dif': centroid_dif})


cell_data = cell_data.merge(new_df)

```

**Comment by ngreenwald** [comment]
In addition, we should update the description of the [cell table](https://ark-analysis.readthedocs.io/en/latest/_rtd/data_types.html) to include all of the column names and what they represent

**Comment by alex-l-kong** [comment]
@ngreenwald about the second point, are cell centroid shift and # concavities the only metrics we need for now, or will there be others Dunja will require?

**Comment by ngreenwald** [comment]
Right now these are the only ones Mike and I have thought about. In the future, we might want to add more. Either way, further modularizing the code to support future metrics would be good.
