### ISSUE TITLE
Deepcell image labelling

### ISSUE THREAD

**Issue by HPiyadasa** [angelolab/ark-analysis#376]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

## **Describe the bug**
Deepcell segmentation_labels seem to have changed (Point1 vs Point1_0) so I am getting errors when generating expression matrices from the labeling + imaging data. 

## **To Reproduce**
1. Go to Segment_Image_Data.ipynb notebook
2. Error occurs in the following code block

cell_table_size_normalized, cell_table_arcsinh_transformed = \
    marker_quantification.generate_cell_table(segmentation_labels=segmentation_labels,
                                              tiff_dir=tiff_dir,
                                              img_sub_folder="TIFs",
                                              is_mibitiff=MIBItiff,
                                              fovs=fovs,
                                              batch_size=5)

## **Screenshots**
<img width="1382" alt="Screen Shot 2021-01-21 at 1 13 15 PM" src="https://user-images.githubusercontent.com/62519486/105413107-7b0f3080-5bea-11eb-847c-6a0b19d56305.png">

**Comment by ngreenwald** [comment]
Yes, looks like deepcell has changed the naming conventions for generated files. 
As a temporary workaround, you change the ```delimiter``` flag in ```load_imgs_from_dir``` to have a leading 0 as well. We'll update the default to reflect the new change

**Comment by ngreenwald** [comment]
Naming is back to normal now; next time you download your results you'll be able to revert back to original delimiter.

**Comment by HPiyadasa** [comment]
Thanks!
