### ISSUE TITLE
Develop a standardized column format for cell tables

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#385]
**Is your feature request related to a problem? Please describe.**

Certain analysis processes (ex. spatial analysis) expect cell tables to come in with a certain column format. We make a lot of assumptions that we can no longer make with the vast amount of different table formats we've seen so far. This has caused a lot of 'column not found' errors.

**Describe the solution you'd like**

We need to make our codebase more robust to the diversity of cell tables we see. One possible method is a column reformatter, which will be run prior to the processes.

**Describe alternatives you've considered**

We've considered passing channel lists between functions to solve the issue of finding channel columns, but this can get very tedious and requires knowledge of exactly what channels the user wants for different tasks.

**Comment by ngreenwald** [comment]
There are a couple different ways we could address this. The simplest would be an option to automatically rename a specified column to a new column name. Also providing (even) more informative error messages about what mismatch was found and why that's a problem.

In addition, once everything has been formatted, we can print out what the function is going to run on, providing a feedback mechanism for people to know if they've incorrectly specified certain column names

**Comment by ngreenwald** [comment]
Now that we're controlling how data is generated at each step, don't think this is an issue anymore
