### ISSUE TITLE
Add option to set nuclear_counts = True in generate_cell_table

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#387]
**Is your feature request related to a problem? Please describe.**

Right now, there's no option to set `nuclear_counts = True` in a call to `generate_cell_table`. This is problematic because the user cannot extract nuclear properties nor retrieve any `props` computed by `assign_multi_compartment_features`.

**Describe the solution you'd like**

We should add the `nuclear_counts` parameter to `generate_cell_table` as well.

**Comment by ngreenwald** [comment]
Yes, once we have the option to generate nuclear segmentations, we should add in this. Hopefully next week
