### ISSUE TITLE
Docker memory size requirement calculation

### ISSUE THREAD

**Issue by ritamyhuang** [angelolab/ark-analysis#414]
**Is your feature request related to a problem? Please describe.**
What is the memory size needed to be allocated to Docker for segmentation on a set of images? For example, if I have a set of 50 images that I want the segmentation script to process altogether at once, and each image is around 17MB, how much memory would have to be allocated to Docker?

I am always unsure of how much memory is needed by Docker to segment my image sets. It is difficult to decide on which computer the segmentation script should be run when the required memory size is unknown.

**Describe the solution you'd like**
The segmentation script reads in the image set and outputs an estimation of the memory size needed.

**Describe alternatives you've considered**
Given a formula to calculate the memory size needed, so we can make an estimation ourselves.

Thank you!

**Comment by ngreenwald** [comment]
Hi Rita, 
I think what we'll do is make the script take significantly less memory so that it can be run on a laptop even if you have tons of images. As people start running larger and larger cohorts this is going to become a more common problem, thanks for flagging it for us.
