### ISSUE TITLE
Create SOM table with pixel clustering information

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#417]
**Is your feature request related to a problem? Please describe.**

The current structure we're using to write the data (`feather` files) will make it more cumbersome to perform operations such as aggregating. We would like the data to be contained in one table (ex. `.csv`) for ease of use.

**Describe the solution you'd like**

We can either write the data directly to `.csv` format in `consensus_cluster` or separately. While possibly more inefficient, I'm more of a fan of the latter approach because we can use the functions in `som_utils` we've written to aggregate the data if needed before saving.

**Comment by ngreenwald** [comment]
I thought Feather was more efficient than writing to CSV? Isn't that why we switched to it?

**Comment by alex-l-kong** [comment]
@ngreenwald oh absolutely, `.feather` is much faster to read and write too. I was thinking more of if the user wanted to use this file outside of the Jupyter notebook/Docker. I don't think everyone in the lab knows about `.feather` or how to use it, but they would for sure know how to use a CSV. CSVs may also integrate better with the processes others have written or will write.

If we don't expect them to use the data outside of FlowSOM clustering, however, I can just write them all to one giant `.feather` file. Definitely far more efficient that way.

**Comment by ngreenwald** [comment]
What do we need the single giant file for? We're going to have datasets where it's prohibitive to concatenate it all together

**Comment by alex-l-kong** [comment]
@ngreenwald we should clarify what we want this PR to accomplish. Our `.feather` files already look to be in a nicely-formed tabular format, similar to the cell tables created in `Segment_Image_Data`. Were we looking to aggregate the data on certain columns? If not, remind me what additional steps we need to do with the final `.feather` files to get them in a format that will be compatible?
