### ISSUE TITLE
Add pixel clustering visualization

### ISSUE THREAD

**Issue by cliu72** [angelolab/ark-analysis#421]
**Is your feature request related to a problem? Please describe.**
Add plots that summarize pixel clustering results.

**Describe the solution you'd like**
1. Pixel clusters: histogram of number of pixels in each cluster
![image](https://user-images.githubusercontent.com/11382352/117421469-6756b400-aed3-11eb-8638-24f06f761e6d.png)

2. Pixel clusters: histogram of number of pixels in each metacluster
![image](https://user-images.githubusercontent.com/11382352/117421595-86554600-aed3-11eb-96f7-dbf3d4fd86a8.png)

3. Pixel clusters: heatmap of pixel clusters x markers
![image](https://user-images.githubusercontent.com/11382352/117421631-90774480-aed3-11eb-95c2-c0fe46378d5b.png)

4. Pixel clusters: heatmap of pixel metaclusters x markers
![image](https://user-images.githubusercontent.com/11382352/117421657-9705bc00-aed3-11eb-8f33-864f153dc7e2.png)

5. Cell clusters: heatmap of cell cluster x pixel metacluster
![image](https://user-images.githubusercontent.com/11382352/117421978-f4017200-aed3-11eb-9d13-d21e23ee3474.png)

6. Cell clusters: heatmap of cell metacluster x pixel metacluster
![image](https://user-images.githubusercontent.com/11382352/117422013-fe237080-aed3-11eb-908e-2dd07aaf46ef.png)

7. Cell clusters: heatmap of cell cluster x marker
![image](https://user-images.githubusercontent.com/11382352/117422051-09769c00-aed4-11eb-910a-d608cf8f0bf2.png)

8. Cell clusters: heatmap of cell metacluster x marker
![image](https://user-images.githubusercontent.com/11382352/117422089-14313100-aed4-11eb-860b-fb1907a4cfbf.png)

9. Notebook to view overlays
Example: https://colab.research.google.com/drive/1G5WQtz5VRxMb-8Z7om6McC4Szyaek_pk?usp=sharing

**Comment by alex-l-kong** [comment]
@cliu72 how much of this is Zak taking on? I can work on the rest.

**Comment by cliu72** [comment]
I think it would still be nice to have all of this in a separate notebook to have all the final visualizations in one place.
