### ISSUE TITLE
Add rescale information to notebook

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#423]
**Is your feature request related to a problem? Please describe.**
The current segmentation notebook hides the rescale factor. We should pull this arg out with a description of when to change it

**Comment by alex-l-kong** [comment]
@ngreenwald can you clarify when rescaling should happen on the image data?

**Comment by ngreenwald** [comment]
This is an argument to the function that sends the images to deepcell.org. We just need to define it and provide some guidance to the user on what the default is, and what it can be changed to
