### ISSUE TITLE
Add module for random sampling methods

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#430]
**Is your feature request related to a problem? Please describe.**

There are several features in `ark-analysis` that require some form of random sampling. As more methods of random sampling are desired, it is best to put all of these methods in their own module.

**Describe the solution you'd like**

We can add a file called `random_utils.py` in the `utils` folder which contains different methods of sampling we can call.

**Additional context**

The problem first arises in pixel clustering, as lab members may desire more than just a simple random sample of pixels per fov.

**Comment by ngreenwald** [comment]
low priority
