### ISSUE TITLE
Add support to TMAs to mibi tiling script

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#436]
**Is your feature request related to a problem? Please describe.**
The current tiling script works for large tiled regions where each tile/fov is flush with the adjacent ones. However, for TMAs, what we often have is a grid of samples spaced equidistantly from one another. Because there is space between each core in the TMA, we don't want to put the subsequent tiles bordering the previous one

**Describe the solution you'd like**
What what work well here is if there was an initial prompt in the tiling script asking if we want a tiled region, or tiled TMA. If TMA is selected, it would expect us to to define the upper left hand corner and bottom right hand corner of the rectangle we want to tile over, in the form of FOVs.

Reading in two FOVs would define the grid. For the spacing, the user would specify the size of each FOV, and the number of FOVs along each axis. The script would then uniformly space the FOVs across that distance, using the start and end coordinates from the provided FOVs to determine what the spacing between FOVs should be, since it will be greater than the FOV size.

**Comment by alex-l-kong** [comment]
@ngreenwald for TMAs, is it possible for tiles to overlap or should we check that they do not given the user specifications?

**Comment by ngreenwald** [comment]
They should never overlap, that's a good input validation check
