### ISSUE TITLE
Cell Table Column Visualization

### ISSUE THREAD

**Issue by ackagel** [angelolab/ark-analysis#442]
### **Problem**
Suppose after clustering/labelling cells, you'd like to see those new labels within a FOV, before running something like spatial analysis.  Currently, there's no built in plotting utility in `ark-analysis` to accomplish that.

### **Solution**
A function (either in `ark.utils.plot_utils` or `ark.analysis.visualize`) that takes in a cell table, a label image, and a column name, which will plot the column name values over the corresponding cell label ids.

**Comment by ngreenwald** [comment]
I'm not sure I understand what the request is here. It sounds like what we do for the cell_clustering functionality https://github.com/angelolab/ark-analysis/blob/new_som/templates/example_pixel_cell_clustering.ipynb. Is it different than `plot_utils.plot_clustering_results`?

**Comment by ackagel** [comment]
Nope; didn't know we had that already.  In that case, it'd be good to use that in the spatial analysis notebook.  Something to add while resolving issue #443 perhaps

**Comment by ngreenwald** [comment]
Sounds good, will you add that?
