### ISSUE TITLE
Running the script to get the jupyter session open URL link_Unable to mount

### ISSUE THREAD

**Issue by Kwokim** [angelolab/ark-analysis#444]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a new issue*

**What are you trying to do?**
A clear and concise description of what script or function you're using
./start_docker.sh
**What is the problem?**
A clear and concise description of what issue you're running into.
$ ./start_docker.sh
docker: Error response from daemon: OCI runtime create failed: invalid mount {Destination:\Program Files\Git\usr\local\lib\python3.6\site-packages\ark Type:bind Source:/run/desktop/mnt/host/c/Users/kwoki/ark-analysis/ark;C Options:[rbind rprivate]}: mount destination \Program Files\Git\usr\local\lib\python3.6\site-packages\ark not absolute: unknown.

**What have you tried so far?**
A clear and concise description of what steps you've taken to try and address the problem.
Rerunning back from:
cd ark-analysis 
docker build -t ark-analysis

**Additional context**
Add any other context or screenshots here.
I changed the script file previously on "start_docker.sh" 
from line ~20 "docker run -it \" to "docker run -t \" for tty format

This was because previously i got this:
$ ./start_docker.sh
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'

**Comment by ngreenwald** [comment]
@ackagel looks like a windows issue. Can you take a look?
@Kwokim, while we look into this, you can set up the environment with Conda instead

**Comment by Kwokim** [comment]
Sure thing, 

How do I set up the environment with Conda?

**Comment by ngreenwald** [comment]
See here for general conda instructions: https://ark-analysis.readthedocs.io/en/latest/_rtd/development.html

**Comment by ackagel** [comment]
I think this has to do with paths being 'ambiguous' for bash scripts running in window's git-bash.  I've seen a work-arounds which set the environment variable,`export MSYS_NO_PATHCONV=1` before running the docker. 

Try adding that to the `start_docker.sh` file just before line ~20.

**Comment by Kwokim** [comment]
Hello,

I have attached the txt file after downloading anaconda and going through the steps for installing. Couple of things I saw in the installation process:

  1.  $ is not recognized? I took this out and then "git" as a command was not recognized
  2.  Docker does show ark analysis is "in use" after using the

cd ark-analysis
docker build -t ark-analysis

This was added to ~line 20 but unknown if this solves the problem since the code language was incorrect?
export MSYS_NO_PATHCONV=1

Best

Dr. Kwok (Chris) Wai Im, PhD
Dr. Matthew Krummel Laboratory
University of California San Francisco
513 Parnassus Avenue
Room HSW-518. Box 0511
San Francisco, CA 94143-0511
469-288-6402<tel:469-288-6402>

________________________________

**Comment by ackagel** [comment]
The default 'Anaconda Prompt' on Windows doesn't support bash scripts, so the install process would not work.  Try using the same `export MSYS_NO_PATHCONV=1` fix, but run the installation process via git-bash (the previous terminal/shell/command-line you were using).  If this still doesn't work, the conda installation method (which, to clarify, is an alternative to the docker method) goes as follows:

From the 'Anaconda Prompt', these commands should successfully install `ark-analysis`:
 - Run `conda create -n <my_env> python=3.6`, where `<my_env>` is a name you set.
 - If the next line is prepended with `(<my_env>)` proceed to the next step.  Otherwise, if it's prepended with `(base)`, run `conda activate <my_env>`.
 - Inside the ark-analysis repo/folder, run `python -m pip install -r requirements.txt` to install the requirements.

To then run the jupyter lab/notebooks, run:
```
python -m jupyter lab --ip=0.0.0.0 --allow-root --no-browser --port=8888
```
and open the provided url in your browser.

**Comment by ngreenwald** [comment]
@ackagel will you open a PR to modify readme to 1) state that '$' is the interpreter for Mac and is used to indicate what code needs to be entered, users should actually type it and 2) the period needs to be included in the docker build -t command?

**Comment by Kwokim** [comment]
Hi sorry for my inexperience,

I am stuck on the line in conda:

To do so, on your command line, type conda create -n <my_env> python=3.6, where <my_env> is a name you set. Our codebase only supports Python 3.6, so please do not change the python=3.6 flag when creating your environment.

The "<my_env>" is supposed to be what name? Is this the file directory path to the folder?

Best

Dr. Kwok (Chris) Wai Im, PhD
Dr. Matthew Krummel Laboratory
University of California San Francisco
513 Parnassus Avenue
Room HSW-518. Box 0511
San Francisco, CA 94143-0511
469-288-6402<tel:469-288-6402>

________________________________

**Comment by Kwokim** [comment]
Sorry,

I figured that out. I have the ark setup downloaded and ark-analysis is listed. However when i run the command "import ark":

'import' is not recognized as an internal or external command,
operable program or batch file.

Best

Dr. Kwok (Chris) Wai Im, PhD
Dr. Matthew Krummel Laboratory
University of California San Francisco
513 Parnassus Avenue
Room HSW-518. Box 0511
San Francisco, CA 94143-0511
469-288-6402<tel:469-288-6402>

________________________________
