### ISSUE TITLE
cannot run start_docker

### ISSUE THREAD

**Issue by HoxB8** [angelolab/ark-analysis#454]
**What are you trying to do?**
Run start_docker

**What is the problem?**
After entering ./start_docker.sh in the command prompt, a new window opens and closes after a few seconds.  Then the process ends and goes to a new command line

**What have you tried so far?**
Tried updating docker and re-cloning the ark-analysis to a new folder and running everything again.  Also tried 'bash start_docker.sh'

**Additional context**
I'm running this on Windows 10.  I had no problem running it about 1.5 month ago.  At that time I used 'bash start_docker.sh'

![image](https://user-images.githubusercontent.com/58482675/130911350-ffea1524-81c2-4fd9-b48f-2e752c71dda3.png)

**Comment by HoxB8** [comment]
I ran the code in windows subsystem linux, then it works.

**Comment by ngreenwald** [comment]
I think it's fine for us to just support one option and specify it. I'm not at all familiar with windows, which one would be easier do you think?

**Comment by y2kbugger** [comment]
Git for Windows is what I would pick. I think people would be more likely
to have it already ready.

Note this wouldn't exclude anyone from running it successfully via their
own method for bash on Windows, e.g. WSL or cygwin. Everyone that's having
problems is either trying to run the wrong command, or trying to run it on
Windows in PowerShell or CMD.exe

We can mention that as a note.

**Comment by ngreenwald** [comment]
Sounds good. @alex-l-kong when you walk through on the lab windows computer, can you take some screenshots of the windows git environment to add to the windows-specific section of the Readme
