### ISSUE TITLE
Add kwargs support for parameter passing to visualize.py

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#461]
**Is your feature request related to a problem? Please describe.**

The current setup of `visualize.py` requires us to specify a ton of arguments (ex. `x_label`, `y_label`, `dpi`, `title`, etc.). This can be burdensome to remember and type out.

**Describe the solution you'd like**

A better way to handle this is to specify a `**kwargs` argument for these functions. Using kwargs allows for much easier parameter passing and handling.

**Comment by alex-l-kong** [comment]
@ngreenwald having worked on this for a little bit, using `**kwargs` is actually going to end up being a very messy solution for us.

The main reason is different `matplotlib`/`seaborn` functions require different sets of `**kwargs`. The easiest hack is to define two separate `dict` arguments (`function_a_args={}`, `function_b_args={}`), but this is even less intuitive for a user to use (since they have to explicitly define the dicts, as opposed to letting `**kwargs**` implicitly take care of it).

Considering the fact that many `matplotlib` and `seaborn` functions already document several params, I don't think it's too much to spell it all out to the user. It's a little tedious when writing out the function, but it makes it a lot easier to use down the line.

I'm open to further ideas, but I think it may be best to close this issue for the time being.

**Comment by ngreenwald** [comment]
Sounds good, always better to admit when something isn't worth it rather than just do it anyway
