### ISSUE TITLE
code files not there when I open docker 

### ISSUE THREAD

**Issue by rachel662** [angelolab/ark-analysis#467]
Hi there 
I'm trying to follow your Readme to get started with ark analysis, thanks for putting it together! 
I'm having a problem with the scripts not being there when I manage to connect with the jupyter notebook, and I have to change a few small things in the command line beforehand to get that far, i.e. take out the ' ' around the . in the 

docker build -t ark-analysis  '.'    line 

the scripts not being there means when I try to run the jupyter notebooks they're not recognising the file paths, so I was wondering if I could get any advice on what i'm doing wrong? Thanks so much in advance 

![image](https://user-images.githubusercontent.com/63318678/134663445-644a883e-e2a0-4eaa-9729-672cda463338.png)

Cheers 
Rachel

**Comment by rachel662** [comment]
![image](https://user-images.githubusercontent.com/63318678/134674329-777c7e50-285e-416c-b076-8ace23f5593d.png)

I also attach an image of the error I get

thanks so much for your help 
Rachel

**Comment by ngreenwald** [comment]
Hi Rachel, can you please screenshot the entire cell and full error message? Right now it's not possible to figure out what's causing the error. 

Thanks,
Noah

**Comment by rachel662** [comment]
Hi there
sorry for being so slow to get back to you 
here is the screenshot 

thanks again for your time
Rachel 

![image](https://user-images.githubusercontent.com/63318678/135268847-eb86f75b-e1d8-48a6-9ae2-dc0c9ccb9737.png)

**Comment by alex-l-kong** [comment]
@rachel662 in the second cell (the one where you set `base_dir`, `tiff_dir`, etc.), did you change any of the default values?

Also, you should not need to put quotations around the `.` in `docker build -t ark-analysis .`. Not sure why that was specified in our `README`, but we'll change it to be clearer.

**Comment by rachel662** [comment]
Hi, 
thanks so much for getting back to me 
I don't think I did? but it's definitely a possibility I did whilst trying to get it to work  - here's a screenshot of the second cell

thanks for the info about the quotes too

![image](https://user-images.githubusercontent.com/63318678/135593728-99d2fd90-07a7-4ee3-8419-385ff2ae2f0e.png)

Cheers
Rachel

**Comment by alex-l-kong** [comment]
@rachel662 yes these are the correct default file paths. Can you create a new cell in the notebook with these lines of code:

```
print(base_dir)
print(input_dir)
print(tiff_dir)
```

then share the output with me? We've had issues with file paths in Windows before and I want to check that they're not popping back up in your case.

**Comment by rachel662** [comment]
Hi, thanks so much again and sorry for my slow reply 
here is the output

![image](https://user-images.githubusercontent.com/63318678/135851744-4aa0c55d-75b1-4937-8140-4a25b2607cb3.png)

**Comment by alex-l-kong** [comment]
@rachel662 these file paths should be correct. I'm curious to know why only `single_channel_inputs` cannot be found, but `input_data` is there. Before we move on, can you manually check `data/example_dataset/input_data` to see if it contains a folder named `single_channel_inputs`? If it doesn't, you may need to re-checkout the folder from GitHub.

**Comment by alex-l-kong** [comment]
@rachel662 try replacing:

```
tiff_dir = os.path.join(input_dir, "single_channel_inputs/")
deepcell_input_dir = os.path.join(input_dir, "deepcell_input/")
```

with:

```
tiff_dir = os.path.join(input_dir, "single_channel_inputs")
deepcell_input_dir = os.path.join(input_dir, "deepcell_input")
```

**Comment by alex-l-kong** [comment]
Hi @rachel662, it looks like at least 2 others have opened issues relating to `start_docker.sh`. Looks like there're several commands on Mac/Linux that don't work on Windows. We'll be opening a separate issue to address these concerns.

In the meantime, can you try opening `start_docker.sh` and replacing all instances of `$PWD` with `%cd%`?

**Comment by alex-l-kong** [comment]
@rachel662 when you open up `start_docker.sh`, you should see lines towards the end of the file like this:

```
 -v "$PWD/ark:/usr/local/lib/python3.6/site-packages/ark" \
 -v "$PWD/scripts:/scripts" \
 -v "$PWD/data:/data" \
```

Try replacing `$PWD` in these lines with `%cd%`.

In the meantime, we'll be working on adding a patch for Windows. Stay tuned.

**Comment by rachel662** [comment]
Hi there, I don't think I have these lines actually, unless i am looking in the wrong place - here is the top of the window that opens up when I run start_docker.sh

![image](https://user-images.githubusercontent.com/63318678/137113636-3e9dcbd8-1f85-4cc3-8d8a-ecf0d9c0ec8a.png)


and from the bottom of the window, thanks so much for your help


![image](https://user-images.githubusercontent.com/63318678/137113816-e7995d9b-bf71-4e78-97a0-29baef705a76.png)

**Comment by alex-l-kong** [comment]
@rachel662 you have to explicitly open up the actual file named `start_docker.sh` in a text editor to change this. `start_docker.sh` won't be visible when you open up the Docker link.
