### ISSUE TITLE
Change data parameter to pandas DataFrame type in draw_heatmap

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#469]
**Is your feature request related to a problem? Please describe.**

Right now, `draw_heatmap` is the only function that takes `data` as a `numpy.ndarray` in `visualize.py`. It was likely done this way to make clipping `np.inf` and `np.nan` values a little easier, but at the cost of the usage of `visualize` becoming somewhat inconsistent.

**Describe the solution you'd like**

It's easier to pass in a `pandas.DataFrame` instead, and `pandas` supports the `np.inf` and `np.nan` clipping by using the `.values` attribute. This change will need to be reflected in the spatial and neighborhood analysis notebooks (and later the pixel clustering), where we visualize at least 1 heatmap.

**Comment by ngreenwald** [comment]
Take a look if this is still a problem, if so should be quick to address

**Comment by alex-l-kong** [comment]
@ngreenwald didn't turn out being as big of a problem as I thought originally, converting from `pandas` to `numpy` isn't a big inconvenience and I can see applications where the user wants to pass in a `numpy` array directly.

If you think this should be addressed soon, I can easily get this in, but for now, I think other issues (ex. splitting up `som_utils.py`, supporting `**kwargs` in `visualize.py`) are higher priority for the presentation.
