### ISSUE TITLE
Add automatic MIBI image downloading from MIBItracker for QC analysis

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#482]
**Section 1: Design details**

**Relevant background**

During the MIBI QC pipeline, we need a way to automate the process of downloading files users extract from MIBI off from MIBItracker. Right now, users have to manually download the files off of the MIBItracker themselves. This requires a significant amount of interruption for those running the pipeline as users have to gather the files, save it to their own device, then run it.

The way forward is to use Ionpath's API to access MIBItracker images scanned by the user. With the user some pre-defined fields from their run, an API endpoint can be created to download the data directly from running the QC pipeline (done in a Jupyter notebook) into a specified path. This removes the bottleneck of the user needing to access MIBItracker and downloading the image data directly. It also allows the data to be created for future tasks in the `ark` pipeline (ex. image segmentation, pixel clustering, etc.).

**Design overview**

This process will be put inside the QC notebook (`example_qc_eval_comp.ipynb`) prior to running QC metric analysis. Please consult the design doc for this notebook (https://github.com/angelolab/ark-analysis/pull/476) to learn more about its placement in `ark` and its structure.

At the beginning, the user will be allowed to specify the username and password to their MIBItracker account as well as their particular run information and which fovs and channels they wish to download. Using this information, we can use Ionpath's `mibilib/mibitracker` library to create an endpoint URL and make an API request to retrieve the data the user wishes to retrieve.

With this information, we can loop through each fov and channel, extract the image data as an `m x n` `numpy` array (where `m x n` is the dimension of the image scanned by MIBI), and write the data to `.tiff`. While downloading the data, the directory structure will be created in a format that `ark` can work with (see the `Output files` section for a visual example, or consult `ark/data/example_dataset` for an example in `ark`). With this in mind, the user can also specify the name of their output folder (`data_write_dir`) and an `img_sub_folder` if they wish to store the image data in a particular subdirectory structure of each folder.

As with the QC metric extraction, the vast majority of the processes (ex. validating the `fovs` and `chans`, extracting the images as `numpy` arrays, saving the data), will be abstracted away in `ark/mibi`. The notebook will remain barebones with a minimal number of function calls visible to the user.

_Note and clarification_

~~This scheme assumes the user wants to download in non-MIBItiff format. Will there be applications where users will need the images downloaded in MIBItiff format?~~

~~If yes, it is possible to do with a different function call to the `mibilib/mibitracker` library and a custom `tiff` writer provided in `mibilib/mibidata`. In this case, we'll also need to provide the user with a way to specify the extraction type (MIBItiff or not).~~

**Design list/flowchart**

![qc_mibitracker_download drawio](https://user-images.githubusercontent.com/31424707/141360208-afd9e0a5-ff09-4729-9871-87055642125c.png)

**Required inputs**

The user will need to provide the following information:

- MIBItracker email
- MIBItracker password
- ~~Extraction type (if we choose to support both non-MIBItiff and MIBItiff downloads)~~
- Run name and run label (NOTE: these are different!)
- The name of the directory to write the image data to
- The name of the sub folder to place the image data into ~~(if so desired for non-MIBItiff extraction)~~

The run name and run label can be found on the particular run's page in Ionpath:

<img width="710" alt="Screen Shot 2021-11-11 at 3 43 54 PM" src="https://user-images.githubusercontent.com/31424707/141384846-78ef64f9-fa52-4ad6-bf7c-bcae52278da6.png">

**Output files**

Data for a particular `fov`/`channel` will be extracted as a `numpy.ndarray` in the dimensions extracted during the run. The data type of each image is `int`.

While saving each `numpy.ndarray` to an appropriately named `.tiff` file, we'll need to create the appropriately named directory structure as such:

![Untitled Diagram drawio](https://user-images.githubusercontent.com/31424707/141361100-acc5efa5-82f1-4848-be35-a4870b9b39eb.png)

~~Note that if MIBItiff extraction is supported, the `.tiff` files will always be placed in the root of the `fov` folder.~~

What an extracted image channel looks like will vary based on the specifics of the data extracted. Please consult your own MIBI-scanned data for an example of what a channel file looks like.

**Section 2: Implimentation details**

Because this will be run in conjunction with QC metric evaluation, the encapsulated functions needed for MIBI downloading will be placed in `qc_comp.py`. The notebook, `example_qc_metric_eval.ipynb`, will also be updated to include the MIBI download process at the beginning.

**Control flow**

_Input specification_

The user will need to provide their `email`, `password`, `run_name`, and `run_label` in appropriately named variables in `example_qc_metric_eval.ipynb`. See the Design list/flowchart section for information on how to retrieve the run name and run label from the Ionpath site.

If they wish, the user can also explicitly set a `fovs` and `chans` variable, which defines a specific subset of FOVs and channels to download. These variables default to `None`, meaning all of them will be downloaded.

Additionally, the user will need to specify `data_dir`, the location of the data folder they wish to extract the FOV image data into. If they wish, the user may explicitly set `img_sub_dir`, which creates an additional subfolder inside each FOV folder where the image data will be placed (by default, `img_sub_dir` is `None`, meaning the data will be saved in the root of each FOV folder).

_Retrieve the MIBI run information_

The notebook defers this work to a function, `download_mibitracker_data`, in `qc_comp.py` which takes in the user-specified email, password, run name, and run label.

This function first creates a MIBItracker `request_helper` instance: this is needed to call Ionpath's API to interactive with, upload, and download images. For the purposes of this project, only the latter will be needed. This `request_helper` instance will be created by calling a hidden function in `qc_comp.py`, appropriately named `create_mibitracker_request_helper`.

With the `request_helper` instance, we can retrieve the run info by calling `request_helper.search_runs` with both the run name and run label. This returns a Python `dict` that contains the name of the XML file in storage used to generate the file name, the FOV names, as well as the channels used for each FOV, etc. Let's call this `dict` `run_info`.

Before actually downloading and creating the image dataset, we can use `run_info` to locate the path of the XML run file in Ionpath storage. Using `request_helper.download_file` with the full XML run path in Ionpath storage as a param, we can retrieve this XML data as an `io.BytesIO` object, which we can then save to an XML file in the root of `data_dir` with the same name. This will be needed to determine run order and will be especially useful during the actual QC metric extraction process.

Note that the XML data needs the intermediate saving step because `io.BytesIO` cannot be converted from binary to XML otherwise.

_Create the image dataset_

Using `run_info`, we can identify the names of each FOV, their internal image ID, and their respective channels. Note that if the user explicitly specifies `fovs` and `chans`, an additional layer of verification is needed to ensure the provided FOV and channel subsets exist within the run.

When looping over each desired FOV, a specific folder for the FOV will be created inside `data_dir` (and an `img_sub_folder` if specified). The desired channel data for each FOV can be downloaded one-by-one using `request_helpers.get_channel_data`, passing both the internal image ID of the FOV and the channel name retrieved from `run_info`. This returns a `numpy` array, which can then be saved to the desired FOV folder using `skimage.io.imsave` as `{chan_name}.tiff`.

**Additional considerations**

Because downloading from MIBItracker requires heavy use of the `mibitracker` library in `mibilib` (developed by Ionpath), this library will need to be included in `requirements.txt`. We have run into `mibilib` dependency issues with our own repo, and there are two possible ways around this:

1. Resolve the dependencies: this will likely have to be on our end. The downside of this method is that there is no way to know ahead of time if these updates will break certain parts of the `ark` pipeline.
2. Copy snippets of the `mibitracker` library into our code base: a hacky but effective way around this, since `mibitracker` is just a wrapper around the `requests` library in Python in many aspects. If we go this route, these wrapper functions will also be placed in `qc_comp.py`.

Because QC metric analysis is going to be run on the commercial instrument computer, it may not be useful to create the full image dataset, directory structure and all. Alternatively, the extracted images can be stored in an `xarray.DataArray`, with dimensions specifying the `fov`, `x`, `y`, and `channel` names. This `DataArray` can be passed directly to `compute_qc_metrics` in `example_qc_metric_eval.ipynb` (as opposed to the function needing to load in the image dataset using `load_utils`). If this is the case, the current process in `example_qc_metric_eval.ipynb` will need to be updated.

**Milestones and timeline**

1. Update `qc_comp.py` with helper functions to download images from MIBItracker and create the image dataset, fully tested (2-3 days, depending on whether we'll be directly calling `mibilib` or copying their wrapper functions to our repo).
2. Update `example_qc_metric_eval.ipynb` with MIBItracker download process included prior to QC metric evaluation (1-2 days, depending on if we'll be saving the data to a directory structure or using a raw `xarray.DataArray`).

**Comment by ngreenwald** [comment]
We don't need to support MIBITIFF downloads for now, fine to skip. 

How much of the run label and run info is contained within the JSON file that is automatically generated when a run is created? Can these be inferred directly by the script if pointed to the correct directory, or some other metadata present?

**Comment by ngreenwald** [comment]
@efrancis28 gonna go ahead and approve this, comment if you have any additional requests

**Comment by ngreenwald** [comment]
Looks good to me, can go ahead and get started.
