### ISSUE TITLE
Update TMA tiling script to match against user-generated points

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#484]
*This is for internal use only; if you'd like to open an issue or request a new feature, please open a bug or enhancement issue*

**Section 1: Design details**

**Relevant background**

The current tiling script reads in a `fov_tile_info` params dict from the user defining the start and end FOV for each region and, based on user params, generates the location of every FOV in the region based on additional user parameters such as the number of FOVs and the size of each FOV along the x and y coordinates.

However, these do not necessarily correspond to the actual desired points in question. On BeTTy, this wasn't a problem; users could easily adjust the point if it was set incorrectly. Unfortunately, the commercial instrument is not so forgiving in this regard, making it practically impossible to adjust the point after being set in the JSON params set in `example_fov_grid_generate.ipynb`. There is no way in the script currently to handle this.

With this in mind, we need an extra line of defense against the commercial instrument's inflexibility. The user will now be able to provide their own tiling parameter JSON (in a similar structure to the one returned by `create_tiled_regions`). In doing so, the user-provided JSON can then be compared against the `create_tiled_regions` JSON as a verification step prior to doing a run on the commercial instrument.

**Design overview**

This process will be appended to `example_fov_grid_generate.ipynb` after the call to `create_tiled_regions` (and subsequent saving).

We will need the user to specify an additional parameter which defines the path to the JSON they wish to verify against. This data will be read in, and both the user-proposed JSON and the automatically-generated JSON (returned by `create_tiled_regions`) will be passed into a function called `assign_closest_tiled_regions`.

Additionally, the user will need to provide a path to the region they wish to tile. This should be in the form of a `.tiff` file. This path will be used to visualize the results over (as later defined in the description of `compare_user_and_script_tiles`).

`assign_closest_tiled_regions`, in a nutshell, takes each of the user-proposed FOVs and maps them onto the closest automatically-generated FOV (in Euclidean space). This mapping contains both the name of the automatically-generated FOV each user-proposed FOV maps onto as well as information regarding each FOV.

Using this mapping returned by `assign_closest_tiled_regions`, we can then pass it to a function called `compare_user_and_script_tiles`, which visualizes on the region space the location of each user-proposed FOV compared to its mapped automatically-generated FOV. The former will be visualized as a black circle and the latter will be visualized as a blue circle. Additional coloring may be needed to adjust for different FOV mapping pairs, different levels of agreement, etc.

This visualization will also contain a mechanism to remap user-proposed FOVs to automatically-generated FOVs. This will be in the form of a drop-down menu of the user-proposed FOVs and the automatically-generated FOVs. The latter will update automatically based on the user-proposed FOVs list. It is also possible to change the mapping by selecting a different automatically-generated FOV to map to a user-proposed FOV.

**Design list/flowchart**

![tma_update drawio (2)](https://user-images.githubusercontent.com/31424707/144292029-cabdc7e5-b7ca-46fa-a8bb-74874306dc77.png)

**Required inputs**

For this section, it is assumed that the user has already ran `create_tiled_regions`.

The user will need to specify an additional proposed JSON file of tiled regions they've created. An example JSON file should look like:

```
{
    'exportDateTime': '2021-11-24T21:14:01',
    'fovFormatVersion': '1.5',
    'fovs': [
     {
           'scanCount': 1,
           'centerPointMicrons': {'x': 400, 'y': 100},
           'timingChoice': 7,
           'frameSizePixels': {'width': 2048, 'height': 2048},
           'imagingPreset': {'preset': 'Normal',
           'aperture': '2',
           'displayName': 'Fine',
           'defaults': {'timingChoice': 7}},
           'sectionId': 8201,
           'slideId': 5931,
           'name': 'row100_col400',
           'timingDescription': '1 ms'
      },
      {
          'scanCount': 1,
          'centerPointMicrons': {'x': 100, 'y': 400},
          'timingChoice': 7,
          'frameSizePixels': {'width': 2048, 'height': 2048},
          'imagingPreset': {'preset': 'Normal',
          'aperture': '2',
          'displayName': 'Fine',
          'defaults': {'timingChoice': 7}},
          'sectionId': 8201,
          'slideId': 5931,
          'name': 'row400_col100',
          'timingDescription': '1 ms'
      },
      ...
      ]
}
```

Additionally, the user will need to specify the region they will be visualizing over. This will vary greatly depending on the slide used, but it should be a `.tiff` file of the desired slide to be tiled.

**Output files**

The output will be a visualization comparing the locations of each user-proposed FOV in the region along with its mapped automatically-generated FOV. A basic overlay might look like:

![tma_verification_viz drawio](https://user-images.githubusercontent.com/31424707/143314585-009fa691-7160-455e-bec1-02f2ec765383.png)

As with most visualizations in `ark`, it will be possible to save this if desired.

**Section 2: Implimentation details**

Once you have completed section 1, please tag the relevant parties and iterate on the initial design details until everyone is satisfied. Then, 
proceed to section 2

**Control flow**

Provide additional, more granular details (if necessary) about how the proposed coding logic will be put together

**Milestones and timeline**

List each of the major components of the project, and provide an estimated completion date for each one.

**Comment by ngreenwald** [comment]
This looks spot on. Couple comments. We'll want an easy way to tweak the mapping between automatic and user-generated FOVs, in case one or two of them are incorrect. Not sure exactly what this would look like, maybe a dropdown list of all the names in the user-generated jason, and a second list with all names in the automatic json, with the option to specify the mapping.

The region overlay will need to be read in as well. This is an actual picture of the slide that is captured by the instrument. We want the dots with the centroid locations to be plotted on the picture of the slide, to more easily assess visually that the correct mapping was generated.

**Comment by alex-l-kong** [comment]
> This looks spot on. Couple comments. We'll want an easy way to tweak the mapping between automatic and user-generated FOVs, in case one or two of them are incorrect. Not sure exactly what this would look like, maybe a dropdown list of all the names in the user-generated json, and a second list with all names in the automatic json, with the option to specify the mapping.
> 
> The region overlay will need to be read in as well. This is an actual picture of the slide that is captured by the instrument. We want the dots with the centroid locations to be plotted on the picture of the slide, to more easily assess visually that the correct mapping was generated.

Ok I'll update the design doc with this info.
