### ISSUE TITLE
Remove 'GoogleDrivePath' dead code

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#512]
**Is your feature request related to a problem? Please describe.**
We still have some old references to GoogleDrivePaths hanging around in the codebase. We should remove all of these, as they're not needed anymore

**Comment by srivarra** [comment]
@ngreenwald Should I also remove *Google File Stream* in the README.md?

**Comment by ngreenwald** [comment]
Yes, `google_drive_utils` can be completely removed. 
The readme is describing how to mount a google filestream directory like a normal directory, which is fine and can be left in. This is specifically to remove code that integrates with google drive directly in underlying functions
