### ISSUE TITLE
Remove Rplots.pdf from templates directory

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#519]
**Is your feature request related to a problem? Please describe.**
The current version of pixel clustering produces an Rplots file that gets saved in the templates directory. 
It looks like everything that is generated in R is saved here e.g.

![image](https://user-images.githubusercontent.com/13770365/164801690-761b4f0e-35a3-43fd-bdbf-d4bee19c6468.png)
![image](https://user-images.githubusercontent.com/13770365/164801719-23d8a68c-8ffa-4423-bfe1-9b8e95d47bc1.png)

**Describe the solution you'd like**
Turn off option to save these plots

**Comment by cliu72** [comment]
@alex-l-kong this can be a part of the file cleanup that we talked about

**Comment by camisowers** [comment]
The pdf is always produced by the ConsensusClusterPlus package used in `pixel_consensus_cluster.R`. Trying to adjust the output directory didn't work and removing the file within the [`som_utils.pixel_consensus_cluster()`](https://github.com/angelolab/ark-analysis/blob/ad6ccfc8b341442f5207878853dc0cfee5cdc4f1/ark/phenotyping/som_utils.py#L1253) function raises an error. 

I think the easiest option is to add `os.remove('Rplots.pdf')` to one of the notebook cells (section 3.1 or after).

Note that once the file is removed, the `pixel_consensus_cluster()` function can not be run again without raising an error or running pixel clustering again from the beginning of the notebook. Probably wouldn't need to run the function twice, but worth mentioning.

**Comment by camisowers** [comment]
Just double checked and deleting the file with os.remove() in the notebook cells (or manually with the gui) and rerunning pixel_consensus_cluster doesn't cause an issue.  Only deleting from within the function or in the corresponding R file raises the [MemoryError](https://github.com/angelolab/ark-analysis/blob/ad6ccfc8b341442f5207878853dc0cfee5cdc4f1/ark/phenotyping/som_utils.py#L1327). 

So if we add `os.remove('Rplots.pdf')` to the notebook there's no rerun issue. In fact, we can add it to the end of the same cell where the function is called.

**Comment by ngreenwald** [comment]
Can it be within the python function that calls the R function, at the very end of the python function?

**Comment by camisowers** [comment]
Turned out the the docker issue was getting in the way of my testing. 
Placing `os.remove('Rplots.pdf')` at the end of the python function is now working!
