### ISSUE TITLE
Allow loading of pixel overlays in photoshop

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#521]
**Is your feature request related to a problem? Please describe.**
The current `save_fov_images` function in the pixel clustering notebook saves the overlays as float64 images, which can't be loaded into photoshop. 

**Describe the solution you'd like**
Since these are all integers anyway that are getting coerced to floats, we should just save the images as ints

**Comment by cliu72** [comment]
Agree. @alex-l-kong should be an easy fix.
