### ISSUE TITLE
Defaults for location of cell_table

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#523]
**Is your feature request related to a problem? Please describe.**
The current cell clustering notebook requires the user to copy the cell table into the top-level directory. 

**Describe the solution you'd like**
Since most of the people using this notebook will have created the cell table using our pipeline, we can infer the location of both the cell table and the segmentation masks from the top-level segmentation directory. These can be modifiable in case the user didn't use our approach, but setting the default to segmentation_dir/cell_table_normalized and segmentation_dir/deepcell_output I think would make sense.

**Comment by cliu72** [comment]
Yup, I had brought this up previously in another comment awhile ago. Should be an easy fix @alex-l-kong
