### ISSUE TITLE
Clarify progress text during metaclustering

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#524]
**Is your feature request related to a problem? Please describe.**
The text that gets printed out during metaclustering isn't intuitive, as different steps seem to have the description

**Describe the solution you'd like**
It should be more clear what is happening at each step

**Additional context**
```
[1] "Reading cluster averaged data"
[1] "Running consensus clustering"
end fraction
clustered
clustered
clustered
clustered
clustered
clustered
clustered
clustered
clustered
clustered
clustered
clustered
clustered
clustered
clustered
clustered
clustered
clustered
clustered
clustered
clustered
clustered
clustered
clustered
clustered
clustered
clustered
clustered
clustered
[1] "Writing consensus clustering results"
[1] "# fovs clustered:"
[1] 10
[1] "# fovs clustered:"
[1] 20
[1] "# fovs clustered:"
[1] 30
[1] "Writing SOM to meta cluster mapping table"
Computing average channel expression across pixel meta clusters
Mapping meta cluster values onto average channel expression across pixel SOM clusters
```

**Comment by cliu72** [comment]
@alex-l-kong I think we had talked about using invisible() or something of that sort to clean-up the output

**Comment by alex-l-kong** [comment]
Yeah, I'd been kind of holding off on doing this until someone explicitly requested it, definitely something I can add.
