### ISSUE TITLE
File clean up after pixel clustering

### ISSUE THREAD

**Issue by cliu72** [angelolab/ark-analysis#531]
**Is your feature request related to a problem? Please describe.**
Clean up files after pixel clustering is done to save space

**Describe the solution you'd like**
Remove unwanted files (preprocessed, subsetted, clustered) after clustering is done. Remove marker columns from files in consensus directory.

**Comment by alex-l-kong** [comment]
I think the easiest way to do this is to put a house cleaning function at the end of each notebook. Alternatively, we could also do it within certain existing functions.

**Comment by ngreenwald** [comment]
Addressed with single directory of feather files
