### ISSUE TITLE
Parallelize pixel clustering

### ISSUE THREAD

**Issue by cliu72** [angelolab/ark-analysis#532]
**Is your feature request related to a problem? Please describe.**
Currently, most of the runtime in the pixel clustering pipeline is for preprocessing, assigning clusters after training, and re-assigning clusters after manual re-clustering.

**Describe the solution you'd like**
Parallelize these steps (probably multiprocessing). For these steps, each fov is independent of each other.

**Comment by alex-l-kong** [comment]
@ngreenwald on @cliu72's dataset, using `multiprocessing.Pool` and testing on `create_pixel_matrix`, here are our approximate benchmarks:

- 1 FOV process (current implementation): 140s
- 2 FOV processes in parallel: 95s
- 5 FOV processes in parallel: 65s
- 10 FOV processes in parallel: 60s

There's definitely diminishing margin of returns in adding more FOV processes, I like 5 (around a 50% speed up) but open to discussion on which value to default to (or if we want to allow the user to customize this).

**Comment by ngreenwald** [comment]
Sounds good, I think we can have it as a hidden arg that defaults to 5
