### ISSUE TITLE
Add option to run trained clustering pipeline

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#534]
**Is your feature request related to a problem? Please describe.**
The current notebooks are set up primarily for optimizing pixel and cell clustering parameters. However, we will likely eventually get to a point where people will want to run the same clustering pipeline and new data, without changing any of the parameters. For example, reviewer experiments with the same panel, or clustering a core panel that is conserved across projects

**Describe the solution you'd like**
We should add simplified version of the pipeline in a separate notebook that copies the relevant files (99.9 percentile values and SOM weights) from a pixel and cell clustering directory, and then runs the entire process on new data.

This could also be useful if people fine-tune clustering on a subset of their entire dataset, and then use this notebook to actually run it across the entire cohort.

**Comment by alex-l-kong** [comment]
Yeah, definitely a great addition to the clustering pipeline. It might be overkill for this issue, but we might want to look into a more programmatic way of handling the lifecycle of the pixel/cell clustering project (ex. MLFlow).
