### ISSUE TITLE
generate_pixel_cluster_mask is really slow

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#535]
**Is your feature request related to a problem? Please describe.**
This function is extremely slow.

**Describe the solution you'd like**
We should look and see if using alternative indexing, similar to what regionprops does, can lead to a performance speedup

**Comment by alex-l-kong** [comment]
Currently, I'm trying to work a solution that uses 1D indexing; 2D arrays are notorious for cache misses. I've timed it and we get a significant speed up (around 3-3.5x per FOV), just need to ensure correctness.

**Comment by ngreenwald** [comment]
Got it. I remember when we switched to tuple-based indexing in segmentation it also provided a massive speedup. Not sure if this works for reassignment as well or just for getting values out of the array, can you take a look and see how this compares in terms of performance?

https://github.com/angelolab/ark-analysis/blob/a84cf4d1289308c6bdd78cd2ca5857efefdaefd4/ark/segmentation/signal_extraction.py#L21

**Comment by alex-l-kong** [comment]
@ngreenwald sure, I'll do some timing analysis on my end and see which one ends up working faster.
