### ISSUE TITLE
Add argument to control number of flowsom clusters

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#540]
**Is your feature request related to a problem? Please describe.**
Currently there is no way for the user to control the number of flowsom clusters generated for a specific dataset

**Describe the solution you'd like**
Pass the parameter through to one of the top-level functions

**Comment by ngreenwald** [comment]
Alex, I tagged you the next couple pixel clustering issues I think are higher on the priority list

**Comment by alex-l-kong** [comment]
@ngreenwald to clarify, it is possible to pass `xdim` and `ydim` to both `train_pixel_som` and `train_cell_som`. `xdim * ydim` will indicate the number of FlowSOM clusters generated for a specific dataset.

Is this an issue simply to explicitly specify those parameters in the notebook call to those functions?

**Comment by ngreenwald** [comment]
Nope, didn't see that they were already in the function def
