### ISSUE TITLE
Split up `som_utils.py` into separate files for pixel and cell clustering

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#544]
**Is your feature request related to a problem? Please describe.**

`som_utils.py` is very large and should be refactored.

**Describe the solution you'd like**

At the very least, it would help to put the pixel clustering functions in `pixel_cluster_utils.py` and cell clustering functions in `cell_cluster_utils.py`.

**Comment by ngreenwald** [comment]
This is worth tackling now
