### ISSUE TITLE
compute_pixel_cluster_channel_avg kills the kernel

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#548]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
When running `apply_pixel_meta_cluster_remapping', the kernel often dies when re-computing the channel averages. Given that this is being computed across all of the FOVs, is this something that will be prohibitive for analyzing larger cohorts? It won't matter how much we subset if this calculation needs to be computed from all the underlying data?

**Comment by alex-l-kong** [comment]
@ngreenwald I'll be doing some memprofing on this one to see if there's a bottleneck in the way this is being computed.

**Comment by alex-l-kong** [comment]
@ngreenwald yeah, we do have a massive memory problem on our hand. I used the `pympler` memory profiler to check out each iteration of `compute_pixel_cluster_channel_avg` and here's what we're getting on Candace's dataset about 25 FOVs in:

<img width="386" alt="Screen Shot 2022-05-20 at 11 59 58 AM" src="https://user-images.githubusercontent.com/31424707/169594654-a38d39d4-1be2-4807-9b2d-edef1c027098.png">

It's understandable that the amount of `pandas.DataFrame` memory goes up per iteration: we are appending after all. However, there should not be this much memory usage: for a 10x10 SOM and 30 FOVs, there should only be at most 3000 rows of data, and we don't have any large blob objects or the like either. We do store a couple `groupby` objects and run a `merge` during the loop, but these shouldn't inherently increase the memory by this much, and unlike `cluster_avgs`, we don't append to either one of them.

Either way, this deserves a deep dive.
