### ISSUE TITLE
Grouping calprotectin and chymase together

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#549]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
This is the second time that cell clustering has grouped mast cells and neutrophils together; see bottom row. This was with 200 cell clusters
<img width="1734" alt="image" src="https://user-images.githubusercontent.com/13770365/168895621-7a7ff607-caa4-4bb8-89e6-bfa56b131ad4.png">

**Expected behavior**
These pixels are basically never co-expressed in the same cells. It must be that the similarity from all the other markers being zero is outweighing the positive signal?

**Comment by cliu72** [comment]
Hmm what I think is interesting about those two markers is that the z-scores don't get as low as the other markers. Like they are slightly white-ish and don't get as blue. I wonder if some pre-processing step to get them to "look like" the other markers might help. I think worst case, you can just manually gate the cells in those clusters by using cut-offs. Back in the day, Erin said she would do that for some of the cell types (like gamma deltas) when doing the clustering using integrated expression.

**Comment by cliu72** [comment]
How many neutrophil/mast cell pixels do you think there are? Maybe that's also a reason - there just aren't enough examples that the SOM is seeing (especially if you're subsetting)

**Comment by ngreenwald** [comment]
Yeah, there aren't a ton of cells, but you can see from the barchart that these aren't the rarest populations

**Comment by ngreenwald** [comment]
Interesting! However, the issue is popping up at the cell clustering step, not the pixel clustering step. Although its true that these cells would be defined by a single pixel cluster population, there are plenty of other cell types which are are also defined by a single pixel cluster population, and don't have this same issue

**Comment by ackagel** [comment]
Gotcha, I misunderstood.  Is there a breakdown of what pixel metaclusters are in this calproc+chym cell cluster?  The pixel metaclusters that pair with each marker could be smaller area fractions of their respective cell, compared to some common 'cell-background' cluster, which would motivate the clustering to 'two-for-one' them.

If that's the case, the row normalizing change could still help with this, but just applied at this step instead:
https://github.com/angelolab/ark-analysis/blob/521cf45d1a27e4622df4a46dbee5183a26b35ca3/ark/phenotyping/som_utils.py#L499-L500

where cell_size could be swapped out for the sqrt of the sum of squared pixel metacluster counts.
