### ISSUE TITLE
Update cell table with cluster IDs

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#551]
**Is your feature request related to a problem? Please describe.**
The current clustering pipeline produces a feather file with the pixel metacluster weights and cell metacluster assignments for each cell. However, this information is never added to the cell table generated from segmentation. 

**Describe the solution you'd like**
A final step that updates the cell table with cell label generated during the clustering process so that these labels can actually be used for downstream analysis

**Comment by alex-l-kong** [comment]
Just to clarify:

1. Should we just append the metacluster assignments, or also the SOM cluster assignments too?
2. For metacluster assignments, I assume we're thinking of the renamed ones that the user specifies during the interactive remapping widget?

**Comment by ngreenwald** [comment]
Yes, named metacluster values only
