### ISSUE TITLE
spatialLDA preprocessing user improvements

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#553]
**Is your feature request related to a problem? Please describe.**
The spatial LDA notebook requires the user to list all of the cluster IDs that will be included. We should have an option to take all of the cluster IDs, rather than requiring the user to list all of them
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/13770365/169385779-c364e811-8551-4c54-8002-c6beb8e1a9cf.png">

The name of the column containing the cluster IDs and cluster labels should be modifiable, and the defaults should be changed to match the pixel clustering output (cell_meta_cluster, cell_meta_cluster_rename)

We should ensure that clusters were specified if cluster featurization is selected, and that markers were specified if marker featurization is selected
<img width="765" alt="image" src="https://user-images.githubusercontent.com/13770365/169387185-40adece0-9e58-4935-858f-efcfa9622fc4.png">

Figure out if this is going to cause problems in the future. Either way, modify so we don't get the warning
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/13770365/169387892-040004c8-9dfd-4fed-828f-2ce0a7ddb591.png">

`fovs` argument in `visualize_difference_graphs` should be pulled out and defined in separate cell with guidance for user that it must be names of fovs. Should validate that these names are correct

**Comment by ngreenwald** [comment]
Defaults for kmeans output don't look great: 
<img width="703" alt="image" src="https://user-images.githubusercontent.com/13770365/169393588-86add8aa-03a5-4353-97e1-4372ba2fa076.png">

**Comment by ackagel** [comment]
made a pr for these issues as they crop up

**Comment by ackagel** [comment]
those warnings are on the spatial lda's end.  I'll silence them for now, but I'll look into if there's actually an issue and submit an issue/pr to callico's repo if so.

**Comment by ngreenwald** [comment]
closed by #437
