### ISSUE TITLE
Update SOM training to return only the SOM weights

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#568]
**Is your feature request related to a problem? Please describe.**
The current SOM function within FlowSOM both trains the SOM, and applies the trained SOM to the provided training data. However, this doubles the memory requirements of the function. Furthermore, we don't care about running the SOM on the provided data, since it is a subset of the whole dataset, which we batch process after the fact

**Describe the solution you'd like**
We should add an option to the SOM function to skip the [MapDataToCodes](https://github.com/SofieVG/FlowSOM/blob/31bf74c131e0c1bee2584a060e99ceff8b74b5af/R/2_buildSOM.R#L228). The easiest option would be getting this merged in to the main FlowSOM repo. Given that it's only a couple lines change, I think there's a decent chance it will get merged in. We should open a PR explaining our use case, why this is helpful, etc. 

However, in the interim, I think we can create a fork and make the changes ourselves, and then update the imports.

**Comment by alex-l-kong** [comment]
@ngreenwald ok, I just opened an issue on their end and will address it with a PR on the FlowSOM repo. I'll also work on forking it for internal usage.
