### ISSUE TITLE
Remove intermediate `pixel_mat_clustered`/`cell_mat_clustered` directory/file

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#571]
**Describe the solution you'd like**

`pixel_mat_clustered` contains the same data as `pixel_mat_consensus`, just without the meta cluster columns. Now that we're working with large datasets, we should not need to keep large duplicate datasets around.

We write to one `pixel_mat_consensus` directory with just the SOM labels at first. It will be much more intuitive to overwrite the old `.feather` files with the pixel data containing the meta cluster labels once that step is performed. This removes an additional variable from the notebook and also simplifies the directory structure prior to finalizing the pipeline for pixel and cell clustering.

**Comment by alex-l-kong** [comment]
@ngreenwald plan to get this finished up before opening the PRs for parallel processing and restarting from crashing since those two depend at least partially on the current directory structure, which the PR addressing this one will change.

**Comment by ngreenwald** [comment]
totally, makes sense
