### ISSUE TITLE
Add pixel and cell cluster metric evaluation statements/graphs

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#572]
**Is your feature request related to a problem? Please describe.**

There is currently no way in the pixel and cell clustering pipeline for a user to quantitatively evaluate how well the pixel and cell clusters are being assigned. While users can run interactive meta clustering, it would be useful to include some clustering metrics to display to the user indicating how confident they can be in the assignments.

**Comment by ngreenwald** [comment]
Without ground-truth annotations, I don't think we'll ever know how well the clustering worked. However, the GUI gives a qualitative sense for how accurate the output is
