### ISSUE TITLE
Add option to view and monitor pixel and cell clustering experiment history

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#573]
**Is your feature request related to a problem? Please describe.**

Possibly related to #534 and #572. Users are expected to run the pixel and cell clustering pipeline multiple times, possibly on the same dataset with different parameters. Currently, there is no tracking system in place to allow the user to verify the results of previous sets of parameters. We would like to make it easier for the user to verify the results of certain sets of parameters for possible resue.

**Describe the solution you'd like**

This ideally will happen in a separate notebook. We have a couple options:

- Save `experiment.csv` files in a hidden `.experiment` folder, and add interactive functionality to the Jupyter notebook to allow them to view the previous results of an experiment, with the parameter values, corresponding heatmaps, meta cluster remapping evaluation metrics, etc. We can programmatically create a dashboard from scratch or potentially utilize dashboard libraries such as `dash` to make this slightly easier.
- Alternatively, we could integrate our pipeline with machine learning lifecycle pipelines such as MLFlow. However, this is a much more involved option and maybe a bit overkill for the pixel and cell clustering pipeline.

**Comment by ngreenwald** [comment]
Closing for now until we have a more concrete request from users about what would be helpful
