### ISSUE TITLE
Allow pixel/cell clustering pipeline to restart from checkpoint in case of crash

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#575]
**Is your feature request related to a problem? Please describe.**

Testing of `example_pixel_clustering.ipynb` and `example_cell_clustering.ipynb` has revealed instances of crashing. If the user needs to restart Docker (ex. to increase memory), it would be inconvenient for them to have to re-run the whole pipeline (or at least one whole step) because of a crash during one component. We should add a way to restart the pipeline at that point in time.

**Describe the solution you'd like**

There are a couple of problematic scenarios I see this popping up where this will need to be addressed (potentially more to be added):

1. SOM training: this one could be the trickiest to implement, as the `SOM` function in `FlowSOM` does not currently support restarting from a checkpoint. This is a feature we may need to add in our local forked version of `FlowSOM` if desired. We can see if we can save a snapshot of the weights and the number of passes we've already computed.
2. Pixel clustering and consensus assignment: in this case, we should have a control statement in the assignment loop to prevent having to re-assign FOVs that have already been fully processed. We should also check to see if the weights in a particular run folder have been generated so we don't re-run the SOM training.

**Comment by ngreenwald** [comment]
I was just thinking the same thing. The SOM training is actually quite fast, and there's no intermediate progress that gets rewritten, so I don't think that one is a big issue. The main thing, as you mentioned, is the FOV-level processing. 

I think adding an `overwrite=True` argument to each of the batch processing functions to control what happens if the output file already exists would be a nice feature

**Comment by alex-l-kong** [comment]
@ngreenwald should we give users the option to provide the user an option to overwrite regardless of the state of the pixel/cell files/directories (ex. default `overwrite=False` argument, with option to set to `True`)? Let me know if there's an application you see this being useful.

**Comment by ngreenwald** [comment]
For the first pass we don't need to include that feature. If it turns out to be useful we can add it in.

**Comment by alex-l-kong** [comment]
@ngreenwald ok great. In that case I just need to spend time writing tests for the pixel clustering restart process and we should be good to go soon.

I think I'll hold off on adding the restart feature for cell clustering for now, since this process doesn't involve a lot of intermediate files and intense training/assignment.
