### ISSUE TITLE
Remove need for separate subset directory for pixel clustering

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#578]
**Is your feature request related to a problem? Please describe.**

Having to maintain a separate `pixel_mat_subsetted` folder adds unnecessary storage requirements to the pixel clustering pipeline for redundant data. For large cohorts, even a percentage of 10% can lead to millions of rows of duplicate data in the `pixel_mat_subsetted` folder. We should consider removing the need to maintain a separate subsetted dataset.

**Describe the solution you'd like**

There are a few ways around this:

1. We can keep the data in `pixel_mat_preprocessed` and instead store the random indices to take for each FOV. When we load the data in `create_pixel_som.R`, we can load the full preprocessed dataset in for the FOV, then use these indices to subset on the rows to take when creating `pixelSubsetData` that gets passed into `SOM`.
2. Alternatively, we can consider moving the subsetting step from `create_pixel_matrix` to `create_pixel_som.R`. When we create `pixelSubsetData`, we can use the `sample` function in `R` to achieve the same functionality. This method also removes the need to store the indices required in step 1.

**Comment by ngreenwald** [comment]
Now that we've removed the other extraneous feathers, this is much less of an issue
