### ISSUE TITLE
I am having problems to extract the single-cell data from the segmentation masks using the segmentation imaging data notebook

### ISSUE THREAD

**Issue by joaoufrj** [angelolab/ark-analysis#588]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a new issue*

**What are you trying to do?**
A clear and concise description of what script or function you're using
I had followed exactly all the instructions in the GitHub to use the Jupyter notebooks through Docker Hub. However, probably because I am using a MacBook with M1Pro chip, that has not been working. So I have created a conda environment, installed ark-analysis and all required packages to run the segmentation imaging data Jupyter notebooks locally. 
**What is the problem?**
A clear and concise description of what issue you're running into.
I can create the folders, the DeepCell input and run the DeepCell segmentation. However, when running several functions there is also an error of the type "got an unexpected keyword argument". I even tried to run the notebook with the example dataset and I have got the exact same error for all functions, as follows:
1- For the function data_utils.generate_deepcell_input: TypeError: generate_deepcell_input() got an unexpected keyword argument 'is_mibitiff'
2- For the function plot_utils.create_overlay: TypeError: create_overlay() got an unexpected keyword argument 'fov'
3- For the function segmentation_utils.save_segmentation_labels: TypeError: save_segmentation_labels() got an unexpected keyword argument 'segmentation_dir'
4- For the function marker_quantification.generate_cell_table: generate_cell_table() missing 1 required positional argument: 'segmentation_labels'
**What have you tried so far?**
A clear and concise description of what steps you've taken to try and address the problem.
I went through the API for each function and tested different options, even tried to just run the example dataset with the original notebook and still got the same errors. it seems it is something simple to fix but it seems I can't find a solution with the basic level of python knowledge I have.
**Additional context**
Add any other context or screenshots here.

**Comment by ngreenwald** [comment]
It sounds like you may be using an older version of the codebase, which doesn't have some of the new features. Can you follow the instructions in the readme for updating the github and try everything again?
