### ISSUE TITLE
Error when loading libraries in pixel clustering notebook

### ISSUE THREAD

**Issue by cliu72** [angelolab/ark-analysis#591]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
Error in loading libraries in pixel clustering notebook. Seems like something related to spatial LDA updates.

**To Reproduce**
Run the first cell of the pixel clustering notebook on master.

**Expected behavior**
Load the libraries.

**Screenshots**
![image](https://user-images.githubusercontent.com/11382352/172733141-89b9bdd0-0721-4157-87d6-9f6fc21af2f2.png)

**Comment by ngreenwald** [comment]
You'll need to get the updated docker image

**Comment by cliu72** [comment]
Oh got it.
