### ISSUE TITLE
Pixel data preprocessing - operand broadcast error

### ISSUE THREAD

**Issue by maharahim** [angelolab/ark-analysis#599]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
Running the pixel data preprocessing block of code in pixel clustering notebook, and getting an error
 "ValueError: operands could not be broadcast together with shapes (2048,2048,33) (1,1,35)"

**To Reproduce**
I ran this notebook over the weekend with no issues on my personal laptop, but didn't have sufficient docker space. Moved to desktop computer with increased space today. Updated code before rerunning, and now have an error in the pixel data preprocessing step. 

**Screenshots**
<img width="1244" alt="Screen Shot 2022-06-14 at 12 59 44 PM" src="https://user-images.githubusercontent.com/72824413/173683084-3e608e09-4e52-4b7b-a10b-a8a97c2d62e8.png">

**Comment by ngreenwald** [comment]
Can you delete the `channel_norm.feather` and `pixel_norm.feather` files that are in the clustering directory and try again?

**Comment by ngreenwald** [comment]
@alex-l-kong where are these norm values being stored right now? Is it experiment-specific?
If the user changes the channels that are included, will it try and load the old values?

**Comment by alex-l-kong** [comment]
@ngreenwald these are being placed in the `pixel_output_dir` the user specifies in `example_pixel_clustering.ipynb`.

Yeah, if the user specifies a different set of channels and the same `pixel_output_dir`, it's gonna load the same `channel_norm.feather` and `pixel_norm.feather` with the old channels. Should we add a check to overwrite these files in case a different set of channels is specified? Or should we tell the user to use a different `pixel_output_dir` if they want to run a separate experiment with different channels.

**Comment by ngreenwald** [comment]
Yeah, lets store it with the channel names and add a check to make sure it matches

**Comment by alex-l-kong** [comment]
@ngreenwald great. If the channels don't match, for now I'm going to print a notification to the user indicating we'll be overwriting the existing `channel_norm.feather` and `pixel_norm.feather`. Alternatively, we can throw a `ValueError` instead, but this would be pretty prohibitive if the user wants to use the same `pixel_output_dir`.

**Comment by ngreenwald** [comment]
Agreed, I think that makes the most sense

**Comment by whitneyt1** [comment]
hi! i'm getting the same `Value Error: operands could not be broadcast together with shapes (1024,1024,19) (1,1,20).`

![oppeanderror](https://user-images.githubusercontent.com/46573884/189761177-7dfc756c-57e8-44ca-a4c9-fb3208ab5e76.PNG)

I have confirmed that my channels are correctly named! 
![channels](https://user-images.githubusercontent.com/46573884/189761583-8e311b3e-28ff-44a5-b5ea-32e7b1851d07.PNG)

**Comment by alex-l-kong** [comment]
Looks like the FOV images (or just one of them) you specified contain one fewer channel than what you specified in your channels list. Can you verify for each FOV image that they contain 20 channels?

**Comment by whitneyt1** [comment]
@alex-l-kong I am so sorry! I got ahead of myself. I had CD14 in my list twice. I removed the duplicate, and things are running smoothly.

**Comment by maharahim** [comment]
I deleted channel_norm.feather but could not find  a pixel_norm.feather
file in the directory to delete. I reran and had the same issue. I created
a new directory and reran, and still am getting the same error.

**Comment by ngreenwald** [comment]
Will you make sure you're using the most up-to-date version of the repo? If you still get the same error when running a new directory, make sure you have all the channels named correctly. If none of that resolves it, can you print out what the keys are in the normalization dict and @alex-l-kong can help you troubleshoot further
