### ISSUE TITLE
Print updates while the SOM is training for pixel and cell clustering

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#600]
**Is your feature request related to a problem? Please describe.**

Opening issue here because we can't open an issue on our forked `FlowSOM` repo.

The SOM training function can take a long time to run, especially for pixel clustering. However, the `verbose` functionality in `SOM` still does not print out updates per training iteration.

For the user's sanity, and to conform to other deep learning libraries such as TensorFlow and PyTorch, we should add functionality to print the number of epochs/passes that have been computed.

**Describe the solution you'd like**

The change needs to be made in `FlowSOM/src/som.c`, where extra print statements needs to be added.

While the change in itself may be easy, transferring the change over to `ark-analysis` may be more difficult. We may be need to recompile the `som.c` function when building the `Docker`. This could involve a little more handiwork.

**Comment by ngreenwald** [comment]
Training is fast compared to the other steps. Since we only use one epoch, don't think this will be that useful.
