### ISSUE TITLE
json decode error when uploading to deepcell server

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#602]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
I'm getting a JSON decode error when uploading data to the deepcell server. I retried running the same FOVs, and got the error for a different zip file, so it's not a corrupted input. 

**To Reproduce**
TBD, currently hard to reproduce. I have the notebook on the MIBIAN open that was leading to the error message so you guys can take a look. 

**Expected behavior**

**Screenshots**
```
ecodeError                           Traceback (most recent call last)
<ipython-input-14-c0157cd31fa5> in <module>
----> 1 deepcell_service_utils.create_deepcell_output(deepcell_input_dir, deepcell_output_dir, fovs=fovs, scale=rescale_factor, zip_size=10)

/usr/local/lib/python3.6/site-packages/ark/utils/deepcell_service_utils.py in create_deepcell_output(deepcell_input_dir, deepcell_output_dir, fovs, suffix, host, job_type, scale, timeout, zip_size, parallel)
    141             executor.shutdown(wait=True)
    142     else:
--> 143         list(map(_zip_run_extract, fov_groups, range(len(fov_groups))))
    144 
    145 

/usr/local/lib/python3.6/site-packages/ark/utils/deepcell_service_utils.py in _zip_run_extract(fov_group, group_index)
    115         print('Uploading files to DeepCell server.')
    116         run_deepcell_direct(
--> 117             zip_path, deepcell_output_dir, host, job_type, scale, timeout
    118         )
    119 

/usr/local/lib/python3.6/site-packages/ark/utils/deepcell_service_utils.py in run_deepcell_direct(input_dir, output_dir, host, job_type, scale, timeout)
    179         upload_url,
    180         timeout=timeout,
--> 181         files=upload_fields
    182     ).json()
    183 

/usr/local/lib/python3.6/site-packages/requests/models.py in json(self, **kwargs)
    915                 raise RequestsJSONDecodeError(e.message)
    916             else:
--> 917                 raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    918 
    919     @property

JSONDecodeError: [Errno Expecting value] <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.17.10</center>
</body>
</html>
: 0
```

**Comment by ngreenwald** [comment]
Okay, it's happening even with files of size 5. And it appears to be completely random. As a temporary fix, it would be great if you could add on a try/except around the [json download step](https://github.com/angelolab/ark-analysis/blob/master/ark/utils/deepcell_service_utils.py#L187) @alex-l-kong. Or maybe there's built in functionality in the `requests` library to retry? Either way, trying that batch again would be great rather than just failing

**Comment by alex-l-kong** [comment]
Sure I'll take a look into this.

**Comment by alex-l-kong** [comment]
@ngreenwald are the errors being returned always 502 Bad Gateway? If so, is it possible it's not inherently a `json` issue, but rather a server issue?

Either way, it would be good to use a try-except clause around this statement. We can make use of the `Retry` module in `requests.packages.urllib.util.retry` to attempt multiple passes before officially failing.

**Comment by ngreenwald** [comment]
Yeah, so far it seems like bad gateway is always the underlying cause. So
maybe it's a timeout issue on the server side? Not sure
