### ISSUE TITLE
Change where channel_norm.feather and pixel_norm.feather are saved

### ISSUE THREAD

**Issue by cliu72** [angelolab/ark-analysis#610]
**Is your feature request related to a problem? Please describe.**
Related to https://github.com/angelolab/ark-analysis/pull/595, right now, the `channel_norm.feather` and `pixel_norm.feather` files are being saved to the top most directory (i.e. ../data/example_dataset). I think it would be better to save these to the specified pixel output directory (i.e. ../data/example_dataset/*_pixel_output_dir). Right now, if the user runs multiple pixel clustering runs, these files will be overwritten. Before the pull request linked above, these were being saved to *_pixel_mat_data within the output directory, which was causing the problem.

I think it would also be better to append the specified prefix to the beginning of these filenames, to be consistent with the other files. Related to this, `post_rowsum_chan_norm.feather` could also have the prefix.

**Describe the solution you'd like**
1. Save `channel_norm.feather` and `pixel_norm.feather` in the specified pixel output directory (but not the data directory inside of that output directory).
2. Append the prefix to those filenames.
3. Append the prefix to `post_rowsum_chan_norm.feather`.

**Comment by cliu72** [comment]
Yeah, like `post_rowsum_chan_norm.feather` is already being saved in the specified pixel output directory.

**Comment by alex-l-kong** [comment]
@cliu72 OK I can make this change.

**Comment by cliu72** [comment]
Thanks!
