### ISSUE TITLE
Color bar for metaclusteing GUI - 0 should always be white

### ISSUE THREAD

**Issue by cliu72** [angelolab/ark-analysis#614]
**Describe the bug**
The color in the heatmap and in the colorbar should always be white for a z-score of 0 (even when the user changes the max z-score). Doesn't seem to be the case currently.

**To Reproduce**
Run the metacluster GUI.

**Expected behavior**
Even when the user changes the max-zscore, a z-score of 0 should always be white.

**Screenshots**
![image](https://user-images.githubusercontent.com/11382352/175142102-a7af7a0e-6a9c-4051-b340-5a8d098a1214.png)

**Comment by alex-l-kong** [comment]
@cliu72 I suspect the issue seems to be in the underlying implementation of `zscore_norm.py`, which fails to properly calibrate the colorbar. I'll be gone next week but will start addressing this issue before I leave.

**Comment by alex-l-kong** [comment]
@cliu72 per our discussion today, after double checking my working branch was up-to-date with `master`, I'm still unable to replicate the z-score slider issue on the TB dataset with both the Python 3.6 and 3.7 Docker images.

@ngreenwald I think we touched on this during yesterday's standup, but just to clarify were you able to replicate this error on your end?

**Comment by ngreenwald** [comment]
Switching from 3.7 to 3.6 resolved the issue for me as well

**Comment by alex-l-kong** [comment]
@ngreenwald @cliu72 looking through the `matplotlib` issue tracker, there are a lot of open issues regarding color bar functionality as a result of a massive rework in the 3.5.x versions, so it's not just us. I've confirmed that this issue does not pop up using the 3.4.x versions.

I think the best way to resolve this is to pin our version at 3.4.x for now.
