### ISSUE TITLE
Add nuclear pixel filtering to clustering pipeline

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#619]
**Is your feature request related to a problem? Please describe.**
Sometimes markers will have background staining that we want to filter out for the clustering process. One way to accomplish this is using the subcellular localization of the marker. For markers which should only be in the nucleus, we remove non-nuclear signal. Conversely, for markers that should only be the cytoplasm/membrane, we filter out nuclear signal. 

**Describe the solution you'd like**
Add this function to the repo, with comments, tests, etc. 

```
from ark.utils.load_utils import load_imgs_from_tree, load_imgs_from_dir
from ark.utils.misc_utils import verify_same_elements
import skimage.io as io

def filter_with_nuclear_mask(fovs, tiff_dir, segmentation_dir, channel, img_sub_folder=None, exclude=True):
    # convert to path-compatible format
    if img_sub_folder is None:
        img_sub_folder = ''
        
    
    for fov in fovs:
        img = load_utils.load_imgs_from_tree(data_dir=tiff_dir, img_sub_folder=img_sub_folder,
                                             fovs=[fov], channels=[channel]).values[0, :, :, 0]
        seg_img = io.imread(os.path.join(segmentation_dir, fov + '_feature_1.tif'))[0, ...]
        
        if exclude:
            suffix = '_nuc_exclude.tiff'
            seg_mask = seg_img > 0
        else:
            suffix = '_nuc_include.tiff'
            seg_mask = seg_img == 0
            
        img[seg_mask] = 0
        io.imsave(os.path.join(tiff_dir, fov, img_sub_folder, channel + suffix), img, check_contrast=False)
```

**Comment by alex-l-kong** [comment]
@ngreenwald should this step be run before or after channel smoothing in the pixel clustering notebook?

**Comment by ngreenwald** [comment]
After

**Comment by alex-l-kong** [comment]
@ngreenwald do you expect users will need to run this filtering process for multiple channels, or is it fine to leave it as is (one channel at a time)?

**Comment by ngreenwald** [comment]
They may need to run a couple channels, but not all with the same `exclude` param, so I don't think we need to make this take in a list of channels
