### ISSUE TITLE
compute_pixel_cluster_channel_avg is prohibitively slow

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#622]
**Is your feature request related to a problem? Please describe.**
The `compute_pixel_cluster_channel_avg` function takes as long as the actual mapping of pixels. This isn't a big deal for small datasets, but for large datasets this single function takes almost 14 hours to run. 

**Describe the solution you'd like**
Given that the only point of this function is to create the weights for the heatmap, I think some aggressive downsampling for the number of FOVs that this average is computed from would work.

**Describe alternatives you've considered**
Is there different logic we could use to create this @cliu72? The same function gets called again in the metaclustering step, which doubles the amount of time devoted to this

**Comment by alex-l-kong** [comment]
@ngreenwald I'll also do some timing tests to see where the big bottlenecks are coming from.

**Comment by cliu72** [comment]
This function has a for loop through all the FOVs. Can't think of another way to do it if we want to read in all the data. Downsampling should be okay, we can do some tests to see how much the heatmaps change with different amounts of downsampling.

**Comment by ngreenwald** [comment]
Also, what is the reason that we need to compute this for pixel clusters, in addition to the pixel metaclusters?

In the consensus clustering we read in the computed cluster expression for each pixel cluster, update the labels to have the metaclusters, and then save it. Is there a scenario where people care about the expression in each cluster, rather than metacluster?

<img width="682" alt="image" src="https://user-images.githubusercontent.com/13770365/176242231-2e40e981-3d00-4861-9116-e3afb64b5073.png">
https://github.com/angelolab/ark-analysis/blob/3454c62f9fa9d6947ba732450e0d7299430261cf/ark/phenotyping/som_utils.py#L1336

**Comment by alex-l-kong** [comment]
> Also, what is the reason that we need to compute this for pixel clusters, in addition to the pixel metaclusters?
> 
> In the consensus clustering we read in the computed cluster expression for each pixel cluster, update the labels to have the metaclusters, and then save it. Is there a scenario where people care about the expression in each cluster, rather than metacluster?
> 
> <img alt="image" width="682" src="https://user-images.githubusercontent.com/13770365/176242231-2e40e981-3d00-4861-9116-e3afb64b5073.png">
> 
> https://github.com/angelolab/ark-analysis/blob/3454c62f9fa9d6947ba732450e0d7299430261cf/ark/phenotyping/som_utils.py#L1336

This is mostly done to ensure support for the metacluster remapping GUI, which requires data in the format of `pc_chan_avg_som_cluster_name` (channel expressions for each SOM cluster, with additional mapping to meta cluster).

I'm not sure if people will actually care about the SOM channel expression, since the desired results should be based on meta clusters. @cliu72 have there been any applications where people have preferred the results generated by the SOM clusters over the meta clusters?

**Comment by cliu72** [comment]
> > Also, what is the reason that we need to compute this for pixel clusters, in addition to the pixel metaclusters?
> > In the consensus clustering we read in the computed cluster expression for each pixel cluster, update the labels to have the metaclusters, and then save it. Is there a scenario where people care about the expression in each cluster, rather than metacluster?
> > <img alt="image" width="682" src="https://user-images.githubusercontent.com/13770365/176242231-2e40e981-3d00-4861-9116-e3afb64b5073.png">
> > https://github.com/angelolab/ark-analysis/blob/3454c62f9fa9d6947ba732450e0d7299430261cf/ark/phenotyping/som_utils.py#L1336
> 
> This is mostly done to ensure support for the metacluster remapping GUI, which requires data in the format of `pc_chan_avg_som_cluster_name` (channel expressions for each SOM cluster, with additional mapping to meta cluster).
> 
> I'm not sure if people will actually care about the SOM channel expression, since the desired results should be based on meta clusters. @cliu72 have there been any applications where people have preferred the results generated by the SOM clusters over the meta clusters?

I'm a little confused. Isn't the pixel SOM x marker expression values needed for the GUI (like you mentioned)? So this table needs to be created.

**Comment by alex-l-kong** [comment]
@cliu72 my bad, my question wasn't worded well. The remapping interface applies to meta clusters, just wondering out of curiosity how many applications you've seen where the user skips the remapping step completely due to relying on just the SOM labels.

In either case, agreed, I don't think it's possible to remove this `merge_asof` step because of the data format the remapping GUI takes. Additionally, the merge is being done on a DataFrame that's just 100 rows, so it isn't a massive computational step.

**Comment by alex-l-kong** [comment]
We can first try taking advantage of the method @ngreenwald and @camisowers researched in #751, where appending `pandas` dataframes to a list and concatenating outside the loop runs ≈5x faster. This might won't be enough of an optimization in itself but this could allow us to reduce the amount of downsampling needed.

**Comment by ngreenwald** [comment]
Agreed that it's worth updating, since it's a free speedup. However, the underlying issue is that the per-FOV function is very time intensive, so with lots of FOVs it takes forever. We'll also need to add in the downsampling ability

**Comment by alex-l-kong** [comment]
Having talked with @cliu72 I think all this change will entail is adding a new parameter like `subset_proportion` in `create_pixel_matrix` to `compute_pixel_cluster_channel_avg` and randomly sample each FOV pixel DataFrame prior to averaging, unless there's additional considerations to the sampling that need to be taken into account.

**Comment by ngreenwald** [comment]
Agreed, that's what I was thinking as well
