### ISSUE TITLE
Retry missing `fov_group` zip files in case of DeepCell response error

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#628]
**Is your feature request related to a problem? Please describe.**

The currently-open PR to address retrying in case of a bad DeepCell response assumes that this operation can be completed in `n` tries, printing an error if it doesn't. In the long term, what we want happening is to identify the `fov_groups` that don't have an associated `.zip` file, then re-run the call to Deepcell on those.

**Describe the solution you'd like**

This requires a few steps to complete:

1. Standardized naming conventions for `.zip` files. Currently, it's hard to associate which FOVs were placed in which `.zip` files without unzipping them. A more indicative name would be the easier solution.
2. Enclose the call to the Deepcell runner function in a loop, with a check to see if all the `.zip` files have been created (number will depend on the batch size). If not, then identify which `fov_groups` need to be resent, and remain in the loop. Otherwise, break.

**Comment by alex-l-kong** [comment]
Addressed by #605.

**Comment by ngreenwald** [comment]
@alex-l-kong it says in the description that the currently open PR (#605) **doesn't** address this issue. In addition, that PR has a detailed discussion of what a future PR would look like to address this. I appreciate you helping to clean up stale issues, but please make sure they're actually stale before closing them.
