### ISSUE TITLE
Overwriting feather files leads to occasional errors with large files

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#633]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
When overwriting a feather file that is sufficiently large, the file inconsistently gets corrupted, leading to errors. This does not happen for creating the file in the first place, only overwriting it. This error happens for both R and Python. 

As a first attempt at fixing this, I created a branch that automatically deletes the feather file immediately before resaving it: https://github.com/angelolab/ark-analysis/tree/delete_feather. However, this lead to issues with multi-processing, where it would (ocassionally, not all the time) lead to missing file errors. It seems that somehow this delete call is being processed before the file is read in. 

Maybe it will require some renaming in order to make sure this race condition doesn't crop up, though  I'm not sure how this is possible, since the delete line is within the same function that is being called in parallel.

**Comment by alex-l-kong** [comment]
@ngreenwald a starter solution could be to write these files to a separate folder with the prefix `_temp_{som/consensus/rename}`, then once everything is complete, delete the old folder and rename the `_temp` folder to the original. When deciding if a restart is needed, we can just check if the folder with the suffix exists, then which files exist in the and/or are not corrupted when deciding where to restart from.

**Comment by alex-l-kong** [comment]
Resolved by #620.
