### ISSUE TITLE
Latest tag is referencing the 3.6 version

### ISSUE THREAD

**Issue by cliu72** [angelolab/ark-analysis#634]
**Describe the bug**
The `latest` tag is referencing the 3.6 version, not 3.7, so "/usr/local/lib/python3.6" is still created. When importing modules, Python is looking inside of the python3.6 folder first (so the up-to-date code in python3.7 is not being imported). 

**To Reproduce**
Re-build the docker and import ark module.

**Expected behavior**
`latest` tag should reference 3.7 version.

**Comment by cliu72** [comment]
@srivarra I pulled the latest version on master just now, and ran "docker pull angelolab/ark-analysis:latest", but it looks like "/usr/local/lib/python3.6" is still created. Is there anything else I need to do to get the latest tag? Doesn't seem to be working for me.

![image](https://user-images.githubusercontent.com/11382352/186041531-fa9d9e3f-b58d-4cb8-8255-8275aa81ffcd.png)

**Comment by srivarra** [comment]
> @srivarra I pulled the latest version on master just now, and ran "docker pull angelolab/ark-analysis:latest", but it looks like "/usr/local/lib/python3.6" is still created. Is there anything else I need to do to get the latest tag? Doesn't seem to be working for me.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/11382352/186041531-fa9d9e3f-b58d-4cb8-8255-8275aa81ffcd.png)
> 
> 

Can you try the tag 'docker_test' and let me know if that solves it?

**Comment by cliu72** [comment]
Do you mean running ""docker pull angelolab/ark-analysis:docker_test" instead? I got this error message:
`Error response from daemon: manifest for angelolab/ark-analysis:docker_test not found: manifest unknown: manifest unknown`

**Comment by ngreenwald** [comment]
it's `docker-test`, not `docker_test`. 

Maybe we should just update the `start_docker.sh` script and the readme to point directly to the relevant versioned image instead of using latest?

https://www.howtogeek.com/devops/understanding-dockers-latest-tag/

**Comment by cliu72** [comment]
Running "docker pull angelolab/ark-analysis:docker-test" didn't fix the problem, but changing the tags in start_docker.sh worked.

**Comment by srivarra** [comment]
> Running "docker pull angelolab/ark-analysis:docker-test" didn't fix the problem, but changing the tags in start_docker.sh worked.

Great, I'll get a fix in.
