### ISSUE TITLE
Catch IOError, OSError exceptions for Feather files

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#635]
**Is your feature request related to a problem? Please describe.**

Feather files do not always get written consistently, which can cause errors when reading them back in. This will currently stop the whole process from running, which is highly inefficient for cohorts with 100s-1000s of FOVs.

**Describe the solution you'd like**

Use a `try`/`except` to catch `IOError`/`OSError`/related errors that pop up with `.feather` reading, which will print out the offending FOVs to the user, but continue the process. This is acceptable because the whole set of FOVs are not necessarily needed for consensus clustering and aggregate computations. In the off chance a good percentage of FOVs are failing, the user can decide themselves to stop the run.

**Comment by ngreenwald** [comment]
Is there anything left to do on this?

**Comment by alex-l-kong** [comment]
@ngreenwald nope, this should all be addressed in `som_utils.py`.
