### ISSUE TITLE
Add testing for R script files

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#637]
**Is your feature request related to a problem? Please describe.**

There currently isn't a system in place to test the functionality of the R scripts. This is cumbersome (see: testing for #575) because there's no good way to mock up the functionality in Python, especially because some R code now uses parallelization.

**Describe the solution you'd like**

This is unfortunately not available in a local `pytest` environment. However, we may be able to add another job called `r_test` in `.travis.yml` which handles this for us.

The library `testthat` will allow us to accomplish this. Here's a good starter describing the basic process: https://www.r-bloggers.com/2019/11/automated-testing-with-testthat-in-practice/.

This job will need to run the test script directly using Linux commands. We can likely use similar methods as with the `docker_deploy` job with `r_test`.

**Additional context**

This should be tested on the Python 3.7 Docker image.

Additionally, a refactor of the scripts is likely in order to ensure specific functionality can be tested.

**Comment by ngreenwald** [comment]
I think it's worth spending a day or so seeing if this is feasible. If it looks like it will be, then opening a design doc for what the restructuring would look like

**Comment by ngreenwald** [comment]
No longer necessary, we'll be transitioning to full python
