### ISSUE TITLE
load_utils functions do not raise warning when given negative values

### ISSUE THREAD

**Issue by camisowers** [angelolab/ark-analysis#645]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
When changing the load functions to keep a consistent data type, a value in the img array that used to get loaded in negative (when converted to int16) is now positive when staying an unsigned int.

**To Reproduce**
Extracting all channel intensity tiffs with replacement for the example bin file `fov-2-scan-1` in the repo creates a negative value in the image data array. When then using the `load_images_from_tree` function, there is no warning issued.

**Expected behavior**
When running the `load_images_from_tree` function, it should raise a warning.

**Comment by ngreenwald** [comment]
Why does this happen during extraction? Shouldn't this only happen for data being loaded?

**Comment by camisowers** [comment]
The old function produced new negative values when converting `int32` to `int16`, which is what was happening in my case. The updated functions which now maintains a consistent data type does not do this. 

No warning is issued because there are in fact no negative values in the data frame, as there should be.
