### ISSUE TITLE
`create_mantis_project` errors out when specifying segmentation path

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#663]
**Describe the bug**

When running `create_mantis_project` in either the pixel or cell clustering notebooks, the line to copy the segmentation file into the corresponding `fov` directory fails. This is because the path gets set incorrectly (https://github.com/angelolab/ark-analysis/blob/master/ark/utils/plot_utils.py#L463): `seg_dir` already contains the full relative path to the segmented images, so does not need to be prepended with `img_source_dir`.

**To Reproduce**

Run the final cell in each notebook to create the Mantis directory structure as is.

**Expected behavior**

The segmentation files (suffixed with `_feature_0.tif`) should be copied over correctly.

**Screenshots**

The error traceback is as follows:

<img width="1117" alt="Screen Shot 2022-08-19 at 1 34 11 PM" src="https://user-images.githubusercontent.com/31424707/185702911-a53af157-e349-45ef-b2c0-efa113fd6f66.png">

**Comment by ngreenwald** [comment]
Yeah, I found the bug as well. I fixed it in #658. I can't figure out why the tests aren't failing though. 
`img_source_dir` needs to be removed
 https://github.com/angelolab/ark-analysis/blob/master/ark/utils/plot_utils.py#L463
