### ISSUE TITLE
Address TODO visualizations in neighborhood analysis notebook

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#666]
**Is your feature request related to a problem? Please describe.**

We have a couple TODOs to add sample visualizations in the neighborhood analysis notebook involving visualizing certain features. These TODOs can be found under the `Visualize neighborhood properties` section.

This is especially important because the MIBI workshop is approaching soon, so our notebooks should not include any hanging TODOs.

**Describe the solution you'd like**

Add or use the necessary functions in `visualize.py` to accomplish this.

**Additional context**

We should decide whether we want to remove this section for the time being and address it later, or address this now.

**Comment by cliu72** [comment]
I addressed this in #668. I kept the overlay generation for neighborhoods vs cells as separate functions for now, we can talk about if we want to consolidate later.
