### ISSUE TITLE
Have just one mantis directory

### ISSUE THREAD

**Issue by cliu72** [angelolab/ark-analysis#669]
**Is your feature request related to a problem? Please describe.**
Right now, mantis directories are created at the end of the notebooks for pixel clustering, cell clustering, and neighborhood analysis. When generating a mantis directory, all the single-channel TIFs are copied, so right now, the data is being copied in all 3 of these places, which is inefficient.

**Describe the solution you'd like**
Have just one mantis directory (probably in the base directory), that will hold single-channel TIFs, pixel overlay, cell overlay, and neighborhood overlay. In Mantis, the user can choose which of these overlays they want to look at.

Also have an option for the user to add a prefix (or suffix) to the pixel/cell/neighborhood mask overlays, so that they can compare across different runs. I think it is a good idea to have as default, no prefix/suffix and the mask overlays are overwritten if one already exists in the directory. If the user chooses, they can add a prefix/suffix to the files (such as "run1_population_pixel_mask.tif", "run2_population_pixel_mask.tif", etc.), so these are written as separate files. The user can then choose which of these to view in Mantis for easy comparison.

**Comment by alex-l-kong** [comment]
Addressed by #668.

**Comment by ngreenwald** [comment]
Nope, it was mentioned there but this is separate

**Comment by ngreenwald** [comment]
This will require a design doc
