### ISSUE TITLE
Remove unused imports across Ark

### ISSUE THREAD

**Issue by srivarra** [angelolab/ark-analysis#677]
**Is your feature request related to a problem? Please describe.**
Unused imports across Ark pollute the namespace and can occupy some memory.

**Describe the solution you'd like**
Prune through every Python file in Ark and remove unused imports. IDEs like PyCharm and VS Code will gray out unused imports per file, and there are ways to remove them.

**Describe alternatives you've considered**
N/A

**Additional context**

This is a post workshop Issue.

**Comment by alex-l-kong** [comment]
On a related note, there are certain cases where we import an entire package but only end up using a few submodules there. Where possible, we should change imports like:

```
import XXX
```

to

```
from XXX import YYY
```
