### ISSUE TITLE
Phase out MIBItiff file support

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#686]
**Is your feature request related to a problem? Please describe.**

Because we run our own low-level processing pipeline, MIBItiffs will no longer be supported in our pipeline. We should remove any references to MIBItiff support in the notebooks and underlying modules.

**Describe the solution you'd like**

Remove options to set MIBItiff parameters or variables, and any chunks of code that relies on them.

**Comment by camisowers** [comment]
Should we leave in any utility functions like [load_imgs_from_mibitiff](https://github.com/angelolab/ark-analysis/blob/c1802e9d967ff821a7ffdcd920bcc6b58647183f/ark/utils/load_utils.py#L13) or the [tiff_utils file](https://github.com/angelolab/ark-analysis/blob/main/ark/utils/tiff_utils.py) on the off chance they may be used in the future, or just go ahead and remove all MIBItiff related code from the repo? @angelolab/computational_team

**Comment by ngreenwald** [comment]
I think leaving the utility functions makes sense in case in the future ionpath fixes the low-level processing and we're directly using their outputs

**Comment by camisowers** [comment]
Agreed. I will only remove the explicit MIBItiff mentions in the notebooks, so they will always use the underlying default `is_mibitiff=False` in the functions while not deleting any functionality.
