### ISSUE TITLE
Supposed file corruption during Pixel Clustering step 2.2: Assign pixel SOM clusters

### ISSUE THREAD

**Issue by sventrx** [angelolab/ark-analysis#688]
Dear ark team,

I was trying out the pixel clustering notebook out today and ran into an issue I don't know how to resolve.

After successfully training the pixel SOM (step 2.1), trying to run the next cell first gives the output "The data for FOV <fovname> has been corrupted, removing" for all FOVs in the fovs list, then proceeds to throw the key error "pixel_som_cluster", as there are no FOVs left to process.

I tried reinstalling the codebase and updating docker, rerunning the notebook, unfortunately to no avail.
I also checked all involved paths and couldn't find any issues there.

Do you guys have an idea where the issue may lie?
Thanks already for your help!

Best wishes,
Sven

![grafik](https://user-images.githubusercontent.com/93774912/188455398-6ff47aa8-39e4-49b3-a129-8322f8669264.png)
![grafik](https://user-images.githubusercontent.com/93774912/188455474-06d33f7b-78e4-4eef-8647-08717cbb8215.png)

**Comment by alex-l-kong** [comment]
@sventrx I'm assuming no errors were encountered during the `create_pixel_matrix` step.

After deleting your current `pixel_output_dir`, can you try changing the pixel SOM assignment cell to this:

```
som_utils.cluster_pixels(
    fovs,
    channels,
    base_dir,
    data_dir=pixel_data_dir,
    norm_vals_name=norm_vals_name,
    weights_name=pixel_weights_name,
    pc_chan_avg_som_cluster_name=pc_chan_avg_som_cluster_name,
    batch_size=1  # this is the new parameter being added
)
```

**Comment by alex-l-kong** [comment]
@sventrx I had another user encounter an error like this, their problem ended up being a multithreading issue with setting the number of cores. I'll link the issue I just opened here: #695. 

If you need to test a fix out immediately, you'll need to modify `ark/phenotyping/run_pixel_som.R` and `ark/phenotyping/pixel_consensus_cluster.R`. In the files mentioned, change the line `nCores <- parallel::detectCores() - 1` to a more reasonable value, such as `nCores <- {number of CPU cores on your machine / 2}`.

**Comment by jonhsussman** [comment]
I have encountered a similar error, however neither of the solutions mentioned was able to solve this problem. I am running it in a conda environment and it worked successfully with a small subset of markers, but upon increasing the number of markers for the pixel clustering, it is now stuck on this step. 

Do you happen to have any other suggests about what could cause this error in this case? 

![image](https://user-images.githubusercontent.com/43019314/190881650-2a05c2c8-9386-4d64-bc7d-b1bf6bcf1ce3.png)

**Comment by alex-l-kong** [comment]
@jonhsussman we recently updated our repo to include more detailed error messages in case of FOV processing errors, can you ensure you have the most recent changes by running `git pull`, then posting the error message after running the pipeline through again?

**Comment by jonhsussman** [comment]
After some further investigation, it seems like there may be some issues with some of our TIFF files specifically. We have now re-converted a single ome.tiff into the single channel TIFFs using bftools/bfconvert, which then suggested more strongly that there is an error in this process. 

So, I am wondering, what tool/command is the most appropriate in order to convert a single ome.tiff into the correct single file TIFFs that can be used as input to the pixel clustering pipeline? 

![image](https://user-images.githubusercontent.com/43019314/191074460-ad551d0d-26d2-431b-84e7-d6597ac8abcd.png)

**Comment by jonhsussman** [comment]
I ran it using the new files, and the current error message is below. Of note, perhaps I should mention that the preceding step, I initially received an error of: Error in ``SOM(data = as.matrix(pixelSubsetData, rlen = numPasses, xdim = xdim, : unused argument (map = FALSE`)`  but resolved this by removing the "map = FALSE" argument from the create_pixel_som.R. Although it ran successfully with the example dataset, I wonder if there could be a dependency issue here or other issue with the SOM step. 

Please let me know if you have any other thoughts here!

![image](https://user-images.githubusercontent.com/43019314/191133985-3bbcf174-aca4-411d-84be-664901b38feb.png)

**Comment by alex-l-kong** [comment]
@jonhsussman for the `SOM` error, I would say wait a bit until we get a new Docker image pushed. It seems like you may be using an older image which didn't implement the `map = FALSE` argument in the `SOM` function.

The `fovStatuses[i, 'status'] == 1` error is surprising, since that seems to imply the `fovStatuses` data frame being returned on your end doesn't contain the column `'status'` or is placing a `NULL` value there. I'm assuming you didn't run into this issue prior to the updates, can you try printing out `fovStatuses` and seeing what happening?

**Comment by jonhsussman** [comment]
Thanks for you reply here! Regarding the SOM function, I was not using
Docker, but instead using conda, and thus referencing a native version of R/
4.2.1. Did you modify the SOM function, and if so, are you able to provide
the most up-to-date version of the SOM function for implementation on
native R installation.

Thanks also for for your suggestion on the fovStatuses error. I will try
this shortly, but wanted to see if you has some information about the
correct SOM function for native R.

**Comment by jonhsussman** [comment]
As a brief update, this is the result of printing out fovStatuses, I'm not sure how best to interpret this: 

![image](https://user-images.githubusercontent.com/43019314/191392093-391a2d32-e734-49e3-90f2-8dec44dd6455.png)

**Comment by ngreenwald** [comment]
Hey @jonhsussman, if you look in the docker file you'll see that we're importing a forked version of Flowsom. 

Given the complexity of the dependencies for `ark`, we won't be able to offer troubleshooting help if you decide to go the conda route. Totally understand the appeal of having everything work from the terminal, but we moved towards the Docker model because of all the hard to track down issues that kept coming up.

**Comment by jonhsussman** [comment]
I managed to solve this problem by processing this step in batches, I am linking to the solution here so others can see if they encounter the same problem: 

https://github.com/SofieVG/FlowSOM/issues/54

**Comment by jonhsussman** [comment]
I wanted to get back to this to expand on it and list the direct solution here so it can be more easily referenced. It is clear that on large fovs, the existing code (Docker and conda alike) will crash at this `.C` step, I tailored the excellent solution above to the code at hand, and showed that in the file `run_pixel_som.R` the line `clusters <- FlowSOM:::MapDataToCodes(somWeights, as.matrix(fovPixelData))` can be directly replaced by the following: 

```
block_size = 100  # Can adjust 
nwdata = as.matrix(fovPixelData)
clusters = matrix(0.0, nrow(nwdata), 2)  # MapDataToCodes returns 2 columns
block_end = nrow(nwdata)
for (block_i in 0:((block_end-1) %/% block_size)) {
  i_start = 1 + block_i*block_size
  i_end = min((block_i+1)*block_size, block_end)
  cat(i_start, i_end, "\n")
  clusters[i_start:i_end,] = FlowSOM:::MapDataToCodes(somWeights, nwdata[i_start:i_end,])
}
```

The block_size can be adjusted, I found that 100 works well, taking an hour or so to complete which seemed reasonable. It probably can go up to 1,000,000 and might be much faster with a very large block, but I didn't have a good reason to test that.

**Comment by ngreenwald** [comment]
Hey @jonhsussman, thanks for following up! Can you confirm (if you haven't already) that this is only an issue, even on your end, with large FOVs? Maybe just taking a small crop (around 2k x 2k, which is what our default is) from one of your larger images and making sure it runs with our current pipeline? 

I just want to make sure there isn't some other error you've found with the pipeline in general, and that it really is specific to large images

**Comment by jonhsussman** [comment]
@ngreenwald That is correct, in fact this error never came up at all with one of our images that was only slightly smaller (but still very massive). And also ran just fine with the example images provided.

**Comment by ngreenwald** [comment]
Okay awesome, thanks!

**Comment by ngreenwald** [comment]
Hey @jonhsussman, just had our weekly meeting to discuss. Not sure what your bandwidth is, but if you're interested in contributing to the repository, we always welcome pull requests from collaborators! If not, no worries, we've added this to our todo list and we'll get the change merged in.

**Comment by jonhsussman** [comment]
I would be very happy to contribute to the repository! My bandwidth has
been very much reduced the last couple of weeks (which also explains my
delay here as I've had to turn away my attention), but I will get back to
this quite soon and start testing some of the solutions and contributing
pull requests.

**Comment by ngreenwald** [comment]
That's sounds great! No rush, totally understand that you have other responsibilities. We have some general guidelines here: https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html

This one is pretty straightforward, and you already have code solution which is great. The main thing is just to confirm that you get the exact same results for your new implementation compared to the base version. Generating some random vectors and passing them to both versions of the function, for example. We don't need to test the whole pixie pipeline, just that specific flowsom call.

**Comment by jonhsussman** [comment]
Thanks for the link and inclusion to the codes! Might take a week or
longer, but will keep you posted with updates herein
