### ISSUE TITLE
dos2unix fixes in launching start_docker.sh don't work when installing ark on windows

### ISSUE THREAD

**Issue by whitneyt1** [angelolab/ark-analysis#696]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
Hello! when launching `bash start_docker.sh` after following the directions on installing ark on windows (https://ark-analysis.readthedocs.io/en/latest/_rtd/windows_setup.html#) we receive the invalid carriage returns error, but the recommended wsl commands don't work. 
<img width="431" alt="errors_startdocker" src="https://user-images.githubusercontent.com/46573884/189202252-75e203cc-cc8d-495c-be0b-d05255e9242f.PNG">

our work around was downloading dos2unix from sourceforge (https://sourceforge.net/projects/dos2unix/) and entering `start <path/to/dos2unix.exe> <path/to/start_docker.sh>` and when we now run `bash start_docker.sh` we still receive the carriage returns error, but then jupyter notebook launches smoothly and we are able to access the notebooks.

<img width="662" alt="workingwitherror" src="https://user-images.githubusercontent.com/46573884/189203127-ff684114-3cb1-4dea-ade8-cd2a91be068a.PNG">

Sorry if this doesn't as a real bug! just wanted to let you know.

**Comment by alex-l-kong** [comment]
@whitneyt1 did you run `wsl sudo apt-get update`, then `wsl sudo apt-get upgrade`, in your Command Prompt prior to running `wsl sudo apt-get install dos2unix`?

I noticed that you tried running `sudo apt-get update` without the `wsl` command; this will only work if run in the Ubuntu terminal, not Command Prompt.

**Comment by whitneyt1** [comment]
hi @alex-l-kong 

yes! We tried `wsl sudo apt-get update` and `wsl sudo apt-get upgrade` My apologies. I scrolled up to find the errors and didn't include all of them :/ 

We also tried running `sudo apt-get update` then `upgrade` in the ubuntu terminal as well. 

<img width="327" alt="Screen Shot 2022-09-08 at 1 33 18 PM" src="https://user-images.githubusercontent.com/46573884/189220386-e5856d1e-5667-422f-838c-d51dbcb8be34.png">

**Comment by alex-l-kong** [comment]
@whitneyt1 can you run `lsb_release -a` in your Ubuntu terminal so I can see what version you have?

If you're using 20.04 (as recommended in the tutorial), sometimes you may need to allow explicit access to the `universe` repository where the `dos2unix` package resides:

- `sudo apt-apt-repository universe multiverse`
- `sudo apt-get update`
- `sudo apt-get upgrade`

**Comment by whitneyt1** [comment]
@alex-l-kong 

<img width="239" alt="Screen Shot 2022-09-08 at 1 46 38 PM" src="https://user-images.githubusercontent.com/46573884/189222672-037e8724-5ac4-4a34-b6f4-54d54d0d60aa.png">

<img width="372" alt="Screen Shot 2022-09-08 at 1 47 53 PM" src="https://user-images.githubusercontent.com/46573884/189222871-c47a9361-2bdf-4f58-a57c-2fe6e30804b4.png">

**Comment by alex-l-kong** [comment]
@whitneyt1 whoops, I had a typo. It should be `sudo apt-add-repository universe multiverse`.

**Comment by whitneyt1** [comment]
@alex-l-kong 
<img width="379" alt="Screen Shot 2022-09-08 at 1 58 12 PM" src="https://user-images.githubusercontent.com/46573884/189224657-8c85c00d-3630-42c0-8ac9-d9f4e90314bd.png">

**Comment by alex-l-kong** [comment]
Try `sudo add-apt-repository universe` and `sudo add-apt-repository multiverse` as separate comamnds.

**Comment by whitneyt1** [comment]
oops! sorry @alex-l-kong ! i'm pretty unfamiliar with terminal.

hmm it looks i'm having some connection issues. This is on the UCSF onsite wifi.

<img width="1032" alt="Screen Shot 2022-09-08 at 3 00 26 PM" src="https://user-images.githubusercontent.com/46573884/189233628-98bfc77c-d80b-4238-bb02-8d8191b0c2af.png">

**Comment by alex-l-kong** [comment]
Can you run the following: `ls /etc/apt/sources.list`? We may need to change the endpoint to the main server.

**Comment by whitneyt1** [comment]
<img width="281" alt="Screen Shot 2022-09-08 at 5 35 11 PM" src="https://user-images.githubusercontent.com/46573884/189248708-a28dc5ac-0853-4fdd-8d45-1645ef0bd3cc.png">

**Comment by alex-l-kong** [comment]
@whitneyt1 OK, let's do this:

- Run `cp /etc/apt/sources.list /etc/apt/sources.copy.list`
- Run `sudo sed -i 's|http://us.|http://|g' /etc/apt/sources.list`

After doing that see if the `sudo add-apt-repository` commands work.

**Comment by whitneyt1** [comment]
<img width="450" alt="Screen Shot 2022-09-09 at 10 23 13 AM" src="https://user-images.githubusercontent.com/46573884/189409090-c21d2ff3-e008-4ca3-8b8c-ccae91c0f4ac.png">

**Comment by alex-l-kong** [comment]
Ok great, try running `sudo apt-get install dos2unix` again.

**Comment by whitneyt1** [comment]
<img width="308" alt="Screen Shot 2022-09-09 at 2 39 32 PM" src="https://user-images.githubusercontent.com/46573884/189449589-ac401568-bbe4-4a32-9c3d-28810b962fbe.png">
@alex-l-kong

**Comment by alex-l-kong** [comment]
That's pretty strange, try running `cat /etc/apt/sources.list`, then `cat /etc/apt/sources.copy.list`. Let me verify which endpoints are being pointed to.

**Comment by whitneyt1** [comment]
<img width="307" alt="Screen Shot 2022-09-09 at 3 23 50 PM" src="https://user-images.githubusercontent.com/46573884/189453775-0c97c009-b3b4-442e-b31a-a548b96f85c5.png">

**Comment by alex-l-kong** [comment]
@whitneyt1 try running `sudo apt-get update` then `sudo apt-get upgrade`, then `sudo apt-get install dos2unix` again.

**Comment by whitneyt1** [comment]
<img width="584" alt="Screen Shot 2022-09-09 at 3 35 51 PM" src="https://user-images.githubusercontent.com/46573884/189454720-17b26af9-7286-4504-afc4-6ecc9f245fe0.png">

@alex-l-kong

**Comment by alex-l-kong** [comment]
@whitneyt1 it's a bit difficult at this point to diagnose what the problem is at this point without looking at the specific setup on your machine. Let's find a time sometime next week to meet up over Zoom to discuss this. What time works best?

**Comment by alex-l-kong** [comment]
Additionally, you may want to put in a ticket to UCSF IT about the issue. Looks like there may be some networking protocols preventing access to the repositories we need to download from.

**Comment by ngreenwald** [comment]
I agree, I think it'll be most productive if she works with UCSF IT. Getting specific dependencies installed on their windows machine is outside of what we can reasonably handle.

**Comment by whitneyt1** [comment]
Hi @alex-l-kong and @ngreenwald 
I think you're right! We figured out a work around, and I thought I'd post and issue in case others also had the same institution specific problems. Alex, if you want to zoom, we can 100% do that, but only if its beneficial to help you guys make this pipeline widely accessible! it would have taken us a long time to figure out the work around of downloading dos2unix directly and applying it to the script without out some outside help from somebody much more fluent in terminal related things. hehe. I'll talk to UCSF IT! Thank you for all your help!

**Comment by alex-l-kong** [comment]
@whitneyt1 I think it's worth holding off on Zoom for now until UCSF IT is finished addressing the issue. Let us know if any residual issues pop up after implementing their fix.
