### ISSUE TITLE
jupyterlab version causing unreadable notebook

### ISSUE THREAD

**Issue by jd-daniels** [angelolab/ark-analysis#700]
On the current version we were getting 'Unreadable Notebook' on 1_Segment_image_data.ipynb

<img width="507" alt="image" src="https://user-images.githubusercontent.com/12498354/189356158-d23e6d4a-4feb-4d82-879f-6d8a5fcad2dd.png">

We had to update jupyterlab inside the container to 3.4.6 in order for it to work...

Singularity> pip install jupyterlab==3.4.6

**Comment by alex-l-kong** [comment]
@jd-daniels can you restart your Docker container, run `pip list` inside it, and send me the output?

**Comment by alex-l-kong** [comment]
@jd-daniels any update on this?
