### ISSUE TITLE
Image size issue

### ISSUE THREAD

**Issue by benoberlton** [angelolab/ark-analysis#701]
I am wondering do I get this error because I have images with different fov sizes? 

Should I split up my fovs by size?

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/76409408/189739061-760a6bf6-4763-42a2-97c8-84066f899a6a.png">

**Comment by alex-l-kong** [comment]
@benoberlton you can split them up by size for now.

However, the call to `load_imgs_from_tree` should work on a dataset with varying image sizes by passing a `max_image_size` argument to it (in your case, 2048). Looks like there isn't a way currently to propagate this from `generate_deepcell_input`.

@ngreenwald is there a reason we don't have a similar `max_image_size` argument to `generate_deepcell_input`, or can we open a PR to add this in?

**Comment by ngreenwald** [comment]
We don't want to use that here because it will add zero adding around the small images, resulting in a segmentation mask with different dimensions compared to the underlying image data. However, batching this doesn't actually speed anything up. We can probably change the underlying logic to work just one FOV at a time.

**Comment by alex-l-kong** [comment]
Cool, I’ll start working on a PR to address this.

**Comment by benoberlton** [comment]
Alex's initial chnange was able to fix the issue in regards to the Deepcell inputs, but the same issue pops up a littl e bit later when extracting the segmented images

![image](https://user-images.githubusercontent.com/76409408/190281343-057f9a80-9c1d-433c-8bcc-10250742fad2.png)

**Comment by ngreenwald** [comment]
Yup, you're going to have the same problem throughout the `ark` pipeline. You should set the batch size to 1, which will resolve the issue.

**Comment by benoberlton** [comment]
Setting the batch size to 1 worked to solve this particular issue. 
Should I do anything in particular going through the rest of the notebooks in regards to the smaller fovs?

**Comment by alex-l-kong** [comment]
@benoberlton if you're running pixel clustering and cell clustering, you'll need to set `pixel_cluster_batch_size=1` and `cell_cluster_batch_size=1` for generating the pixel and cell masks, which happens toward the end of both notebooks.
