### ISSUE TITLE
Newest start_docker.sh file doesn't allow for local changes to code

### ISSUE THREAD

**Issue by cliu72** [angelolab/ark-analysis#703]
**Describe the bug**
After pulling the current codebase on main, I found that local changes to any of the scripts were not being updated in Docker (same problem I was having before, which was caused by the wrong docker tag in start_docker.sh). I rolled back a few commits and figured out the issue. 

In this commit https://github.com/angelolab/ark-analysis/commit/f3044e78d5b683dd7a06dbe08dc130baae7aecdb, the following line was removed from start_docker.sh (in 2 places):
`-v "$PWD/ark:/usr/local/lib/python3.7/site-packages/ark" \`

If I understand correctly, that mounts the codebase to docker so any local code changes are correctly propagated. I added that line back in (but changed it to python3.8) to the version of start_docker.sh currently on main, and it seemed to have solved the issue. Relevant code block looks like this:

```
if [ ! -z "$external" ]
  then
    docker run -it \
      -p $PORT:$PORT \
      -e JUPYTER_PORT=$PORT \
      -e JUPYTER_DIR=$JUPYTER_DIR \
      -v "$PWD/ark:/usr/local/lib/python3.8/site-packages/ark" \
      -v "$PWD/scripts:/scripts" \
      -v "$PWD/data:/data" \
      -v "$external:/data/external" \
      -v "$PWD/ark/phenotyping/create_pixel_som.R:/create_pixel_som.R" \
      -v "$PWD/ark/phenotyping/run_pixel_som.R:/run_pixel_som.R" \
      -v "$PWD/ark/phenotyping/pixel_consensus_cluster.R:/pixel_consensus_cluster.R" \
      -v "$PWD/ark/phenotyping/create_cell_som.R:/create_cell_som.R" \
      -v "$PWD/ark/phenotyping/run_cell_som.R:/run_cell_som.R" \
      -v "$PWD/ark/phenotyping/cell_consensus_cluster.R:/cell_consensus_cluster.R" \
      -v "$PWD/.toks:/home/.toks" \
      angelolab/ark-analysis:v0.4.1
  else
    docker run -it \
      -p $PORT:$PORT \
      -e JUPYTER_PORT=$PORT \
      -e JUPYTER_DIR=$JUPYTER_DIR \
      -v "$PWD/ark:/usr/local/lib/python3.8/site-packages/ark" \
      -v "$PWD/scripts:/scripts" \
      -v "$PWD/data:/data" \
      -v "$PWD/ark/phenotyping/create_pixel_som.R:/create_pixel_som.R" \
      -v "$PWD/ark/phenotyping/run_pixel_som.R:/run_pixel_som.R" \
      -v "$PWD/ark/phenotyping/pixel_consensus_cluster.R:/pixel_consensus_cluster.R" \
      -v "$PWD/ark/phenotyping/create_cell_som.R:/create_cell_som.R" \
      -v "$PWD/ark/phenotyping/run_cell_som.R:/run_cell_som.R" \
      -v "$PWD/ark/phenotyping/cell_consensus_cluster.R:/cell_consensus_cluster.R" \
      angelolab/ark-analysis:v0.4.1
fi
```
After doing this, any local changes I made to main were then properly propagated to Docker.

**Expected behavior**
I'm not sure why those lines were initially removed, but whatever the reason or if there is a better solution than the one I used, I think it is important for users to be able to make local edits to the code and have them reflected in Docker.

**To Reproduce**
Pull version of code on main and change any of the scripts. They are not reflected inside of Docker.

**Comment by cliu72** [comment]
Actually upon closer inspection, it's not even just that local changes are not propagated. It seems like the wrong version of the scripts are being mounted to Docker. I.e. after pulling from main and then starting the docker, the wrong scripts are mounted to Docker (seems like an old version). Again, adding those lines back into start_docker.sh seemed to fix the issue.

**Comment by ngreenwald** [comment]
@ackagel did this on purpose, it was a workaround to get the spatial scripts integrated. He's going to be updating it this week with his workaround. Will you make sure Candace tries it out to see that it works for her?

**Comment by ackagel** [comment]
The thinking was that we could just rebuild the docker to get the local changes installed, since Docker would cache the earlier, time consuming installation steps (i.e R and FlowSom installation).  But relying on Docker's cache seems inconsistent and unintuitive, even for more advanced users, so I'm changing the `start_docker.sh` script to install the local version of ark with a `-u` flag.

This took a bit more time than I expected since changes to the Dockerfile meant excruciatingly long build times, but I should have this out (at least in a PR) before the end of the day.

**Comment by cliu72** [comment]
Using this method, if a user makes changes to an ark script and then they reload the jupyter notebook they're working on, will those changes propagate? Or would the user need to stop the docker and then restart it to see those changes? I think that would get really annoying if we have to restart the docker every time some change was made.

**Comment by ackagel** [comment]
you should be able to make changes from within jupyter lab, by opening up a jupyter terminal and running `cd /opt/ark-analysis && pip install .`.  You'll need to restart the kernel in any notebooks you're running, but that's it in terms of restarting anything.

We can document that somewhere of course.

**Comment by dtebaykin** [comment]
Running into an issue while attempting pixel clustering script with the newest version of ARK:
<img width="1414" alt="Screen Shot 2022-09-19 at 4 34 40 PM" src="https://user-images.githubusercontent.com/8460227/191828918-b35bb9dd-a51b-47d6-9453-75b3eb85109f.png">

After a bit of debugging, this seems to be a docker issue: the version of pixel_cluster_utils.py that is in docker image is outdated and does not have ncores argument. 

Is it possible the pixel_cluster_utils.py file is missing when building the current docker image in start_docker.sh? It's using the older version from somewhere.

**Comment by cliu72** [comment]
@dtebaykin For now, try opening a terminal within Jupyter, then these two commands:
```
cd /opt/ark-analysis
pip install .
```

After doing that, you should pull the most recent version and this error should go away.

**Comment by cliu72** [comment]
@ackagel Adding the `-u` flag to start_docker.sh doesn't seem to be working (not using the most recent version of the code). When I open a terminal and use those two commands though, it works.

**Comment by ngreenwald** [comment]
In order to make sure this is working, I'd recommend making a breaking change to the codebase locally, and then make sure this shows up in the docker. I think the reason this slipped through testing was that it was hard to tell which changes were getting incorporated. Deleting a single line from one of the helper functions should be enough to make it clear what version is being used

**Comment by ngreenwald** [comment]
@ackagel any update on this?

**Comment by ackagel** [comment]
I'm pretty sure this isn't working because I forgot to make a new docker tag to point to this.  This should work with the 'local-updating' docker tag, but I'll make a new tag for 'v0.4.2', which should resolve the issue.

**Comment by ngreenwald** [comment]
@srivarra @alex-l-kong can one of you confirm that with the newest release this is no longer an issue?

**Comment by srivarra** [comment]
@ngreenwald I can confirm that running `./start_docker.sh -u` reinstalls `ark-analysis` with the local changes made. To test this I added a constant in the `settings.py` file and it was able to print in the notebooks. Is there anything else to look out for?

**Comment by ngreenwald** [comment]
Will you make a breaking change to some random function and then run the function?

**Comment by srivarra** [comment]
@ngreenwald Made a breaking change to `io_utils.py::validate_paths` where it returns the input immediately. It does indeed return out the paths. Can confirm that breaking function changes propagate from local code to the docker image..

**Comment by alex-l-kong** [comment]
@ngreenwald with the `v0.4.2` image I'm getting an error with the `arrow` library installation. 

<img width="516" alt="Screen Shot 2022-10-04 at 11 58 32 AM" src="https://user-images.githubusercontent.com/31424707/193903440-04ec2667-9705-41d7-b08b-c825c263b2a3.png">

This issue doesn't pop up with `v0.4.1`.

**Comment by srivarra** [comment]
I am running into Alex's issue as well.
