### ISSUE TITLE
datasets module doesn't seem to be installed

### ISSUE THREAD

**Issue by cliu72** [angelolab/ark-analysis#704]
**Describe the bug**
In the current version on main, requirements.txt definitely contains the datasets module. However, when I start Docker, it looks like python can't find the datasets module. Not sure where requirements.txt is supposed to be run, but it doesn't seem like datasets is being installed.

![image](https://user-images.githubusercontent.com/11382352/189792041-f6ee28c1-fcbc-470a-8937-60536303096b.png)

**Expected behavior**
Install datasets (not sure if it's a bigger problem with requirements.txt)

**To Reproduce**
Pull the current version on main, try "import datasets" in a jupyter notebook.

**Comment by srivarra** [comment]
@cliu72 Currently the Docker Image does not have the module installed. However if you can use it if you manually install it. Open a terminal in Jupyter Lab, type `bash` to start the bash shell. Then run `pip install datasets`. Let me know if that allows you to run that cell.

**Comment by cliu72** [comment]
Yup, I did that last night and it was fine, but just thought I'd open an issue for it to get installed on Docker. I'm also just curious - when does requirements.txt actually get run? I thought it was when docker is started but is that not the case?

**Comment by srivarra** [comment]
`requirements.txt` gets run during the building process of the docker image. The Docker Image itself isn't updated yet. That'll be done when there is a new release (which will happen once we get all the notebooks to work).

**Comment by cliu72** [comment]
Ah gotcha. So after the Docker image is updated will the users have to rebuild the image manually? Or do those updates happen automatically when they run "--update"?

**Comment by srivarra** [comment]
The `--update` flag is only for the notebooks themselves. When the Image is updated, it'll go ahead and fetch the version tagged in `start_docker.sh`.  https://github.com/angelolab/ark-analysis/blob/b4a23f9697adef8fb49b48706b03f64247b66b2a/start_docker.sh#L78

This will get changed to `v0.4.2`, and then Docker is smart enough to notice that you don't have `v0.4.2` installed, so it'll go ahead and download it.

**Comment by cliu72** [comment]
Ah got it. Thanks Sri!

**Comment by ngreenwald** [comment]
We should make a new release now, not wait until the rest of the notebooks are resolved. Having a broken image is a problem for new users, we should get it fixed since it's easy to make a patch

**Comment by ngreenwald** [comment]
The other issue with the change @ackagel made to the dockefile is that anytime we fix any bugs in the code, we need to release a new patch, since the updated code isn't incorporated (see the issue #708 ben raised)

I know other libraries have had compiled code that needs to be included in docker images, I think deepcell even had this same issue a while back. Will you all @angelolab/computational_team discuss at standup tomorrow other potential solutions? I think there's a way to separately copy relevant files in after the local directory is mounted, but I'm not sure.
