### ISSUE TITLE
Cell_Table produces 0 size 0 label rows

### ISSUE THREAD

**Issue by benoberlton** [angelolab/ark-analysis#708]
For each of my FOVs in my final cell_table there exist a large number of rows where I am just given a number of 0's 

![image](https://user-images.githubusercontent.com/76409408/190268273-c697f7bf-3b4b-4f49-81de-8ec2b124274a.png)

![image](https://user-images.githubusercontent.com/76409408/190268307-fb23d05d-7ba5-4b20-a206-b1a857756b72.png)

All of the actual data is still there in further rows, but the first ~1000 rows of each FOV just contain 0s

**Comment by srivarra** [comment]
@benoberlton We have a fix in for this issue. There will be a new Docker Image built soon.

**Comment by srivarra** [comment]
As we discussed, and it was solved by downloading ark-analysis within the docker image and installing it from the main branch. Closing for now.
