### ISSUE TITLE
Warn users about out of date ark-analysis

### ISSUE THREAD

**Issue by ackagel** [angelolab/ark-analysis#710]
## **Problem**
It isn't trivial for users to know when their local ark-analysis is out of date.

## **Solution**
`start_docker.sh` could check the commit hash on github's main branch, and compare it to the local installation.  If they differ, a warning message should appear to advise the user to update w/ `git pull` and `./start_docker.sh -u`.  We could expand this to also print a changelog of features they're missing out on. 

## **Alternatives**
I'm open to other ideas, but I think the only alternative is to just not do this at all and trust users to keep track of ark updates.

**Comment by ngreenwald** [comment]
I'm a bit more hesitant on this one. In general, packages will periodically make releases that update users, but unless you're using something fundamental like pip, you don't usually see warnings that things are out of date. 

That said, I could be persuaded given how frequently we're changing things and solving issues

**Comment by ngreenwald** [comment]
The readme now states the current version of the repo, which will help to guide users towards which one they're using
