### ISSUE TITLE
Change defaults in settings.py

### ISSUE THREAD

**Issue by cliu72** [angelolab/ark-analysis#712]
**Is your feature request related to a problem? Please describe.**
Some of the variables in settings.py are misaligned with what we usually use in our datasets/what the notebooks are generating. For example, `FOV_ID` is currently 'SampleID' - should probably be 'fov'. `KMEANS_CLUSTER` is currently 'cell_meta_cluster_rename' which doesn't make sense.

**Describe the solution you'd like**
Go through settings.py and set the defaults to match the example dataset/what we usually use.

**Additional context**
I tried to change some of these when I was updating the neighborhood notebooks but it broke a bunch of tests so I didn't bother. I don't think the tests should be checking for hard-coded variables - alas, when I reverted settings.py all the tests passed.

**Comment by ngreenwald** [comment]
Do you have a list of what you changed/reverted?

**Comment by cliu72** [comment]
I believe I tried to change `FOV_ID`, `CELL_TYPE`, `CLUSTER_ID`, and `KMEANS_CLUSTER`. Changing `FOV_ID` definitely messed with the tests, not sure if the others do as well.

**Comment by ngreenwald** [comment]
Got it. I agree, the point of the having these as global variables is that we should be able to change them when we want and have the changes propagate. Either way, makes sense to update them to be in line with the variable names we've settled on.

**Comment by cwalker8** [comment]
For pairwise spatial enrichment, changing cell_type to "cell_meta_cluster" in settings.py resolved naming issue.
