### ISSUE TITLE
Replace batching functionality of `ark` pipeline to per-FOV looping

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#720]
*This is for internal use only; if you'd like to open an issue or request a new feature, please open a bug or enhancement issue*

### Instructions
This document should be filled out prior to embarking on any project that will take more than a couple hours to complete. The goal is to make sure that everyone is on the same page for the functionality and requirements of new features. Therefore, it's important that this is detailed enough to catch any misunderstandings beforehand. For larger projects, it can be useful to first give a high-level sketch, and then go back and fill in the details. For smaller ones, filling the entire thing out at once can be sufficient.  

**Relevant background**

Several lab members have started running cohorts containing images of varying sizes, which will cause the calls to `load_imgs_from_tree` to fail. This is because the batching functionality defaults to loading 5 images into a fixed dimensional `xarray`; this batching does not provide any significant optimization because we eventually use a per-FOV loop anyways, so it should be removed.

**Design overview**

Any function that explicitly or implicitly relies on a `batch_size` argument will need to be modified so it only processes a single FOV and removes any loops over batches. Additionally, notebooks which make calls to these functions will need to be updated.

This only applies to functions where `batch_size` doesn't remove a per-FOV loop used later on. Functions that use batching for multiprocessing are exempt.

**Code mockup**

The functions needing modification are mostly self-contained. They are sorted by appearance on the pipeline and should be completed in this order:

- [X] Cell table generation (`marker_quantification.generate_cell_table`)
- [x] Pixel/cell cluster mask generation (these two can be addressed in one PR)
    - [x] `data_utils.generate_and_save_pixel_cluster_masks` and `data_utils.generate_pixel_cluster_mask`
    - [x] `data_utils.generate_and_save_cell_cluster_masks` and `data_utils.label_cells_by_cluster`
- [x] Post-cluster cell labeling and FOV saving (these can be addressed in one PR)
    - [x] `data_utils.create_mantis_project`
    - [x] `data_utils.save_fov_images`
    - [x] `data_utils.label_cells_by_cluster`
        - This will require refactoring of the neighborhood analysis notebook too
- [x] Spatial enrichment functions (these two can be addressed in one PR)
    - [x] `spatial_analysis.batch_channel_spatial_enrichment`
    - [x] `spatial_analysis.batch_cluster_spatial_enrichment`
        - This PR will also need to address what to do with `calculate_channel_spatial_enrichment` and `calculate_cluster_spatial_enrichment`, since they're not being used outside of the testing module.
- [ ] Neighborhood analysis
    - [ ] `spatial_analysis.create_neighborhood_matrix`
        - The neighborhood analysis notebook currently pre-computes all the distance matrices prior to running `create_neighborhood_matrix`. This will need to be updated so distance matrices can be computed in the per-FOV loop.
- [ ] Distance matrix computation
    - [ ] `spatial_analysis_utils.calc_dist_matrix`
        - After batching functionality of neighborhood analysis is removed, there's no need for this function to support a list of FOVs, so it can be condensed to single-FOV processing.
        - This function should now save a single `xarray` as opposed to a dictionary of them
    - [ ] `spatial_analysis.calculate_channel_spatial_enrichment` and `spatial_analysis.calculate_cluster_spatial_enrichment`
        - These need to be refactored so they take in a single distance matrix and a single FOV to subset on

**Required inputs**

`batch_size` will no longer be supported as an argument to these functions. Any argument requiring a `fovs` list will be changed to requiring a `fov` variable, a single string defining which FOV to process.

The other inputs will remain constant.

**Output files**

Same outputs as usual.

**Timeline**
Give a rough estimate for how long you think the project will take. In general, it's better to be too conservative rather than too optimistic. 
- [ ] A couple days
- [ ] A week
- [X] Multiple weeks. For large projects, make sure to agree on a plan that isn't just a single monster PR at the end. 

Estimated date when a fully implemented version will be ready for review:

The cell table, mask generation, and post cluster utils PRs each should take 2-3 days.

Budgeting 3-4 days each for the spatial enrichment functions, neighborhood analysis, and distance matrix computation in case we need further discussion over the current setup.

Estimated date when the finalized project will be merged in: 

Aiming to have all these PRs merged in no more than 3 1/2 weeks from today.

**Comment by alex-l-kong** [comment]
@ngreenwald let me know if this looks good.

**Comment by ngreenwald** [comment]
Looks good!

**Comment by alex-l-kong** [comment]
Updated the issue to include single-FOV support of `save_fov_images` and `label_cells_by_cluster`.

**Comment by alex-l-kong** [comment]
Refactoring `calc_dist_matrix` to not take in a list of FOVs will be a more involved issue due to its usage in all the spatial functions. This should be handled as a separate issue from unbatching neighborhood analysis, updating timeline to add 2-3 more days for this.
