### ISSUE TITLE
DeepCell visualization introduces negative objects in Mantis Viewer

### ISSUE THREAD

**Issue by sguldberg** [angelolab/ark-analysis#743]
When running cell segmentation using the most up to date segmentation notebook on either the example dataset or my own FOVs, 
 inputting the feature 0 tif is having an issue on Mantis Viewer with negative objects (see attached images for both the example dataset and 1 of my FOVs). I also attached the feature0 tif and segmentation borders by themselves from my FOV for reference. Feature0 files generated from older notebooks don't introduce the lines/negative objects seen on Mantis Viewer.
<img width="948" alt="Screen Shot 2022-10-04 at 11 15 55 AM" src="https://user-images.githubusercontent.com/56889968/193919296-c9d02e44-ad4e-42e7-97ce-8d7ad6e25922.png">
<img width="1541" alt="Screen Shot 2022-10-04 at 12 14 48 PM" src="https://user-images.githubusercontent.com/56889968/193919362-d7a267e8-27e5-49fe-aec2-8e3cf8fa937a.png">
<img width="1004" alt="Screen Shot 2022-10-04 at 11 17 13 AM" src="https://user-images.githubusercontent.com/56889968/193920160-600bb776-2541-44f9-813c-ae25ca27d377.png">

<img width="1007" alt="Screen Shot 2022-10-04 at 1 26 07 PM" src="https://user-images.githubusercontent.com/56889968/193919727-755a7471-209a-448e-8bd5-0c565d931783.png">

**Comment by ngreenwald** [comment]
Hey @sguldberg, I believe this is addressed in the new release we put out yesterday. You should be able to re-run the notebook after following the instructions in the readme to update and not have the negative cells.

**Comment by sguldberg** [comment]
Yup updating the notebooks fixed this issue. Thanks!
