### ISSUE TITLE
Give feature_0 and feature_1 files more informative names

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#745]
**Is your feature request related to a problem? Please describe.**
The current pipeline produces tifs that are named feature_0 and feature_1, which are not informative

**Describe the solution you'd like**
We should rename these with more informative names, reflecting the fact that they are cell and nuclear segmentation

**Comment by alex-l-kong** [comment]
Per lab meeting we agreed to rename `feature_0` to `whole_cell` and `feature_1` to `nuclear`.
