### ISSUE TITLE
readthedocs default landing page is out of date

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#750]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
The link at the top of the readme for documentation points to readthedocs/latest. However, this tag doesn't have the most up to date information. Instead, if you go to the left sidebar and switch to `stable`, this does have the changes we've made recently. I'm not sure if this is a legacy from the old 'latest' tag with docker issue, or something else. However, either way, we should update readthedocs so the default is pointing to the most up-to-date version of the documentation

**Comment by alex-l-kong** [comment]
@ngreenwald the issue is that `latest` is currently set to the `master` branch, this needs to be changed to `main`. Will it be possible to update that on your end?

**Comment by ngreenwald** [comment]
Sure, just tell me what I need to change

**Comment by ngreenwald** [comment]
Found it, thanks
