### ISSUE TITLE
Figure out optimal performance for merging large dataframes

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#751]
**Is your feature request related to a problem? Please describe.**
The current segmentation generation code is fairly slow. This is likely because of the underlying computations required to extract the single cell statistics. However, it's also possible we're not properly optimizing how we combine many dataframes together. For example, in `generate_cell_table`, we have a for loop over each FOV which progressively appends each new dataframe to the existing one. For my cohort, the end result is a 10GB csv file, and creating this is quite slow. 

**Describe the solution you'd like**
It's possible we're not taking advantage of best practices for large scale concatentation. e.g. https://stackoverflow.com/a/36489724 and https://www.terality.com/post/pandas-concat-vs-append. This is also now an issue in the new fiber segmentation notebook, specifically 'run_fiber_segmentation`.  We should figure out what the optimal method is for vertical combination of DFs, and make sure we're using it.

**Comment by camisowers** [comment]
Ran some basic time tests with `generate_cell_table`. Adding new dataframes to a list and then concatenating outside of the for loop is 5 times faster than using pd.append() inside the loop. 
We should make sure we are not directly appending anywhere else.
