### ISSUE TITLE
Add mixing score analysis

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#756]
**Is your feature request related to a problem? Please describe.**
The mixing score analysis from Leeat's paper would be broadly useful to have. The implementation should allow the user to specify any two populations, and compute the degree of mixing. Potentially also changing how the denominator is calculated. We'll need to discuss the specific details with Erin and Mike before making a design doc, some flexibility in how the ratio is calculated

**Comment by camisowers** [comment]
One approach to explore is how the SPIAT repo implemented the mixing score concept in R. They have generalized it to allow for the calculation of any two cell phenotypes while also adding a normalization component. 

https://github.com/TrigosTeam/SPIAT/blob/main/R/mixing_score_summary.R
https://www.biorxiv.org/content/10.1101/2020.05.28.122614

**Comment by ngreenwald** [comment]
Summary for next pipeline meeting: What is the math that Leeat/Erin implemented before. What are alternative ratios that we can consider? What are alternative ways of constructing the numerator and denominator of the ratio. e.g. number of interactions, number of cells with at least 1 interaction, distance to nearest interaction, etc
