### ISSUE TITLE
Jupyter Notebook Testing Improvements

### ISSUE THREAD

**Issue by srivarra** [angelolab/ark-analysis#765]
*This is for internal use only; if you'd like to open an issue or request a new feature, please open a bug or enhancement issue*

### Instructions
This document should be filled out prior to embarking on any project that will take more than a couple hours to complete. The goal is to make sure that everyone is on the same page for the functionality and requirements of new features. Therefore, it's important that this is detailed enough to catch any misunderstandings beforehand. For larger projects, it can be useful to first give a high-level sketch, and then go back and fill in the details. For smaller ones, filling the entire thing out at once can be sufficient.  

**Relevant background**

The Jupyter Notebook tests are currently rather inflexible and complex. It makes adjusting the notebooks themselves quite difficult as the tests also need to be updated in conjunction.

**Design overview**

Utilize a class based testing [implementation](https://github.com/angelolab/ark-analysis/discussions/738#discussioncomment-3766825) with one class per notebook. `pytest` has special `_setup()` functions which behave like `__init__()` methods in regular python classes, therefore we can setup any variables necessary for each notebook (like precomputed data, etc...). For each class we should have a function per tagged Jupyter Notebook cell, which runs that cell.

If we utilize [`pytest-order`](https://github.com/pytest-dev/pytest-order) we can order the tests the same way as the user would run the cells.

In addition we can create a temporary path utilized by the all the notebook tests, so all of their outputs can be sent there, and discarded once the tests are finished.

Here are some guidelines:

1. We should test the jupyter notebooks for completeness (i.e. the notebooks run without crashing / halting)
2. Only create a small testing dataset if necessary.
3. Use `testbook.inject` sparingly

**Code mockup**

```python
import pytest
from testbook import testbook
from typing import Iterator
import pathlib
import os

# Sets the notebook testing session directory. Saves all notebook related files
# in a temporary directory.

@pytest.fixture(scope="session")
def base_dir_generator(tmp_path_factory) -> Iterator[pathlib.Path]:
    """
    A Fixture which creates the directory where the all notebook test inputs and outputs are
    saved.
    Sets the path once for all notebook related tests.

    Args:
        tmp_path_factory (pytest.TempPathFactory): Factory for temporary directories under the
            common base temp directory.

    Yields:
        Iterator[pathlib.Path]: The iterable path containing the path of the `notebook_tests`
        inputs and outputs.
    """
    notebook_test_output_dir = tmp_path_factory.mktemp("notebook_tests")
    yield notebook_test_output_dir

SEGMENT_IMAGE_DATA_PATH = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                                       '..', '..', 'templates', '1_Segment_Image_Data.ipynb')

@testbook(SEGMENT_IMAGE_DATA_PATH, timeout=60000, execute=False)
class Test_1_Segment_Image_Data(tb, base_dir_generator):
    @pytest.fixture(autouse=True)
    def _setup(self):
        """
        Sets up necessary data and paths to run the notebooks.
        """
        # Create any simulated / fake / testing data necessary here
        self._image_data = ... # Create the tiffs
        self._paths = ... # Set any paths relative to the `setup_temp_path_factory` (a.k.a base_dir)

    @pytest.mark.order(0)
    def test_imports(self):
        self.tb.execute_cell("import")
    
    @pytest.mark.order(1)
    def test_create_dirs(self):
        self.tb.execute_cell("create_dirs")
    
    # Skip downloading the example dataset cell
    @pytest.mark.skip(reason="Either don't download the example dataset (therefore generating all data necessary), or create a small dataset used only for notebook testing.")
    @pytest.mark.order(2)
    def test_download_example_dataset(self):
        self.tb.execute_cell("download_dataset")
    
    @pytest.mark.order(3)
    def test_validate_path(self):
        self.tb.execute_cell("validate_path")

    # Here we run a cell, and then test the value of on a object in that cell.
    @pytest.mark.order(4)
    def test_load_fovs(self):
        self.tb.execute_cell("load_fovs")
        
        nb_fovs = tb.ref("fovs")
        expected_fovs = ["fov0", "fov1", "fov2"]
        assert set(nb_fovs) == set(expected_fovs)

    ...

    # Here we run a cell and then test STDOUT. This runs the `create_deepcell_output` cell
    # Test to make sure that the output is printing
    @pytest.mark.order(5)
    def test_create_output(self):
        self.tb.execute_cell("create_output")

        assert "Extracting tif files from DeepCell response" in tb.cell_output_text

```

**Required inputs**

* A *temporary directory* to get all the notebook outputs in one place.
  * Including creating any data used by the notebooks.
* Each notebook should have appropriately tagged cells.

**Output files**

* All output files should output to the *temporary directory*, there are no outputs otherwise.

**Timeline**
Give a rough estimate for how long you think the project will take. In general, it's better to be too conservative rather than too optimistic. 

About 1 week.

Estimated date when a fully implemented version will be ready for review: 10/28, post example dataset PRs.

Estimated date when the finalized project will be merged in: 10/31.

**Comment by srivarra** [comment]
@ngreenwald

**Comment by ngreenwald** [comment]
Great, lets discuss today at standup

**Comment by ngreenwald** [comment]
Before getting started on this, I think it would be useful to decide which code that injects/tests a particular cell should be kept and migrated over to this framework, and which should be removed. Given that our goal is only to do integration testing in the noteobooks, there will likely be some cells whose custom code can be deleted, but others where we think it's worthwhile. Before going to the trouble of porting over (or not) each of those, lets put together a proposed list for each category.

**Comment by srivarra** [comment]
## 1 - Segment Image Data

| **Tagged Cell**       | **Inject \(Y/N\)** | **Injection Variable / Function** | **Skip \(Y/N\)** |
|-----------------------|--------------------|-----------------------------------|------------------|
| import                | N                  | N/A                               | N                |
| file\_path            | Y                  | base\_dir \(V\)                   | N                |
| create\_dirs          | N                  | N/A                               | N                |
| get\_example\_dataset | Y                  | create test fovs \(F\)            | N                |
| validate\_path        | N                  | N/A                               | N                |
| load\_fovs            | Y                  | fovs \(V\)                        | N                |
| nuc\_mem\_set         | Y                  | nucs, mems \(V\)                  | N                |
| gen\_input            | N                  | N/A                               | N                |
| seg\_scale\_set       | N                  | N/A                               | N                |
| create\_output        | Y                  | save segmented masks \(F\)        | N                |
| overlay\_mask         | Y                  | simulate deepcell output \(F\)    | N                |
| save\_mask            | N                  | N/A                               | N                |
| nuc\_props\_set       | N                  | N/A                               | N                |
| create\_exp\_mat      | N                  | N/A                               | N                |
| save\_exp\_mat        | N                  | N/A                               | N                |


## 2 - Cluster Pixels


| **Tagged Cell**           | **Inject \(Y/N\)** | **Injection Variable / Function**                  | **Skip \(Y/N\)** |
|---------------------------|--------------------|----------------------------------------------------|------------------|
| import                    | N                  | N/A                                                | N                |
| file\_path                | Y                  | base\_dir \(V\)                                    | N                |
| get\_example\_dataset     | Y                  | create test fovs \(F\)                             | N                |
| load\_fovs                | Y                  | fovs \(V\)                                         | N                |
| pixel\_prefix             | N                  | N/A                                                | N                |
| dir\_set                  | N                  | N/A                                                | N                |
| smooth\_channels          | N                  | N/A                                                | N                |
| filter\_channels          | N                  | N/A                                                | N                |
| channel\_set              | Y                  | channels \(V\)                                     | N                |
| gen\_pixel\_mat           | N                  | N/A                                                | N                |
| pixel\_som\_path\_set     | N                  | N/A                                                | N                |
| train\_pixel\_som         | Y                  | train\_pixel\_som \(F\)                            | N                |
| cluster\_pixel\_mat       | Y                  | cluster\_pixels \(F\)                              | N                |
| pixel\_consensus\_cluster | Y                  | pixel\_concensus\_cluster \(F\)                    | N                |
| pixel\_interactive        | N                  | N/A                                                | N                |
| pixel\_apply\_remap       | Y                  | create `pixel_meta_cluster_mapping.csv` \(V\) | N                     |
| pixel\_cmap\_gen          | N                  | N/A                                                | N                |
| pixel\_overlay\_fovs      | N                  | N/A                                                | N                |
| pixel\_mask\_gen\_save    | N                  | N/A                                                | N                |
| cell\_param\_save         | N                  | N/A                                                | N                |
| pixel\_mantis\_project    | N                  | N/A                                                | N                |


## 3 - Cluster Cells

| **Tagged Cell**          | **Inject \(Y/N\)** | **Injection Variable / Function**                 | **Skip \(Y/N\)** |
|--------------------------|--------------------|---------------------------------------------------|------------------|
| import                   | N                  | N/A                                               | N                |
| dir\_set                 | N                  | N/A                                               | N                |
| get\_example\_dataset    | Y                  | create test fovs \(F\)                            | N                |
| param\_load              | N                  | N/A                                               | N                |
| cluster\_prefix          | N                  | N/A                                               | N                |
| cell\_cluster\_files     | N                  | N/A                                               | N                |
| train\_cell\_som         | Y                  | create \`som` files \(F\)                         | N                |
| cluster\_cell\_data      | Y                  | create clustered som files \(V\)                  | N                |
| cell\_consensus\_cluster | Y                  | create cell\_consensus\_cluster data \(V\)        | N                |
| cell\_interactive        | N                  | N/A                                               | N                |
| cell\_apply\_remap       | Y                  | create `cell_meta_cluster_mapping.csv` \(V\) | N                |
| cell\_cmap\_gen          | N                  | N/A                                               | N                |
| cell\_som\_heatmap       | N                  | N/A                                               | N                |
| cell\_meta\_heatmap      | N                  | N/A                                               | N                |
| cell\_overlay\_fovs      | N                  | N/A                                               | N                |
| cell\_mask\_gen\_save    | N                  | N/A                                               | N                |
| cell\_overlay\_gen       | N                  | N/A                                               | N                |
| cell\_appent\_meta       | N                  | N/A                                               | N                |
| cell\_mantis\_project    | N                  | N/a                                               | N                |



## 4 - Post Clustering

| **Tagged Cell**                         | **Inject (Y/N)** | **Injection Variable / Function**         | **Skip (Y/N)** |
|-----------------------------------------|------------------|-------------------------------------------|----------------|
| import                                  | N                | N/A                                       | N              |
| dir_set                                 | Y                | base_dir (V)                              | N              |
| create_dirs                             | N                | N/A                                       | N              |
| problem_cluster_hist                    | Y                | populations, marker (V)                   | N              |
| problem_cluster_split                   | Y                | marker, problematic_cluster (V)           | N              |
| marker_mantis_project                   | N                | N/A                                       | N              |
| problem_cluster_final_assignment        | Y                | problematic_cluster, final_assignment (V) | N              |
| save_updated_cell_table                 | N                | N/A                                       | N              |
| load_updated_cell_table                 | Y                | functional_markers (V)                    | N              |
| functional_marker_counts_mantis_project | N                | N/A                                       | N              |
| marker_threshold_range                  | Y                | populations, marker (V)                   | N              |
| threshold_values                        | Y                | threshold_list (V)                        | N              |
| updated_cell_table                      | N                | N/A                                       | N              |

**Comment by ngreenwald** [comment]
Awesome, @alex-l-kong take a look and see if you agree. 

@srivarra, notebook 4 is fairly straightforward, I don't think there's much logic in the cells that isn't covered elsewhere. What's the thinking behind injecting for things like the list of populations? Do we expect the test data to be different?

**Comment by srivarra** [comment]
@ngreenwald It's mainly cause the test FOVs that get made have generic channel names like `chan_0`, `chan_1`, etc.

**Comment by alex-l-kong** [comment]
This looks good.

**Comment by ngreenwald** [comment]
Got it, so if we have a small test dataset of real data that we use instead, we could get rid of some of those modifications and just run the cells as is?

**Comment by srivarra** [comment]
Yeah that would work as well. And it could also be cached locally + on travis.
