### ISSUE TITLE
Remove parallel processing from pixie

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#771]
**Is your feature request related to a problem? Please describe.**
The parallel processing implemented in Pixie has in general been hard to maintain, and doesn't play nice across OS. 

**Describe the solution you'd like**
Remove the parallel processing functionality in favor of slower, but simpler, code which runs each FOV in series.

**Comment by alex-l-kong** [comment]
@ngreenwald would it be better to have both options available to the user? We can turn off multiprocessing by default and have separate logic to run the non-multiprocessed loop, and add additional notebook flags in to turn this on if desired.

In this way, users who have not experienced problems with multiprocessing can still get a speedup.

**Comment by ngreenwald** [comment]
Will you be able to reuse the multiprocessing-friendly versions of the individual functions, or you'll need to write different ones that work on their own? I think I remember we had to do a refactor in order to get them to work for multiprocessing

**Comment by alex-l-kong** [comment]
@ngreenwald we can easily integrate this with existing functionality. Both `run_pixel_som.R` and `pixel_consensus_cluster.R` will need slight reorganization, it was about time to clean up those files via creating more helper functions anyways.

**Comment by ngreenwald** [comment]
okay sounds good, in that case makes sense to leave as an option but set the default to a version that doesn't use the multiprocessing library at all
