### ISSUE TITLE
We want to be able to choose color for pixel clustering metaclusters.

### ISSUE THREAD

**Issue by dtebaykin** [angelolab/ark-analysis#773]
**Is your feature request related to a problem? Please describe.**
We want to be able to pick color after metacluster merging in 2_Cluster_Pixels.ipynb heatmap
Currently, it assigns the next available color in the palette(?) used. This means a fully re-metaclustered heatmap and subsequent overlays are very difficult to look at (They can be mostly green/cyan or purple).

**Describe the solution you'd like**
A new field could be added after "New metacluster" button that allows for selection of one of the currently unused colors from the color palette.

**Describe alternatives you've considered**
The solution for now is to re-run clustering and first select the color you want the cluster to end up as during meta-reclustering.

**Additional context**
N/A

**Comment by dtebaykin** [comment]
EDIT: The new metacluster always ends up as the next available color, not the color of any selected for merging clusters.

**Comment by dtebaykin** [comment]
The bigger issue are the overlays that are generated after the heatmap using the same cluster colors. After merging the clusters the overlays are various shades of green and very hard to distinguish between groups of cells.

**Comment by cliu72** [comment]
I think the easiest way to go about this is to have custom scripts after all the clustering is done, and specify whatever colors you want in that script. I don't think this should be a default feature of the Pixie notebook, since the notebook will be run iteratively with mantis to figure out what the best clusters are. In my head, choosing colors is a downstream visualization task to make figures look nicer, and can be handled after the clusters are final.

Here is example code for making color overlays:
```
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
from matplotlib import colors
import skimage.io as io

# Manually define colors for more flexibility
# Will need to change the length of cols depending on how many clusters you have
# If num_clusters=20 (i.e. you have 20 clusters), the last element in the list should be cols[20]
# If num_clusters=25 (i.e. you have 25 clusters), the last element in the list should be cols[25]
# cols[1] = '#whatevercolor' means that cluster #1 will be that color
num_clusters = 20
cols = [None]*(num_clusters+1)
cols[0] = '#000000' #empty slide is usually 0, leave this as black
cols[1] = '#808080'
cols[2] = '#1F78B4'
cols[3] = '#FFBE7D'
cols[4] = '#FF7F00'
cols[5] = '#59A14F'
cols[6] = '#E31A1C'
cols[7] = '#B2DF8A'
cols[8] = '#A0CBE8'
cols[9] = '#FFFFCC'
cols[10] = '#6A3D9A'
cols[11] = '#F1CE63'
cols[12] = '#B15928'
cols[13] = '#499894'
cols[14] = '#FBB4AE'
cols[15] = '#D4A6C8'
cols[16] = '#FDDAEC'
cols[17] = '#B6992D'
cols[18] = '#E5C494'
cols[19] = '#8DA0CB'
cols[20] = '#B3B3B3'

# Make bounds
bounds = [i-0.5 for i in np.linspace(0,num_clusters+1,num_clusters+2)]
colmap = colors.ListedColormap(cols)
norm = colors.BoundaryNorm(bounds, colmap.N)

# Where the mask tiffs are saved, the pixel values in these tiffs should correspond to cluster number
mask_dir = "pixel_masks"
# Output directory where the colored tiffs will be saved
output_dir = "pixel_masks_colored"
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# Make the colord tiffs
all_fovs = os.listdir(mask_dir)
for fov in all_fovs:
    clust_array = np.array(io.imread(os.path.join(mask_dir,fov)))
    image = colmap(norm(clust_array))
    plt.imsave(os.path.join(output_dir, fov.replace(".tiff","_colored.tiff")), image)
```

**Comment by dtebaykin** [comment]
Will try that, thank you for sharing. One solution could be adding a color palette variable to the function that makes overlays. It would be optional and should overwrite the default colors from the heatmap.
