### ISSUE TITLE
`pixel_output_dir` folder does not create properly in pixel clustering

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#778]
**Describe the bug**

The current method of creating `pixel_output_dir` does not create this directory in the correct location.

The problem is in the `os.makedirs(pixel_output_dir)` call. This will create `pixel_output_dir` in the root `templates` folder instead of `base_dir`.

**Expected behavior**

Change `os.makedirs(pixel_output_dir)` to `os.makedirs(os.path.join(base_dir, pixel_output_dir))`.

**To Reproduce**

Run pixel clustering notebook as is with any dataset.

**Comment by srivarra** [comment]
I think it's already like that? [link to main's notebook 2](https://github.com/angelolab/ark-analysis/blob/9fb4e50241c52d738c9f4268948ceaa737cb93a3/templates/2_Cluster_Pixels.ipynb)

**Comment by alex-l-kong** [comment]
Something weird must have happened on my end then.
