### ISSUE TITLE
Unable to interact with the matplotlib widget in Jupyter Lab notebook

### ISSUE THREAD

**Issue by nancyliy** [angelolab/ark-analysis#784]
I was running the Pixel Clustering notebook on my data and run into an issue at the step using Metacluster Visualization GUI. As the screen recording attached shows, I was unable to interact with the matplotlib that was generated. Please kindly help!

Here are some widget extension info: 
<img width="755" alt="Screen Shot 2022-10-20 at 12 51 16 AM" src="https://user-images.githubusercontent.com/78202174/197043993-5226a6f1-f25c-4934-947b-9fa51cf0ecbc.png">

https://user-images.githubusercontent.com/78202174/197043847-861e8d55-1413-4dfb-96c9-19d1cf082bf8.mov

**Comment by alex-l-kong** [comment]
Hi @nancyliy, can you try zooming out in your browser and recapturing the video so I can see the entire visualization? It's a bit hard to see what's going on right now, the lower bar identifying the SOM/meta clusters selected currently isn't displayed in the video.

**Comment by nancyliy** [comment]
https://user-images.githubusercontent.com/78202174/197298807-b4550ee2-c746-43d6-96ec-f5f2e2e8b2e2.mov

Hi Alex here you go the recaptured video for your kind troubleshooting. Thank you!

**Comment by alex-l-kong** [comment]
@nancyliy sometimes inputting multiple clicks in a short time frame (ex. 2 seconds) can cause strange reactions from the GUI; it does seem to select your clusters/metaclusters eventually after a click. How long do you usually have to wait for the selection to actually show up?

**Comment by alex-l-kong** [comment]
@nancyliy here's a video to demonstrate how the video works:

https://user-images.githubusercontent.com/31424707/197592865-bd516871-baa4-4608-adca-dd6558befe89.mov

**Comment by alex-l-kong** [comment]
@nancyliy how many SOM clusters did you specify? It seems like you have a lot, you may need to zoom out in your browser to see the `New metacluster` button.

With a lot of SOM metaclusters you may experience slower loading times using the GUI. I'll need to do some research into seeing if this can be sped up or if it's an inherent scalability problem with number of SOM clusters.
