### ISSUE TITLE
unable to exclude channels when using k-means clustering to find neighborhoods

### ISSUE THREAD

**Issue by nancyliy** [angelolab/ark-analysis#787]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
when running the example neighborhood analysis script to perform k means clustering using the `spatial_analysis.generate_cluster_matrix_results` function, I encountered a key error stating the specified channel to exclude is not found in axis" even though I specified the correct channel column name in my spatial enrichment input cell table (attached). In addition, I would like to know the way to perform k means clustering with no channels excluded (include all channels). I tried setting excluded_channels = [""] or excluded_channels = `None` but neither of the methods worked.

**Expected behavior**
the jupyter cell runs and k-means clustering results are generated

**To Reproduce**
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/78202174/197352144-d0c1f9b6-1006-4c02-a4a0-037389822191.png">
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/78202174/197352152-3af2b497-32a2-42b8-919a-8dfcf366af38.png">
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/78202174/197352166-dbd16cbb-4d7f-43ec-b0e6-0b38b3b20da3.png">

[reg001_X05_Y05_final_cell_type_assignment_for_neighborhood.csv](https://github.com/angelolab/ark-analysis/files/9844858/reg001_X05_Y05_final_cell_type_assignment_for_neighborhood.csv)

**Comment by cliu72** [comment]
Hi Nancy! In `settings.py` (this file is located in ark-analysis/ark), can you make sure that `PRE_CHANNEL_COL` and `POST_CHANNEL_COL` are set to the correct values? These should be the column names in your data table right before and after all the channel names. In the csv you linked, I think `PRE_CHANNEL_COL = "centroid-1"` and `POST_CHANNEL_COL = "label"`. Hopefully that will allow you to specify excluded channels.

If you don't want to exclude any channels, I just opened a pull request for that fix. While we are waiting for someone to review that code and merge it into the main branch, you can checkout that branch using "git checkout kmeans_nh_no_excluded_channels_fix" - which should let you set `excluded_channels = None`.

**Comment by cliu72** [comment]
@ngreenwald should we put somewhere in the documentation to make sure `settings.py` matches with the data table? Specifying PRE_CHANNEL_COL and POST_CHANNEL_COL in settings was Adam's code (and I think is used elsewhere, not just in the kmeans notebook). I don't think it currently handles the case where a channel column is either the first or last column in the table (i.e. if there is no pre or post channel column).

**Comment by ngreenwald** [comment]
I think our assumption is that anyone using the spatial analysis scripts will have generated their cell table with Mesmer/Pixie. Is there a scenario where that would produce a cell table without a pre-channel or post-channel column?

**Comment by cliu72** [comment]
If the assumption is that everyone's cell table was generated with Mesmer/Pixie, then probably not necessary unless people manually change their cell table for some reason. I think it would be good to document somewhere that `settings.py` can be changed to accommodate different cell tables (maybe readthedocs somewhere?)
