### ISSUE TITLE
Mixing Score functionality

### ISSUE THREAD

**Issue by camisowers** [angelolab/ark-analysis#793]
*This is for internal use only; if you'd like to open an issue or request a new feature, please open a bug or enhancement issue*

**Relevant background**

As mentioned in issue #756, we would like to create a function to calculate the mixing score between any two cell populations in a sample. The tumor-immune mixing score (https://www.cell.com/cell/pdf/S0092-8674(18)31100-0.pdf) can be generalized as the # of reference-target interactions divided by the # of reference-reference interactions, to measure the degree of target cell mixing within reference cell areas. We may want to explore other ways of calculating the mixing score, but identifying interactions between cell types is the central functionally required for any mixing analysis. 

**Design overview**

* We define an interaction between cells as being within an agreed upon distance from each other, as determined by the distance matrix for each FOV. There already exists a `calc_dist_matrix()` function used by all the spatial analysis notebooks, that details the distances between the centers of each pair of cells. 
* Using these distance matrices, we will be able to find the neighboring cell types of each individual cell in the FOV.
<img width="129" alt="Screen Shot 2022-10-26 at 3 11 55 PM" src="https://user-images.githubusercontent.com/38049893/198148714-70c289fd-f4eb-40fd-90f6-3751f4d5a955.png">
We already do this for our k-means clustering analysis with the function `create_neighborhood_matrix` which returns a neighbor's matrix dataframe and gets saved as `neighborhood_counts.csv` in the notebook. 

1. the default radius for identifying neighbors for kmeans clustering is`distlim=50`
2. we will need to do some digging to find a more suitable radius that only catches the more immediate cell neighbors
3. so even though a neighbor's matrix already exists, we will need to generate a new new "cell_neighbors" matrix and it should be saved as well (includes all FOVs)

* The current neighbor's data generated does not specify the cell type for each individual cell (blue column below), which is necessary to determine what type of cells are interacting.
<img width="500" alt="Screen Shot 2022-10-26 at 3 21 05 PM" src="https://user-images.githubusercontent.com/38049893/198149671-b6fde95f-4142-4236-b56a-93655c0788e1.png">

1. One option is to add a bool arg to `create_neighborhood_matrix` for whether to include a column specifying the cell type of each individual cell, but I think we can just add it into the regularly generated neighborhood matrix without causing issues 

Once we have the appropriate cell neighbors matrix, a function to calculate the mixing score can be discussed further and will be relatively simple to implement. This can either go into an individual notebook or be added at the end of the spatial notebooks. 

**Code mockup**

Add column with cell type ids to neighborhood matrix:
```
def create_neighborhood_matrix(all_data, dist_matrices_dict, included_fovs=None, distlim=50,
                               self_neighbor=False, fov_col=settings.FOV_ID,
                               cell_label_col=settings.CELL_LABEL,
                               cluster_name_col=settings.CELL_TYPE):

    # Initialize empty matrices for cell neighborhood data, now 3 cols for id instead of 2
    cell_neighbor_counts = pd.DataFrame(
        np.zeros((all_neighborhood_data.shape[0], cluster_num +[fov_col, cell_label_col, cluster_name_col]))
    )

    # Replace the id columns of cell_neighbor_counts w/ fovs, cell-labels, (cell types) respectively
    cell_neighbor_counts[0, 1, 2] = all_neighborhood_data[[fov_col, cell_label_col, cluster_name_col]]

    # Rename the columns to match cell phenotypes
    cols =  [fov_col, cell_label_col, cluster_name_col])) + list(cluster_names)
    cell_neighbor_counts.columns = cols

...

```
New functions:

```
def compute_cell_neighbors(all_data, dist_matrices_dict, save_dir, included_fovs=None, distlim=50,
                               self_neighbor=False, fov_col=settings.FOV_ID,
                               cell_label_col=settings.CELL_LABEL,
                               cluster_name_col=settings.CELL_TYPE):

    neighbors_radius = ?

    # find only close neighboring cells, save to csv file
    for fov in included_fovs:
        cell_neighbors = create_neighborhood_matrix(..., fov, distlim=neighbors_radius, ...)
        cell_neighbors.to_csv(os.path.join(save_dir, f"{fov}_cell_neighbors.csv"), index=False)
```

```
def compute_mixing_score(cell_neighbors_dir, fov, target_cell, reference_cell, cluster_name_col=settings.CELL_TYPE):
    
    # read in fov cell neighbors, drop fov and cell label columns
    neighbors_mat = pd.read_csv(os.path.join(cell_neighbors_dir, f"{fov}_cell_neighbors.csv"))
    neighbors_mat = neighbors_mat.drop([0, 1])
    
    # condense if we don't need individual cell info, just totally number of cell type interactions
    interactions_mat = neighbors_mat.groupby(by=[settings.CELL_TYPE]).sum()
    
    # example mixing calc based on Leeat's paper
    reference_target = interactions_mat.loc([target_cell, reference_cell])
    reference_reference = interactions_mat.loc([reference_cell, reference_cell])

    mixing score = reference_target / reference_reference
    #  technically should be (reference_target / 2) / (reference_reference / 2) but also ratios

    return mixing_score

```

**Required inputs**

Only need the previously calculated FOV distance matrices. No image data required. 

**Output files**

Potentially a file detailing the mixing scores for each specific FOV and cell pairings looked at. This can vary based on how we decide to format the notebook implementation later (e.g. whether we want to loop through and calculate the mixing score for a specific cell pairing among all the FOVs and save the values). 

**Timeline**
Give a rough estimate for how long you think the project will take. In general, it's better to be too conservative rather than too optimistic. 
- [ ] A couple days
- [ ] A week
- [x] Multiple weeks. For large projects, make sure to agree on a plan that isn't just a single monster PR at the end. 

It shouldn't take long to adjust the neighborhood matrix function and code the helper functions; however the I imagine testing out radii (on the example data?) and further honing in on the details of the mixing score calculation will take up most of the time. 

Estimated date when a fully implemented version will be ready for review:
depending on PR #803.

Estimated date when the finalized project will be merged in: 
mid - late November

**Comment by ngreenwald** [comment]
This looks great. @efrancis28 take a look and see if this lines up with what you were thinking as well. 

I think rather than using the example dataset, using the TNBC dataset from Leeat's paper makes sense. There should be a supplemental table with the mixing score for each patient, you can make sure that you're getting exactly the same thing if we implement it the same way, or roughly the same thing (i.e. relative ranking) if we make some small changes. I think adding the cell table column to the output by default makes the most sense. Good to go ahead and get started!

**Comment by efrancis28** [comment]
Agreed the overview looks great! Using the TNBC dataset will also help us confirm which version of her mixing score script she actually used. Otherwise, I have example data and results for my myeloid-lymphocyte mixing score that could be useful.
