### ISSUE TITLE
Populations specified in post clustering notebook don't work with example dataset

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#821]
**Describe the bug**

The current populations specified for the post clustering notebook aren't specified in the `cell_meta_cluster` column of the example `cell_table`, which throws a `ValueError`. This happens in both plotting steps.

**Expected behavior**

Notebook should run seamlessly using the example dataset.

**To Reproduce**

Run notebook as is.

<img width="1251" alt="Screen Shot 2022-11-10 at 11 45 20 AM" src="https://user-images.githubusercontent.com/31424707/201191475-f26dc0cb-372c-4ff5-b198-92847528500c.png">

**Comment by srivarra** [comment]
In the Download the Example Dataset could you try changing `overwriting_existing` from `False` to `True` and then running it?

**Comment by srivarra** [comment]
I don't think there's a programmatic way to do that, but I can add when to set `overwrite_existing` to `True` to the description in the notebooks.

**Comment by ngreenwald** [comment]
Is the issue that you had a previous version of the example dataset prior to a huggingface update, or is this a problem with what sequence of notebooks had been run in what order?

**Comment by srivarra** [comment]
It's somewhat related to running the notebooks in sequence. Only notebook 1 has the overwrite flag defaulted to `True`. This will always force the download + moving the dataset to `data/example_dataset/`. 2-4 have overwrite defaulted to `False` so data generated by notebook 1 does not get overwritten (if a user wants to run 1-4 in succession). But if the directories a notebook needs does not exist, it should download and move it over.

 @alex-l-kong Do you recall if a warning appeared when running the `get_example_dataset` with overwrite as `False` saying "Files exist in <some path>. They will not be overwritten"?

**Comment by alex-l-kong** [comment]
@srivarra yes.

**Comment by srivarra** [comment]
I see, perhaps there was a different cell table in `data/example_dataset/segmentation/cell_table`?

**Comment by ngreenwald** [comment]
Okay, so the cell table from notebook one, which doesn't have any pixie labels, overwrote the existing one?

**Comment by srivarra** [comment]
Yeah, and since it wasn't overwritten, the notebook opened the incorrect file.
