### ISSUE TITLE
Input Validation and Error Handling

### ISSUE THREAD

**Issue by srivarra** [angelolab/ark-analysis#827]
*This is for internal use only; if you'd like to open an issue or request a new feature, please open a bug or enhancement issue*

### Instructions
This document should be filled out prior to embarking on any project that will take more than a couple hours to complete. The goal is to make sure that everyone is on the same page for the functionality and requirements of new features. Therefore, it's important that this is detailed enough to catch any misunderstandings beforehand. For larger projects, it can be useful to first give a high-level sketch, and then go back and fill in the details. For smaller ones, filling the entire thing out at once can be sufficient.  

**Relevant background**

Throughout the Notebooks, there are many instances where a user inputs their own paths to files / directories, FOV names, channel names and more.
If a user inputs potentially an incorrect parameter, sometimes the errors which get thrown are in packages like `Pandas`, or `xarray`, which can be unintuitive for users to try to fix themselves. Currently functions like `validate_paths` make use of Exception handling such as `FileNotFound`. However, these issues could be more specific.

For example `validate_paths` errors out during the first `FileNotFound` exception. It would be useful for it to gather all the non-existing files and print them out together.
In addition, these errors should be raised to the function which called it, such as `create_pixel_matrix`. This ensures that `create_pixel_matrix` displays the error for the user, instead of `validate_paths`, thus making the error stack shorter and easier to navigate.

Resources:
 - [Python Exceptions](https://realpython.com/python-exceptions/)
 - [Builtin Exceptions](https://docs.python.org/3/library/exceptions.html)
 - [Exception Groups](https://realpython.com/python311-exception-groups/), not useful until we bump to python 3.11. Skip for now.
 - [Look Before You Leap (LBYL), and Easier to Ask Forgiveness than Permission (EAFP)](https://realpython.com/python-lbyl-vs-eafp/)

**Design overview**

Create custom exceptions for the following:
- `FOVNotFound` (File itself, Cell Table cell)
- `ChannelNotFound` (File, Cell Table cell)
- `BinFileNotFound` (Toffy / mibi-bin-tools support maybe?)
- `CellTableColumnNotFound` (https://github.com/angelolab/ark-analysis/issues/787)

These exceptions will be inherited from `FileNotFound` or just the base `Exception`. These exceptions will occur in the validation functions (like `io_utils.validate_paths`), so we need to add proper handling for those base validation functions.

For the following functions implement `FOVNotFound` and `ChannelNotFound`:
- `ark.phenotyping`:
  - `pixel_cluster_utils`
    - `smooth_channels`
    - `filter_with_nuclear_mask`
    - `create_pixel_matrix`
    - `train_pixel_som`
    - `cluster_pixels`
    - `pixel_consensus_cluster`
    - `apply_pixel_meta_cluster_remapping`
  - `cell_cluster_utils`
    - `train_cell_som`
    - `cluster_cells`
    - `cell_consensus_cluster`
    - `apply_cell_meta_cluster_remapping`
    - `generate_weighted_channel_avg_heatmap`
- `ark.utils`
  - `data_utils`
    - `generate_deepcell_input` (`ChannelNotFound` for `nuc_channels`, `mem_channels`)
    - `generate_and_save_pixel_cluster_masks`
    - `generate_and_save_cell_cluster_masks`
  - `plot_utils`
    - `create_overlay`
    - `plot_pixel_cell_cluster_overlay`
    - `create_mantis_dir`
    - `plot_pixel_cell_cluster_overlay`
  - `segmentation_utils`
    - `generate_cell_table`
- `ark.analysis`
  - `spatial_analysis`
    - `generate_cluster_matrix_results` (Fov not found in the cell table)

The following implement `CellTableColumnNotFound`:
- `ark.analysis`:
  - `spatial_analysis`
    - `generate_cluster_matrix_results`
- `ark.segmentation`
    - `marker_quantification`
        - `compute_marker_counts`
- `ark.utils`
  - `segmentation_utils`
    - `transform_expression_matrix`

The following functions need extra path input validation:
- `ark.phenotyping`
  - `post_cluster_utils`
    - `plot_hist_thresholds`
    - `create_mantis_project`

For functions which call other functions which end up calling any of the validate functions, make sure to correctly raise the exception the correct amount of times, such as in `ark.utils.segmentation_utils.generate_cell_table`. Ideally, the validation functions should be called in the top level user-facing function themselves. `smooth_channels` calls `load_imgs_from_tree`.

Use [*Tracing*](https://docs.python.org/3/library/traceback.html) to raise the exception to get more context if necessary (and where appropriate).

**Code mockup**

```python
class FOVNotFoundError(Exception):
    """ Raised when a FOV directory is not found in a directory where it should be."""

    def __init__(self, value) -> None:
        self.value = value

    # __str__ is to print() the value
    def __str__(self) -> str:
        return (repr(self.value))


class ChannelNotFoundError(Exception):
    """ Raised when a channel tiff file is not found in a directory where it should be."""
    ...


class CellTableColumnNotFoundError(pandas.errors.InvalidColumnName):
    """ Raised when an incorrect Cell Table Column is attempted to be accessed."""
    ...

```

For example, in `ark.analysis.spatial_analysis.generate_cluster_matrix_results`, we can wrap the cell table FOV column check with `verify_in_list`:

```python
try:
    misc_utils.verify_in_list(fov_names = included_fovs, unique_fovs=all_data[fov_col].unique())
except ValueError as e:
    raise FOVNotFoundError(f"this channel {e.err_string} is not found in the cell_table") from e

```

In `ark.analysis.spatial_analysis.calculate_channel_spatial_enrichment`, we can make sure that the `PRE_CHANNEL_COL` and `POST_CHANNEL_COL` values exist in the Cell table: Here we will raise the error with a traceback (not always necessary, useful for nested procedures).

```python
try:
    misc_utils.verify_in_list(cell_table_cols = cell_table.columns, channel_cols = [PRE_CHANNEL_COL, POST_CHANNEL_COL])
except ValueError as e:
    tb = sys.exc_info()[2]
    raise CellTableColumnNotFoundError(f"The CHANNEL_COL {e.err_string} is not found in the cell table.").with_traceback(tb) from e
```

Python error handling follows the following framework:

```python
try:
    "try something"
except:
    "run something when an execption occurs"
else:
    "No exceptions, run this"
finally:
    "Always run this code (with and without) exceptions"
```

When applicable, we should try and make use of `else` and `finally`.

We should move all the validation / verification functions to a separate file.

**Required inputs**

The inputs for each function will remain unchanged, we will just need to wrap certain validation checks. The only input would be for each `Exception` class raised to hold the error string.

**Output files**

No output files are generated.

However, we should make sure that any `try; except; etc...` do not have any side effects when they error out (i.e. appending to a file when a necessary column does not exist.)

**Timeline**
Give a rough estimate for how long you think the project will take. In general, it's better to be too conservative rather than too optimistic. 

Two weeks.

Estimated date when a fully implemented version will be ready for review: 11/28/22

Estimated date when the finalized project will be merged in: 12/2/22

**Comment by srivarra** [comment]
@ngreenwald

**Comment by ngreenwald** [comment]
Nice work. @alex-l-kong @camisowers will you guys take a look as well, lets discuss at standup today
