### ISSUE TITLE
Port pixel and cell consensus clustering process to Python

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#831]
**Relevant background**

ConsensusClusterPlus will need to be handled separately from `pyFlowSOM` in the transition to a purely Python-based pixel and cell clustering workflow. We don't need to find a perfectly equivalent Python alternative, but it does need to support the general idea of consensus clustering.

**Design overview**

[This](https://github.com/ZigaSajovic/Consensus_Clustering) implementation of consensus clustering should do the trick. Because this repo has not made a formal release, we would need to directly copy the `ConsensusCluster` class in  `consensusClustering.py` file to our repo for our own use.

This class makes it easy for us to replace the existing `ConsensusClusterPlus` logic in R; both `pixel_consensus_cluster.R` and `cell_consensus_cluster.R` can be removed after this. Note that scaling, capping, and cluster assignment will need to be moved to `pixel_consensus_cluster` and `cell_consensus_cluster` in `pixel_cluster_utils.py` and `cell_cluster_utils.py` respectively.

**Code mockup**

_Abstract Consensus Cluster Class_

We should create a separate file called `clustering_helpers.py` in `phenotyping`. This will initially contain just the Pixie consensus cluster class (`PixieConsensusCluster`) but will later also contain `PixieSOMCluster` after `pyFlowSOM` is finalized.

`PixieConsensusCluster` will have the following general implementaiton:

``` 
class PixieConsensusCluster:
    def __init__(self, input_file: pathlib.Path, columns: List[str], max_k: int = 20, cap: float = 3):
        self.input_data = pd.read_csv(input_file)
        self.columns = columns # the columns to subset on
        self.max_k = max_k
        self.cap = cap
        self.cc = # define ConsensusCluster object with parameters cluster_ = sklearn.AgglomerativeClustering (same as hierarchical clustering for CCP) L = 2 (default min), K = max_k (same as maxK arg in CCP), H = 10 (same as reps in CCP), and resample_proportion = 0.8 (same as pItem in CCP).
        self.mapping = None  # this will be set during generate_som_to_meta_map

    def scale_data(self):
        # equivalent of running scale, pmin, and pmax in R on self.input_data[columns], we'll need to find equivalent Python functions but shouldn't be hard

    def run_consensus_clustering(self):
        self.cc.fit(self.input_data[columns])

    def generate_som_to_meta_map(self):
        # use a slightly modified version of predict_data by Sajovich to map SOM clusters to meta clusters and assign to self.mapping. We have to modify as that function as it uses the k with the best metrics, but we always want the max k

    def save_som_to_meta_map(self, save_path: pathlib.Path):
        self.mapping.to_csv(save_path)  # may be adjusted to support consistency of setting base_dir

    def assign_consensus_labels(self, external_data: pandas.DataFrame) -> pandas.DataFrame:  # NOTE: for pixel clustering, this will be called for each FOV, the looping/multiprocessing support will be handled by the pixel_consensus_cluster function in pixel_cluster_utils.py
        # use self.mapping to assign equivalent meta cluster based on the SOM cluster
``` 

This functionality will replace both `pixel_consensus_cluster.R` and `cell_consensus_cluster.R`.

_Integration with `pixel_consensus_cluster`_

Prior to the call to `assign_consensus_labels`, `pixel_consensus_cluster` and `cell_consensus_cluster` must load the pixel/cell data in, and afterwards save it to the appropriate location. Note that for pixel clustering, the loop/multiprocessing currently in `pixel_consensus_cluster.R` will need to be moved to `pixel_consensus_cluster` in `pixel_cluster_utils.py`:

```
if multiprocess:
    with multiprocessing.get_context('spawn').Pool(batch_size) as fov_data_pool:
        for fov_batch in [fovs_list[i:(i + batch_size)]
                          for i in range(0, len(fovs_list), batch_size)]:
            # load in all the DataFrames and use fov_data_pool to make a multiprocess call to assign_consensus_labels
            # loop over the processed DataFrames and save
else:
    for fov in fovs_list:
        # load in the DataFrame and call assign_consensus_labels
        # save
```

_Integration with `cell_consensus_cluster`_

Because no multiprocessing is needed for cell consensus clustering, this function only needs to handle additional file loading and saving currently done in R.

_Porting over `ConsensusCluster` class_

We can copy over the `ConsensusCluster` class directly to `clustering_helpers.py`, or we can copy over the file directly. Either way, it shouldn't be necessary to write our own test functions for this.

_Testing_

We can use a small dataset (via `pytest.fixture`) to test this functionality. Since this is an abstract consensus clustering class, we can just test the general functionality in `clustering_helpers_test.py`, and leave the pixel and cell-specific tests to `notebooks_test.py` using the example datasets (the internal logic will need amending as there's no need to mock the call to `pixel_consensus_cluster`).

Additionally, `pixel_consensus_cluster` and `cell_consensus_cluster` can now be directly tested instead of being mocked. As with `clustering_helpers_test.py`, we can use simple datasets for these.

**Required inputs**

`PixieConsensusCluster` will need the respective SOM average file (generated by `cluster_pixels` and `cluster_cells`) as well as the `cap` and `max_k` arguments from the user.

**Output files**

Same as the original.

**Timeline**

- [ ] A couple days
- [ ] A week
- [X] Multiple weeks. For large projects, make sure to agree on a plan that isn't just a single monster PR at the end. 

Estimated date when a fully implemented version will be ready for review:

11/27/22 (Thanksgiving break will push this one out a bit longer...)

Estimated date when the finalized project will be merged in:

11/29/22

**Comment by alex-l-kong** [comment]
@ngreenwald @cliu72 let me know how this looks.

**Comment by ngreenwald** [comment]
I'll defer to candace on this one

**Comment by cliu72** [comment]
I think this looks good. One thought is that we can set the minimum k to equal whatever the user sets as maximum k, which will probably speed this up too (setting a minimum k wasn't an option in the R package, at least to the best of my knowledge, which is why I didn't do it in R). Perhaps doing that would avoid having to change the predict_data function as well.
