### ISSUE TITLE
Port `FlowSOM` functionality over to `pyFlowSOM`

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#833]
**Relevant background**

`pyFlowSOM` will replace the `FlowSOM` library which requires external `R` scripts to call. This will allow us to remove any R dependencies and files and transfer their functionality over to the respective Python functions. Additionally, this will also allow for full-fledged testing of the process.

**Design overview**

Because `pyFlowSOM` is essentially a trimmed-down native Python-implementation of the existing `FlowSOM` library, we can take a plug-and-play approach with the call to both train the SOM and map cluster values to the data.

There are a few extra elements that will require porting over to the Python:

- 99.9% normalization of the training data prior to training and the full data prior to cluster assignment
- Multiprocessing support for pixel clustering
- File loading and saving

**Code mockup**

_Abstract and derived SOM cluster classes_

As with Consensus Clustering, we define a SOM cluster class (`PixieSOMCluster`) in `clustering_helpers.py` as functionality will be generally shared between pixel and cell clustering. However, because of differences in normalization and data loading processes, it will be best to explicitly define `PixieSOMCluster` as an abstract class and have two other classes, `PixelSOMCluster` and `CellSOMCluster`, implement certain abstract methods in it.

The implementation will follow the general process:

```
from abc import ABC, abstractmethod
class PixieSOMCluster(ABC):
    @abstractmethod
    def __init__(self, columns: List[str], weights_path: pathlib.Path, num_passes: int = 1, xdim: int = 10, ydim: int = 10, lr_start: float = 0.05, lr_end: float=0.01):
        self.columns = columns
        self.weights = None if not weights_path.exists() else feather.read_dataframe(weights_path)  # NOTE: user can pass in an older weights path if desired to skip the training process
        self.num_passes = num_passes
        self.xdim = xdim
        self.ydim = ydim
        self.lr_start = lr_start
        self.lr_end = lr_end
        self.weights_path = weights_path

    @abstractmethod
    def normalize_data(self):
        pass

    def train_som(data: pd.DataFrame):
        self.weights = som(data=data, xdim=self.xdim, ydim=self.ydim, alpha_range=(self.lr_start, self.lr_end))  # imported from pyFlowSOM)
        feather.write_dataframe(self.weights, self.weights_path, compression='uncompressed'

    def assign_som_clusters(self, external_data: pandas.DataFrame) -> pandas.DataFrame:
        # make sure the columns of self.weights and external_data match up per Zak's request
        # call map_data_to_codes (imported from pyFlowSOM) and assign to external_data
        

class PixelSOMCluster(PixieSOMCluster):
    def __init__(self, pixel_data_folder: pathlib.Path, pixel_subset_folder: pathlib.Path, norm_vals_path: pathlib.Path, columns: List[str], weights_path: pathlib.Path, num_passes: int = 1, xdim: int = 10, ydim: int = 10, lr_start: float = 0.05, lr_end: float=0.01):
        super().__init__(columns, weights_path, num_pases, xdim, ydim, lr_start, lr_end, weights_path)
        self.norm_data = feather.read_dataframe(norm_vals_path)
        self.pixel_data_folder = pixel_data_folder  # the unsubsetted data folder
        self.train_data = # load and combine all the .feather files in pixel_subset_folder here

    def normalize_data(self, data: pandas.DataFrame):  # NOTE: this function will also be called per full FOV pixel dataset during cluster assignment
        # use the values in norm_data to normalize train_data

    def train_som(self):
        super().train_som(self.normalize_data(self.train_data))

    def assign_som_clusters(self, external_data: pandas.DataFrame) -> pandas.DataFrame:  # NOTE: for pixel clustering, this will be called for each FOV, the looping/multiprocessing support will be handled by the pixel_consensus_cluster function in pixel_cluster_utils.py
        super().assign_som_clusters(self.normalize_data(external_data))
        

class CellSOMCluster(PixieSOMCluster):
    def __init__(self, cell_data_path: pathlib.Path, columns: List[str], , weights_path: pathlib.Path, num_passes: int = 1, xdim: int = 10, ydim: int = 10, lr_start: float = 0.05, lr_end: float=0.01):
        super().__init__(columns, weights_path, num_pases, xdim, ydim, lr_start, lr_end, weights_path)
        self.cell_data = feather.read_dataframe(cell_data_path)

    def normalize_data(self, data: pandas.DataFrame):
        # normalize cell_data by the 99.9% values

    def train_som(self):
        super().train_som(self.normalize_data(self.cell_data))

    def assign_som_clusters(self) -> pandas.DataFrame:
        super().assign_som_clusters(self.normalize_data(self.cell_data))
```

This functionality will replace `create_pixel_som.R`, `run_pixel_som.R`, `create_cell_som.R`, and `run_cell_som.R`.

_Integration with `train_pixel_som` and `cluster_pixels`_

We can remove `pixel_weights_path` as the class instance directly stores the weights.

Because SOM cluster assignment can be an expensive process for massive pixel cohorts, we have optional multiprocessing support turned on. However, this will need to be ported over to Python. A general framework in `cluster_pixels` will look like:

```
if multiprocess:
    with multiprocessing.get_context('spawn').Pool(batch_size) as fov_data_pool:
        for fov_batch in [fovs_list[i:(i + batch_size)]
                          for i in range(0, len(fovs_list), batch_size)]:
            # load in all the DataFrames and use fov_data_pool to make a multiprocess call to assign_som_labels
            # loop over the processed DataFrames and save
else:
    for fov in fovs_list:
        # load in the DataFrame and call assign_som_labels
        # save
```

_Integration with `train_cell_som` and `cluster_cells`_

We can remove `cell_weights_path` as the class instance directly stores the weights.

Because no multiprocessing is needed for cell SOM clustering, this will be much more plug-and-play for us. We only need to handle additional file loading and saving in these functions.

_Testing_

We can use a small dataset (via `pytest.fixture`) to test this functionality. We don't need to directly test `PixieSOMCluster` because it is meant to be derived from. We can limit tests to `PixelSOMCluster` and `CellSOMCluster` functions with this small sample dataset.

`notebooks_test.py` will handle integration testing on more extensive datasets. Note that we can remove any mocks that exist since functionality will be fully ported over to Python.

Because all R helper scripts are being removed, we can now fully test `train_pixel_som`, `cluster_pixels`, `train_cell_som`, and `cluster_cells`. As with `PixelSOMCluster` and `CellSOMCluster`, we can use a simple fixture (perhaps the same one) to test.

**Required inputs**

No additional inputs will be required. However, instead of the R scripts, inputs will be shipped over to the `PixelSOMCluster` or `CellSOMCluster` instance.

**Output files**

Same as before

**Timeline**
Give a rough estimate for how long you think the project will take. In general, it's better to be too conservative rather than too optimistic. 
- [ ] A couple days
- [ ] A week
- [X] Multiple weeks. For large projects, make sure to agree on a plan that isn't just a single monster PR at the end. 

Estimated date when a fully implemented version will be ready for review:

TBD. Depends on Zak's progress. Definitely aiming for before winter closure.

Estimated date when the finalized project will be merged in: 

TBD. Depends on Zak's progress. Definitely aiming for before winter closure.

**Comment by alex-l-kong** [comment]
@ngreenwald @cliu72 this is subject to change based on Zak's work, but I think this will provide a high-level overview of `pyFlowSOM` integration for the time being. Let me know how it looks.

**Comment by ngreenwald** [comment]
Looks good. If the weights are stored as part of the class, how will the class be saved? We want to be able to run the SOM with the previous class, even if it's not from the current jupyter session

**Comment by alex-l-kong** [comment]
@ngreenwald oh good point, yeah let's save the weights instead. I'll update the design doc accordingly.

**Comment by cliu72** [comment]
This looks good to me
