### ISSUE TITLE
Consistent `segmentation_dir` across pixel and cell clustering notebooks

### ISSUE THREAD

**Issue by cliu72** [angelolab/ark-analysis#844]
**Is your feature request related to a problem? Please describe.**
- In the pixel clustering notebook, the segmentation directory is specified using:
```
segmentation_dir = "segmentation"
deepcell_output_dir = os.path.join(segmentation_dir, "deepcell_output")
```
- When saving the json to pass parameters to the cell clustering notebook, `segmentation_dir` is saved, not `deepcell_output_dir`
- In the cell clustering notebook, the user specifies `segmentation_dir = 'segmentation'`, but also, the directory specified in the pixel clustering notebook is read from the json: `deepcell_output = cell_clustering_params['segmentation_dir']`. This is confusing because what was specified as the segmentation directory in the pixel clustering notebook is being read in as `deepcell_output` in the cell clustering notebook. It is also redundant to have the user specify the segmentation directory and also read it from the json.

**Describe the solution you'd like**
- Be consistent with the way the segmentation directory is specified in pixel and cell clustering, and remove the user specified segmentation directory in the cell clustering notebook
- I think it would be better to remove the word "deepcell" from all variable names across both notebooks (and just use "segmentation_dir"). I understand that ark is meant for people who are using our segmentation notebook as well, but I am marketing Pixie as "generalizable" in the paper, so I think it would be confusing for people who read the paper and want to try it out who have no idea what "deepcell" is.
- I think it's fine to keep the word "deepcell" in the file paths, since the example data uses "deepcell", but I think removing it from the actual name of the variable would be helpful

**Comment by alex-l-kong** [comment]
I'm gonna loop in @srivarra on this discussion cause it might make sense to adjust the example dataset structure to make the workflow easier.

One of the potential problems integrating this fix with the current example data structure is the way the current `segmentation` directory (assigned to `segmentation_dir`) is handled. Having a separate `segmentation_dir` and `deepcell_output_dir` makes it easy for us to access the cell table directory inside `segmentation_dir` while also explicitly defining the path to the deepcell outputs.

There are a couple of programmatic hacks we can use to get around this, but I'm slightly concerned about the interoperability depending on if the user loads in the example dataset with or without the overwrite flag. @srivarra would appreciate some additional input on your end, we could also reorganize the example dataset but if there's an easier solution would definitely take that route instead.

**Comment by cliu72** [comment]
I don't think there's a need for programmatic hacks or reorganization of the example dataset. I think we can resolve this with the following changes:
1. In the pixel clustering notebook, rename `deepcell_output_dir` to `segmentation_dir` (and remove the original `segmentation_dir`) - since it's possible that users will be using segmentation output from something other than deepcell.

What it used to look like:
```
segmentation_dir = "segmentation"
deepcell_output_dir = os.path.join(segmentation_dir, "deepcell_output")
```

What it would look like after change:
```
segmentation_dir = os.path.join("segmentation", "deepcell_output")
```

After doing this, replace `deepcell_output_dir` with `segmentation_dir` everywhere in the notebook. Effectively, in the json, `segmentation_dir` would be saved as ` os.path.join(segmentation_dir, "deepcell_output")`.

2. In the cell clustering notebook, change the path to the cell table so it doesn't use a variable, so it looks like this. I think this is the easiest solution.
```
# define the cell table path
cell_table_path = os.path.join(base_dir, 'segmentation', 'cell_table', 'cell_table_size_normalized.csv')
```

3. In the cell clustering notebook, remove `segmentation_dir = 'segmentation'`, it's not actually important. The only place it is being used in the cell clustering notebook is in the function call to `generate_and_save_cell_cluster_masks` and even then, it is being used to specify the deepcell_output dir.

4. In the cell clustering notebook, rename `deepcell_output_dir` to `segmentation_dir`, so it looks something like this:
`segmentation_dir = cell_clustering_params['segmentation_dir']`. Then make these changes:
```
# generate and save the cell cluster masks for each fov in subset_cell_fovs
data_utils.generate_and_save_cell_cluster_masks(
    fovs=subset_cell_fovs,
    base_dir=base_dir,
    save_dir=os.path.join(base_dir, "pixie", cell_output_dir),
    seg_dir=os.path.join(base_dir, segmentation_dir), #this was changed
    cell_data_name=cell_data_name,
    seg_suffix=seg_suffix,
    sub_dir='cell_masks',
    name_suffix='_cell_mask'
)
```

```
plot_utils.create_mantis_dir(
    fovs=subset_cell_fovs,
    mantis_project_path=os.path.join(base_dir, "pixie", cell_output_dir, "mantis"),
    img_data_path=tiff_dir,
    mask_output_dir=os.path.join(base_dir, "pixie", cell_output_dir, "cell_masks"),
    mapping = os.path.join(base_dir, cell_meta_cluster_remap_name),
    seg_dir=os.path.join(base_dir, segmentation_dir), #this was changed
    mask_suffix="_cell_mask",
    seg_suffix_name=seg_suffix)
```

**Comment by alex-l-kong** [comment]
@cliu72 OK that makes sense. Had steps 1-3 down but seems like I got too hung up on defining `cell_table_path` in a manner that didn't involve too many arguments in `os.path.join` in step 4.
