### ISSUE TITLE
Pixel clustering/cell clustering file cleanup

### ISSUE THREAD

**Issue by cliu72** [angelolab/ark-analysis#845]
**Is your feature request related to a problem? Please describe.**
Just some small miscellaneous stuff I noticed when testing the pixel/cell clustering notebooks.
- [X] I think we talked before about removing the prefix from the individual filenames (and only using the prefix for the folder name). They have been removed from most of them, but they still exist on some files: *_channel_norm.feather, *_pixel_norm.feather. Related to this, I don't think the `create_pixel_matrix` function needs the `pixel_cluster_prefix` argument.
- [X] Related to the above point, currently all the individual filenames for cell clustering still include the prefix. Can we remove those?
- [x] Currently, the first 99.9 normalization file is called *_channel_norm.feather and the second 99.9 normalization is called post_rowsum_chan_norm.feather. Can we make these more similar and intuitive - maybe channel_norm.feather and channel_norm_post_preprocessing.feather - or something like that?
- [x] Related to the point above, the two 99.9 normalization files have different formats. The first one (*_channel_norm.feather) has one column for channels, and a second column for norm values, while the second one (post_rowsum_chan_norm.feather) has a different column for each marker - can we make these two files consistent?
- [x] The threshold we use to filter out low expressing pixels is currently called *_pixel_norm.feather. I think this is slightly confusing because we're not really normalizing using this value. We're using it as a threshold. Can we call it 'pixel_threshold.feather' or something like that? Similarly, in this file, the name of the column is "pixel_norm_val" - can we change this to "pixel_threshold_val"?
- [x] Can we change the name of the weights file from "pixel_weights.feather" to "pixel_som_weights.feather"? Same for the cells - can we change to "cell_som_weights.feather"?
- [x] I don't think it's necessary to save the "pixel_som_to_meta.feather" file. That information is already captured in "pixel_channel_avg_som_cluster.csv." Same for *_cell_clust_to_meta.feather.
- [x] Can we change *_cluster_counts_norm.feather to *_cluster_counts_size_normalized.feather?
- [x] Can we save *_weighted_cell_channel.csv as a feather file, just to be consistent? *_cluster_counts.feather and *_cluster_counts_norm.feather have basically the same dimensions.
- [x] It seems to me that *_cell_mat.feather and *_cluster_counts_norm.feather have basically the same info, but *_cell_mat.feather has an additional columns for the clusters, I don't think we need the count info in multiple places - maybe just append cluster info to "cluster_counts_norm.feather"?
- [x] The channel files are named *_cell_som/meta_cluster_channel_avg.csv, while the pixel cluster count file are named *_cell_som/meta_cluster_count_avgs.csv - can we remove the "s" at the end of "avgs" in the second?
- [x] Can we change the names of the notebooks to "2_Pixie_Cluster_Pixels.ipynb" and "3_Pixie_Cluster_Cells.ipynb" to make it clear these are the notebooks related to the paper? That was brought up by the reviewers - that it wasn't clear what part was Pixie.
- [x] Throughout the two notebooks, they reference other notebooks in ark - can we make sure the names of those notebooks are up to date?

**Comment by alex-l-kong** [comment]
For bullet point 7 (removing the saving of `pixel_som_to_meta.feather`), we can just access the data in the `PixieConsensusCluster` instance instead. Saves us a lot of time.

**Comment by alex-l-kong** [comment]
For bullet point 10, I just ended up deleting `cell_mat.feather` and used `cluster_counts_size_norm.feather` as the consensus matrix.
