### ISSUE TITLE
Porting object segmentation (ezSegmenter) from Matlab/MAUI to Python/Ark

### ISSUE THREAD

**Issue by bryjcannon** [angelolab/ark-analysis#847]
**Is your feature request related to a problem? Please describe.**

- Need an easily accessible, open source object segmenter tool for identifying and creating single object data in MIBI data, primarily focusing on acellular (e.g. plaques, tangles) or cellular (microglia, astrocytic, dendritic cell projections) features.

- ezSegmenter has been used to solve the above but is currently a part of eventually-deprecated MAUI and is written in MATLAB. 

**Describe the solution you'd like**

- Create open-access object segmenter jupyter notebook(s) for MIBI or other TIFF data, i.e. a python-based ezSegmenter.
- Ideally a mixture of jupyter notebook functionality + Mantis image viewer built for this fits into the current MIBI image segmentation pipeline alongside primary MESMER segmentation and Pixie pixel clustering.

- Primary functionality (segmentation, merging, composite building) has been coded out. Need help integrating this into Ark image I/O standards, user interfaces (i.e. jupyter notebooks and Mantis integration)

**Additional context**
[Full project scope notes here](https://docs.google.com/document/d/1RwrbHzgqStRwcs7VINxrFzlPyVOxr8XC4d6IQ4Kv-I0/edit#) 
Outline for segmenting and merging soma-based (MESMER) and projection-based (ezSeg) objects:

![ezSeg_Ark_workflow_diagram_v1_WHITEARROW (1)](https://user-images.githubusercontent.com/18650480/205137062-755d14d5-b08f-4ed2-af24-cfcda2a50806.png)

General outline of expected user experience for ezSegment-ing and merging:

![Ark_ezSeg_basic_workflow drawio_GREENARROWS](https://user-images.githubusercontent.com/18650480/205135854-be4b21f4-60f5-4436-bf20-d7d8294b45d9.png)

**Comment by bryjcannon** [comment]
@alex-l-kong @ngreenwald Figured I'd start here and then work more directly with @alex-l-kong to build out the design doc?

**Comment by ngreenwald** [comment]
Yeah, lets discuss tomorrow, I think Sri might have more bandwidth since Alex is working on revisions for Pixie paper

**Comment by bryjcannon** [comment]
Looking through the fiber_segmentation.py, there is a lot of overlap that can probably be re-used here. Might need to adjust some of the code to handle objects that can be fibrous or not (e.g. plaques), but otherwise could use the contained functions as the actual segmentation file.

Main features that don't exist and need to be built out are the merging of cell and object masks, composite channel building, and likely dealing with multiple mask layers in pixie & cell annotation.
