### ISSUE TITLE
Refactor mask generation

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#857]
**Is your feature request related to a problem? Please describe.**
We have a fair amount of duplicate code in these two plotting functions:
https://github.com/angelolab/ark-analysis/blob/main/ark/utils/plot_utils.py#L24

https://github.com/angelolab/ark-analysis/blob/main/ark/utils/plot_utils.py#L91

In addition, the shared code is not modular enough to enable it to be reused for other plotting. It's a fairly common task to have a segmentation mask and want to color the cells given a provided set of labels. We should refactor these two functions as necessary to create a core conserved function

**Describe the solution you'd like**
I wrote something for my own project that does something similar. The proposed solution doesn't need to be exactly this, but similar in spirit. 

def create_cell_overlay(cell_table, seg_folder, fovs, cluster_col, plot_dir, save_names):
    cell_subset = cell_table[cell_table['fov'].isin(fovs)]
    cell_subset['unique_ids'] = pd.factorize(cell_subset[cluster_col])[0] + 1

    # import viridis colormap from mpl
    num_categories = np.max(cell_subset.unique_ids)
    cm_values = cm.get_cmap('Paired', num_categories - 1)

    # get RGB values from cm_values
    rgb_values = cm_values(np.arange(num_categories - 1))

    # combine with all black for background
    rgb_values = np.vstack((np.array([0, 0, 0, 1]), rgb_values))

    new_cmap = colors.ListedColormap(rgb_values)

    for idx, image in enumerate(fovs):
        seg_mask = io.imread(os.path.join(seg_folder, image + '_feature_0.tif'))[0]

        edges = find_boundaries(seg_mask, mode='inner')
        seg_mask = np.where(edges == 0, seg_mask, 0)

        # convert string entries in pandas df to unique integers
        cell_subset_plot = cell_subset[cell_subset['fov'] == image]
        labels_dict = dict(zip(cell_subset_plot['label'], cell_subset_plot['unique_ids']))

        # relabel the array
        relabeled_img_array = data_utils.relabel_segmentation(seg_mask, labels_dict)

        output = new_cmap(relabeled_img_array / np.max(relabeled_img_array))
        io.imsave(os.path.join(plot_dir, save_names[idx]), output)

**Comment by ngreenwald** [comment]
This would actually be quite useful to have as a general function. Some additional useful points:
1. User-provided or default color mask
2. Consistent coloring across multiple images, assigning the same cell type the same color each time
3. The option to show or hide the colormap, to return as modified array or save as an image

**Comment by ngreenwald** [comment]
A third addition: option to supply a continuous gradient, rather than binary assignment, for each cell, and color the segmentation mask by the intensity of the continuous variable

**Comment by srivarra** [comment]
@ngreenwald 

Cell Clustering Sample Image:
![cell_clustering_fov1](https://github.com/angelolab/ark-analysis/assets/8909315/e355f47a-a4ee-4706-93ba-c9c10c5730a0)

Neighborhood Analysis Sample Image:
![neighborhood_analysis_fov6](https://github.com/angelolab/ark-analysis/assets/8909315/29f03724-bd34-4c3d-829a-13953847617c)

---
I added a function which converts a numpy array to a discrete colormap. Is there any place in the notebooks for it, or is it better to leave it out of the notebooks?
