### ISSUE TITLE
`create_mantis_dir` assumes segmentation overlay extension is the same as the pixel/cell overlay extension

### ISSUE THREAD

**Issue by cliu72** [angelolab/ark-analysis#862]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
In the `create_mantis_dir` function, it assumes that the segmentation extension is the same as the extension of the overlay mask:
https://github.com/angelolab/ark-analysis/blob/de39b62b1c310a3f63549b2238c8e72af9ece56f/ark/utils/plot_utils.py#L504

This causes errors when the segmentation mask suffix and overlay mask suffix are different. In my testing, I am using segmentation masks that end in ".tif", but in the pixel clustering notebook, the default is to generate the pixel masks using ".tiff."

**Expected behavior**
Be able to read ".tif" or ".tiff."

**To Reproduce**
![image](https://user-images.githubusercontent.com/11382352/207501508-b4383314-90e6-4803-8469-f77758ed78b5.png)

**Comment by alex-l-kong** [comment]
@cliu72 we recently enforced a convention in our repo where we only use `.tiff` extensions, I'm guessing your data was generated before we implemented this change.

@ngreenwald is it worth making our codebase backwards compatible for `.tif` files (which essentially means undoing the changes we made for this PR)?

**Comment by alex-l-kong** [comment]
@ngreenwald @cliu72 actually, it's gonna be far easier to include a function in the `ark` pipeline (towards the beginning) to convert input data from `.tif` to `.tiff` format.

**Comment by ngreenwald** [comment]
I agree, we made this change after candace generated the initial segmentation tifs, which is what lead to the error. If we find that many external users loading in segmentations from other software, we can add a conversion script, but until then I think it'll be simpler to assume people are using the pipeline to generate them.

**Comment by cliu72** [comment]
The entire pipeline currently works for segmentation files with the ".tif" extension, except for this last step (`seg_suffix` is a parameter to many of the functions in the notebook). Regarding this specific issue I opened, I think logically it doesn't make sense for the `mask_name` to use the seg_suffix_ext since those are different files. I think it makes more sense to specify a mask_suffix_ext, since there is a seg_suffix_ext anyways.

In general, I think my paper is being marketed as "cross-platform" and doesn't require people to generate their segmentation masks using Mesmer. I'm worried we'll run into a reviewer having an issue again. Is there a reason why the support for `.tiff` was removed?

**Comment by ngreenwald** [comment]
We previously had a mix of .tif and .tiff files, which meant we had to keep track of which files ended with which. The goal is to be able to do what you suggested with the mask overlay (assume everything ends with .tiff). If you think its worth it for this function to take in `seg_suffix` that's totally fine

**Comment by cliu72** [comment]
Gotcha. For this specific issue, the only change I am requesting is that this line:
https://github.com/angelolab/ark-analysis/blob/de39b62b1c310a3f63549b2238c8e72af9ece56f/ark/utils/plot_utils.py#L504

be changed to:
`mask_name: str = mn + mask_suffix + ".tiff" `

The function currently already takes in a `seg_suffix` anyways, so there is no need to make changes there.

I'm going to open a new issue for the generalizability of .tif thing.
