### ISSUE TITLE
Check for cross-platform compatibility

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#864]
**Is your feature request related to a problem? Please describe.**
We made a number of changes to Pixie/ark as part of the pyFlowSOM process. We should verify that none of these were breaking changes

**Describe the solution you'd like**
Once we have a new docker image, confirm that pixel and cell clustering works on the MIBIAN, on a mac laptop, on Ben's laptop, etc.

**Comment by alex-l-kong** [comment]
ark-analysis image v0.5.0 has been up for some time now, think it's a good time to start looking into this. Here're the devices we need to support, feel free to add more to this checklist:

- [X] Mac
- [ ] Windows (personal)
- [ ] MIBIAN

Mac has been verified. I can handle MIBIAN, @srivarra can you verify on Windows?

**Comment by srivarra** [comment]
@alex-l-kong I can verify that ark-analysis v0.5.0 works on my Windows laptop

**Comment by alex-l-kong** [comment]
@ngreenwald v0.5.1 works on MIBIAN for Pixie as well. If there are no other computers to check, recommend closing the issue.

**Comment by ngreenwald** [comment]
Awesome, good stuff
