### ISSUE TITLE
Make `ark` pip installable

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#865]
**Is your feature request related to a problem? Please describe.**
Now that pyFlowSOM is pip installable, we'll need to ensure `ark` is as well. 

**Describe the solution you'd like**
Once the R code is gone and the docker updates PRs are in, we should update the build process to generate cross platform builds. We may need to tweak the Travis settings to support this.

**Comment by cliu72** [comment]
I believe pyFlowSOM is not pip installable on mac right now. Zak said we'd need to pay for that. Talked to @srivarra and he said it'd be easy for him to do (if we do pay for it). Can we just go ahead and pay for that? Or look into free options? Or just make the whole world get rid of macs?

**Comment by srivarra** [comment]
@cliu72 It's easy for Intel Macs since Travis supports that architecture, but they do not have Apple Silicon Runners as of now. See [cibuildwheel for supported CI + architectures](https://github.com/pypa/cibuildwheel#usage)

**Comment by cliu72** [comment]
So I guess the two options are to pay for travis and have it on intel macs only (sorry everyone with apple silicons), or completely move away from travis for apple silicon support?

**Comment by ngreenwald** [comment]
And it has to be built on the architecture it's designed for? i.e. even though we don't care about testing against silicon, just having wheels, the wheels need to be built on that exact OS? How did Zak get around that issue for pyFlowSOM? I thought you tried pip installing on your mac and it worked

**Comment by srivarra** [comment]
I was able to pip install it because I have a bunch of C header files / libraries I installed with `homebrew`. A `pip` installation without a pre-build wheel will basically clone the source code and build it locally against those C dependencies.

**Comment by ngreenwald** [comment]
And that wheel needs to be built via Travis on the same exact system?
It sounded like github actions also doesn't currently support this, right?

**Comment by srivarra** [comment]
After looking through the [MacOS](https://docs.travis-ci.com/user/reference/osx) and [Multi-arch CPU](https://docs.travis-ci.com/user/multi-cpu-architectures) build documentation, it looks like we can only build for ARM on Linux with Travis. We are not able to build for solely ARM on MacOS.

Github Actions supports supports building native packages on Apple Silicon, this is what [scikit-learn](https://github.com/scikit-learn/scikit-learn/blob/main/.github/workflows/wheels.yml) does.

However one thing we could try is dual-architecture [Universal Builds](https://cibuildwheel.readthedocs.io/en/stable/faq/#universal2). This is a wheel which contains both Intel x86_64, and ARM wheels. Therefore it's double the size.

From that section, this in particular stands out:

> Apple Silicon wheels are not built by default on Intel runners, but can be enabled by adding extra archs to the [CIBW_ARCHS_MACOS option](https://cibuildwheel.readthedocs.io/en/stable/options/#archs) - e.g. x86_64 arm64. Cross-compilation is provided by the Xcode toolchain.

So, it looks like we can attempt it, but it doesn't have the ✅ of approval on the [CI service / OS+arch matrix](https://cibuildwheel.readthedocs.io/en/stable/#usage).

**Comment by ngreenwald** [comment]
Okay, well it seems like that would be easier than switching to github actions, right? It seems like eventually we'll want to switch, as I imagine github will continue to improve and further integrate GA into the workflow. But for now, if we can just make a relatively simple change, that would be ideal.
