### ISSUE TITLE
Have `load_imgs_from_tree` also look for .tif files

### ISSUE THREAD

**Issue by cliu72** [angelolab/ark-analysis#866]
**Is your feature request related to a problem? Please describe.**
Could we make the `load_imgs_from_tree` function also read in ".tif"? I think it's fine if all image files that are being written by ark are ".tiff", but I think it would be helpful to be able to read in images that are ".tif." Especially for my paper, we are marketing Pixie as being very generalizable. I think this would be (hopefully) an easy thing to add back in. I'm only requesting that the 2 Pixie notebooks be able to read in ".tif" files, not the whole pipeline.

To me, it doesn't seem like it would be that bad, since the function is already reading in jpeg and png. Seems like we would just need to change these lines:
https://github.com/angelolab/ark-analysis/blob/a98648c8f3bd11fd713be3b41eb885bf5058d93f/ark/utils/load_utils.py#L134 and
https://github.com/angelolab/ark-analysis/blob/a98648c8f3bd11fd713be3b41eb885bf5058d93f/ark/utils/load_utils.py#L140
to look for ".tif" files as well.

**Describe the solution you'd like**
Similarly to how `load_imgs_from_tree` takes in jpeg/pngs, have it take in tif files.

**Describe alternatives you've considered**
Alex suggested adding something in the beginning to turn everything into "tiffs", but I don't think it's necessary since we already have the ability to read in jpegs/pngs.

**Comment by ngreenwald** [comment]
Sure, we can add it back in. If we always produce .tiff files, then it's just these couple load functions that need to handle the alternative
