### ISSUE TITLE
Imports issue with ark-analysis jupyter

### ISSUE THREAD

**Issue by dtebaykin** [angelolab/ark-analysis#872]
Running the first block of code in the notebook 1 of ark-analysis pipeline version 0.4.4 produces this error:

<img width="1294" alt="Screen Shot 2022-12-20 at 1 09 38 PM" src="https://user-images.githubusercontent.com/8460227/208767877-be7afadb-799a-43ff-84ab-4d5814bd6a68.png">

All 4 baseline notebooks rely on the example_dataset.py, so all of them fail the first step.

**Comment by srivarra** [comment]
Try running `start_docker` with the `-u` flag. I believe that solved the issue a couple of others were having.

**Comment by dtebaykin** [comment]
./start_docker.sh -u 
The above solved the imports issue. Should that be edited into the README.md file and the ark-analysis setup guide? I tested it on a fresh 0.4.4 pull on 2 machines with new docker installs 4.15.0

**Comment by srivarra** [comment]
@dtebaykin We already have a small blurb on updating [here](https://github.com/angelolab/ark-analysis#updating-the-repository). Updating is mainly only for testing out the latest features merged into main after the latest release. This issue will be fixed in the next full release however.

**Comment by ngreenwald** [comment]
Is this related to reverting our docker back to a previous version while waiting for the python PR to get merged in? Or this is indicating a more general problem that will persist?

**Comment by srivarra** [comment]
@ngreenwald Yeah it had to do with the previous build we had to do. It should be resolved once we do a clean build in the future.
