### ISSUE TITLE
3_pixie_cluster_cells notebook: Pixel meta cluster that doesnt map into any cell 

### ISSUE THREAD

**Issue by HPiyadasa** [angelolab/ark-analysis#882]
**Describe the bug**
Pixel clustering shows a meta cluster with ~3000 pixels (image attached). When proceeding to the pixie cluster cell notebook, cluster_counts_size_norm.feather file generated has NAs causing cell consensus clustering to output error (input X contains NaN). Going back to pixel clustering notebook and merging this cluster with a different cluster and coming back to cell clustering resolves the issue.

**Expected behavior**
ignore or delete any NaN columns from relevant files when going into cell consensus clustering. 

**To Reproduce**
Can provide test dataset and parameters if required. 

Please either copy/paste or screenshot all of the code you ran which produced the error. In addition, copy the full error message. 
<img width="1373" alt="Screenshot 2023-01-17 at 10 32 29 AM" src="https://user-images.githubusercontent.com/62519486/212984357-28339634-fbd3-45bf-93cd-1a7dada5443d.png">

<img width="1384" alt="Screenshot 2023-01-17 at 12 41 29 PM" src="https://user-images.githubusercontent.com/62519486/212983879-a550a747-5610-428f-92ab-c1a23cd76a1f.png">

<img width="1217" alt="Screen Shot 2023-01-13 at 5 24 25 PM" src="https://user-images.githubusercontent.com/62519486/212985259-d1d825c6-c430-4053-b6c1-9f4a8cfd2282.png">
<img width="1176" alt="Screen Shot 2023-01-13 at 5 24 42 PM" src="https://user-images.githubusercontent.com/62519486/212985263-8785827e-d325-4a18-a156-ce57fd18b2da.png">

**Comment by alex-l-kong** [comment]
@HPiyadasa I think it's more important to figure out why these NaNs are appearing in the first place. This file is created by an internal function `create_c2pc_data`, I'll check and see if there's a hidden bug in it first.

**Comment by cliu72** [comment]
I looked at this with Hadeesha for a bit and I'm pretty sure the root of the issue is when there are pixel meta clusters (or clusters) that are not in any cell. When we looked at "cluster_counts.feather", there were just 0's for the pixel cluster that didn't exist in any cell, but in "cluster_counts_size_norm.feather", it became all NA's (I think because of the size normalization). As a result, the SOM is training with a column of all NA's. Interestingly, the weights file seems to be okay (correct dimensions).

**Comment by alex-l-kong** [comment]
> I looked at this with Hadeesha for a bit and I'm pretty sure the root of the issue is when there are pixel meta clusters (or clusters) that are not in any cell. When we looked at "cluster_counts.feather", there were just 0's for the pixel cluster that didn't exist in any cell, but in "cluster_counts_size_norm.feather", it became all NA's (I think because of the size normalization). As a result, the SOM is training with a column of all NA's. Interestingly, the weights file seems to be okay (correct dimensions), but all the clusters assigned are 0 (see screenshot from Hadeesha above).

Yes that would make sense, and I agree that's the best fix.
