### ISSUE TITLE
`percent_var_exp` is not calculated in `spLDA.processing.compute_topic_eda()`

### ISSUE THREAD

**Issue by srivarra** [angelolab/ark-analysis#888]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**

In `spLDA.processing.compute_topic_eda`

https://github.com/angelolab/ark-analysis/blob/7aadf27cb64e16fd0c293e1d1a36fb644c9a5425/ark/spLDA/processing.py#L276-L302

the statistic `percent_var_exp` is not implemented. Initially, when using less up-to-date versions of `seaborn`, `pandas`, and `scikit-learn`, this does not cause tests to fail as `NaN`s were not handled. But when it comes to loosening the requirements in #886, using the latest version of each cause `ark.analysis.visualize_test.test_visualize_topic_eda()` to fail. 

What should the `percent_var_exp` function look like? Or should it be removed as it isn't one of the five metrics mentioned in the docstring for `compute_topic_eda`.

**Expected behavior**
Either an implemented version of `percent_var_exp` or remove it.
**To Reproduce**
Run either:
- `LDA_Preprocessing.ipynb`
- `ark.analysis.visualize_test.test_visualize_topic_eda()`

with `seaborn>=0.12`.

**Comment by ngreenwald** [comment]
Remove it for now, as we are not heavily using this notebook.
