### ISSUE TITLE
OME-TIFF_Conversion Template

### ISSUE THREAD

**Issue by AnnaBeeBiomed** [angelolab/ark-analysis#909]
**Describe the bug**
This is from the origin/main branch (latest version as of this post). The error is as described in the image below. Running help(ark.utils) to list the packages within ark.utils shows that load_utils package is missing.

**Expected behavior**
The ome_tiff conversion script should progress to the next stage.  

**To Reproduce**

![OME_TIFFconversion](https://user-images.githubusercontent.com/68141051/218613342-5ea892cd-7dec-4131-8cfd-7da4771706bf.PNG)

**Comment by srivarra** [comment]
@AnnaBeeBiomed This will be fixed in #895.
