### ISSUE TITLE
Add seed to `som` function in Pixie notebooks

### ISSUE THREAD

**Issue by cliu72** [angelolab/ark-analysis#910]
**Is your feature request related to a problem? Please describe.**
Add the ability to change the random seed for the SOM function

**Describe the solution you'd like**
In both pixel and cell clustering, add `seed` parameter (will probably need a small adjustment to cluster_helpers.py, and then both train_pixel_som and train_cell_som functions). I think it would be helpful to have the seed parameter explicitly listed in the notebooks.

**Comment by alex-l-kong** [comment]
We'll need to first make a new release of `pyFlowSOM` in order for this to propagate, since the current version still uses `deterministic` and not `seed`. @srivarra can we go about doing this?

**Comment by srivarra** [comment]
@alex-l-kong Yeah, I'll go ahead and make the new release.
