### ISSUE TITLE
ValueError: No images found in designated folder

### ISSUE THREAD

**Issue by maharahim** [angelolab/ark-analysis#926]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
I can't generate cell expression matrix after segmentation, with error: ValueError: No images found in designated folder

**Expected behavior**
I would expect cell expression matrices to generate, as there was no problem with file structure in the notebook up until that point. 
I have ran git pull and updated docker prior to running segment_images notebook. I am using the same file structure that I used a few weeks back with no issues:
image_data/
 fov1/
   marker.tiff

**To Reproduce
<img width="1126" alt="Screen Shot 2023-02-16 at 3 50 10 PM" src="https://user-images.githubusercontent.com/72824413/219513919-5360d2c9-66b9-4078-8d63-9027237750d4.png">
**

**Comment by maharahim** [comment]
I changed my input files from .ome.tif and .tif to .tiff which seemed to have fixed this issue.

**Comment by srivarra** [comment]
@maharahim A little while ago we defaulted to using `".tiff"` instead of `".tif"` across Ark. We'll add a bit of documentation to make this more clear for the end user.

**Comment by ngreenwald** [comment]
I think it would be good to 1) print the name of the folder that didn't have any images, and 2) list what is in the folder. This will help with debugging this message
