### ISSUE TITLE
Modular Mask Generation

### ISSUE THREAD

**Issue by srivarra** [angelolab/ark-analysis#927]
*This is for internal use only; if you'd like to open an issue or request a new feature, please open a bug or enhancement issue*

### Instructions
This document should be filled out prior to embarking on any project that will take more than a couple hours to complete. The goal is to make sure that everyone is on the same page for the functionality and requirements of new features. Therefore, it's important that this is detailed enough to catch any misunderstandings beforehand. For larger projects, it can be useful to first give a high-level sketch, and then go back and fill in the details. For smaller ones, filling the entire thing out at once can be sufficient.  

**Relevant background**

There are two plotting overlays which share many of the same functionalities:
- `plot_utils.plot_pixel_cell_cluster_overlay` 
- `plot_utils.plot_neighborhood_cluster_result`

It would be beneficial to generalize the plotting for pixel, cell, and neighborhood clusters both for maintenance, and on the user's end.

In addition, we can expand the customization efforts for generating the cluster overlays:

1. Allow users to provide a color mask they like
   1. Add an option to supply a continuous gradient as well instead of categorical assignment. Color the segmentation mask by the intensity of the continuous variable.
2. An option to display or hide the legend
   1. The legend should account for gradients within the categorical labels.
3. Make sure the changes work with the *Image Stitching* Notebook.
4. For extensibility reasons, it should be flexible enough to support future clustering tasks

**Design overview**

Create a user facing wrapper function which handles input validation (paths, fovs + data array), and cluster information. It will load the `DataArray` and then filter out the FOVs to get the mask of. Then
**Code mockup**

```python
import alpineer

def plot_cluster_overlay(
    cluster_xr: xr.DataArray,
    cluster_col: str,
    fovs: List[str],
    assignment_type: Optional[str] = "categorical",
    cmap_name: Union[str, matplotlib.colors.Colormap],
    cell_ids: List[str],
    cluster_id_mapping: Optional[Union[pathlib.Path, str, pd.DataFrame]] = None,
    legend: bool,
    fig_size: Tuple[int, int],
    save_dir: Union[pathlib.Path, str],
    display_image: Optional[str],
    ) -> None

    # Input validation
    alpineer.misc_utils.verify_in_list(fovs, cluster_xr.fovs.values)
    alpineer.misc_utils.verify_in_list(assigmnemt_type, ["categorical", "continuous"])

    if assignment_type == "continuous" and type(cmap_name) in [Sequential, Sequential2, Cyclic]:
        # define the colormap, add black for empty slide
        mycols = cm.get_cmap(cmap_name, k).colors
        mycols = np.vstack(([0, 0, 0, 1], mycols))
        cmap = colors.ListedColormap(mycols)
        bounds = [i-0.5 for i in np.linspace(0, k+1, k+2)]
        norm = colors.BoundaryNorm(bounds, cmap.N)

        # check if `cmap` is a Sequential, Sequential2 or Cyclic colormap, not a Qualitative one
    if assignment_type == "continuous" and cmap_name == Qualitative:
        # Notify the user that a continuous colormap cannot be constructed from a Qualitative one.
    
    if type(cluster_id_to_name_path) in (pathlib.Path, str):
        # Load and process the cluster_id_to_name csv file
        cluster_id_to_name = pd.read_csv(cluster_id_to_name_path)
        misc_utils.verify_same_elements(
            cluster_mapping_cols=cluster_id_to_name.columns.values,
            required_cols=['metacluster', 'mc_name']
        )

        # Subset on metacluster and mc_name
        metacluster_id_to_name = cluster_id_to_name[['metacluster', 'mc_name']].copy()

        # take only the unique pairs
        metacluster_id_to_name = metacluster_id_to_name.drop_duplicates()

        # sort by metacluster id ascending, this will help when making the colormap
        metacluster_id_to_name = metacluster_id_to_name.sort_values(by='metacluster')

        # assert the metacluster index in colors matches with the ids in metacluster_id_to_name
        misc_utils.verify_same_elements(
            metacluster_colors_ids=list(metacluster_colors.keys()),
            metacluster_mapping_ids=metacluster_id_to_name['metacluster'].values
        )

        # use metacluster_colors to add the colors to metacluster_id_to_name
        metacluster_id_to_name['color'] = metacluster_id_to_name['metacluster'].map(
            metacluster_colors
        )
    ...

    for fov in fovs:
        cluster_mask = cluster_xr[cluster_xr[fov_col] == fov].values

        # Create the figure

        if legend:
            # Add the legend
            if cluster_id_to_name_path:
                # Add the custom legend cluster names
        
        # Plotting
        ...

        if save_dir:
            misc_utils.save_figure(save_dir, f"{fov}.png)
    

```

**Required inputs**

Currently, the parameters for the two functions are as follows:

```python
def plot_neighborhood_cluster_result(
    img_xr, 
    fovs, 
    k, 
    save_dir=None, 
    cmap_name='tab20',
    fov_col='fovs', 
    figsize=(10, 10)):
    """Takes an xarray containing labeled images and displays them.
    Args:
        img_xr (xarray.DataArray):
            xarray containing labeled cell objects.
        fovs (list):
            list of fovs to display.
        k (int):
            number of clusters (neighborhoods)
        save_dir (str):
            If provided, the image will be saved to this location.
        cmap_name (str):
            Cmap to use for the image that will be displayed.
        fov_col (str):
            column with the fovs names in `img_xr`.
        figsize (tuple):
            Size of the image that will be displayed.
    """
```

and 

```python
def plot_pixel_cell_cluster_overlay(img_xr,
    fovs,
    cluster_id_to_name_path, 
    metacluster_colors,
    save_dir=None, 
    fov_col='fovs', 
    figsize=(10, 10)):
    """Overlays the pixel and cell clusters on an image

    Args:
        img_xr (xarray.DataArray):
            xarray containing labeled pixel or cell clusters
        fovs (list):
            list of fovs to display
        cluster_id_to_name_path (str):
            a path to a CSV identifying the pixel/cell cluster to manually-defined name mapping
            this is output by the remapping visualization found in `metacluster_remap_gui`
        metacluster_colors (dict):
            maps each metacluster id to a color
        save_dir (str):
            If provided, the image will be saved to this location.
        fov_col (str):
            column with the fovs names in `img_xr`.
        figsize (tuple):
            Size of the image that will be displayed.
    """

```

We can merge the two to get:

- `cluster_xr`: An `xarray.DataArray` storing the labeled clusters
- `cluster_col`: The `xarray.DataArray` axis which will used for gathering the clusters
- `fovs`: A `List[str]` for the FOVs to display
- `save_dir`: A `pathlib.Path` or `str` directory to save the clustering masks / overlays to
- `cmap`: Either a pre-existing colormap found on the [docs](https://matplotlib.org/stable/tutorials/colors/colormaps.html), which can be verified in `matplotlib.colormaps`. This can also be a pre-existing colormap from external libraries such as [CMasher](https://cmasher.readthedocs.io/index.html).
- `legend`: A `bool`, flagging whether the legend should be shown or not
- `figsize`: A `tuple`, the size of the image which will be displayed
- `cell_ids`: A `List[str]`, a list of cell IDs so the ID to color mapping can stay the same for any image of a particular dataset (good if a cell doesn't exist in a particular image)
- `cluster_id_mapping`: A `pathlib.Path` or `str` pointing to a `csv` file generated by `metacluster_remap_gui`, or any cluster ID to a user given "name". This should also support data frames.
- `assignment_type`: A `str`, either `"categorical"` or `"continuous"`, used to color the segmentation masks.
- `display_image`: A `str`, either `"figure"` or `"tiff"`. The user can specify if they want the colored tiff itself, or a Matplotlib styled plot.

**Output files**

- Clustering masks / overlays have an option to be saved. They can be saved as Matplotlib figures, or as colored tiff files.
- Will need to edit the Pixie pipeline to add an option for returning the cluster ID to name data frames.

**Timeline**
Give a rough estimate for how long you think the project will take. In general, it's better to be too conservative rather than too optimistic. 
- [ ] A couple days
- [x] A week
- [ ] Multiple weeks. For large projects, make sure to agree on a plan that isn't just a single monster PR at the end. 

Estimated date when a fully implemented version will be ready for review: 2/24

Estimated date when the finalized project will be merged in: 2/28

**Comment by srivarra** [comment]
@ngreenwald Is there anything else to consider?

**Comment by ngreenwald** [comment]
A couple things: 

- Sometimes the user will want to plot one image at a time. Since not all images will have all cell IDs, different colors get assigned to different cells in each image. We'll likely need to take in a list of all possible cell IDs, so that the mapping is the same each time
- the cluster_id_to_name_path would be better if it was more general. Being able to pass in the df directly, and with more general names, will allow this to work in different contexts. This may require tweaking how Pixie saves this information, or a loading function that swaps the names
- For returning the labeled image directly: This should be an option for the user. Sometimes, rather than a figure, you want the actual tiff image, but colored by the colormap. i.e. 
```
new_colormap = cmap()....
labeled_img = load_from_dir....
colored_tiff = new_colormap(labeled_img)
```

**Comment by srivarra** [comment]
@ngreenwald Added those modifications in.

**Comment by ngreenwald** [comment]
Looks good!
