### ISSUE TITLE
Removed pairwise enrichment script

### ISSUE THREAD

**Issue by chiarasch** [angelolab/ark-analysis#933]
Question:
I intended to use your script for pairwise enrichment analysis, but you seem to have removed it yesterday? (https://github.com/angelolab/ark-analysis/blob/main/templates/example_pairwise_spatial_enrichment.ipynb)
Could you provide the script again or can I find the code elsewhere? Thanks a lot!

**Comment by ngreenwald** [comment]
We had some reports that there may be a bug in the underlying logic of the script, so we removed it until we can investigate further. An archived version is still available in prior commits, which are you welcome to use in the interim.

**Comment by chiarasch** [comment]
Thank you!
