### ISSUE TITLE
Document supported python versions, expand versions

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#965]
**Is your feature request related to a problem? Please describe.**
The current `ark` build only supports python 3.8. If you try and pip install using 3.9, this unintuitive error message comes up: 
<img width="1568" alt="image" src="https://user-images.githubusercontent.com/13770365/228660324-78643084-ac20-4881-b3d3-e3de05b34394.png">

**Describe the solution you'd like**
We should more clearly indicate which versions are supported. We should also begin testing multiple versions of python to make the subsequent process of switching/deprecating relatively seamless.

**Comment by srivarra** [comment]
The [NumPy drop schedule](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule) states that as of April 14, 2023, new releases of NumPy (version 1.21+) will not be available for Python 3.8.
